export type MarketLocation={
  slug:string;
  name:string;
  state:string;
  region:"Haryana"|"Chandigarh"|"Punjab"|"Rajasthan";
  aliases:string[];
  nearby:string[];
  corridor:string;
  marketNote:string;
  legacyBuyPath?:string;
  legacySellPath?:string;
  hub?:boolean;
};

export const marketLocations:MarketLocation[]=[
  {slug:"haryana",name:"Haryana",state:"Haryana",region:"Haryana",aliases:[],nearby:["Chandigarh","Delhi NCR","Punjab","Rajasthan"],corridor:"statewide Haryana",marketNote:"ROHILLA DRIVE accepts buyer and seller requirements across Haryana and can follow up even when the exact vehicle is not currently published.",hub:true},
  {slug:"ambala",name:"Ambala",state:"Haryana",region:"Haryana",aliases:["Ambala","Ambala City","Ambala Cantt"],nearby:["Yamunanagar","Panchkula","Kurukshetra","Chandigarh"],corridor:"Ambala–Chandigarh and Ambala–Yamunanagar corridors",marketNote:"Ambala is the home market of Rohilla Multibrand Cars and the primary operating base for ROHILLA DRIVE.",legacyBuyPath:"/used-cars-ambala",legacySellPath:"/sell-car-ambala"},
  {slug:"bhiwani",name:"Bhiwani",state:"Haryana",region:"Haryana",aliases:["Bhiwani"],nearby:["Rohtak","Hisar","Charkhi Dadri","Jhajjar"],corridor:"Bhiwani–Rohtak–Hisar belt",marketNote:"Buyers and sellers in Bhiwani can submit a requirement online and continue directly on WhatsApp for follow-up."},
  {slug:"charkhi-dadri",name:"Charkhi Dadri",state:"Haryana",region:"Haryana",aliases:["Charkhi Dadri","Dadri"],nearby:["Bhiwani","Jhajjar","Mahendragarh","Rohtak"],corridor:"Charkhi Dadri–Bhiwani–Jhajjar belt",marketNote:"ROHILLA DRIVE captures used-car buying and selling requirements from Charkhi Dadri without requiring a dealer account for individual sellers."},
  {slug:"faridabad",name:"Faridabad",state:"Haryana",region:"Haryana",aliases:["Faridabad"],nearby:["Palwal","Gurugram","Delhi","Noida"],corridor:"Faridabad–Delhi NCR corridor",marketNote:"Faridabad customers can share exact model, budget and timing or submit a car for sale with private photos."},
  {slug:"fatehabad",name:"Fatehabad",state:"Haryana",region:"Haryana",aliases:["Fatehabad"],nearby:["Hisar","Sirsa","Jind","Hanumangarh"],corridor:"Fatehabad–Hisar–Sirsa belt",marketNote:"Fatehabad requirements are handled through the same ROHILLA DRIVE lead workflow with direct call and WhatsApp options."},
  {slug:"gurugram",name:"Gurugram",state:"Haryana",region:"Haryana",aliases:["Gurugram","Gurgaon"],nearby:["Faridabad","Jhajjar","Rewari","Delhi"],corridor:"Gurugram–Delhi NCR corridor",marketNote:"Gurugram buyers can request specific used cars by model and budget while sellers can submit their vehicle without creating a dealer account."},
  {slug:"hisar",name:"Hisar",state:"Haryana",region:"Haryana",aliases:["Hisar","Hissar"],nearby:["Bhiwani","Fatehabad","Jind","Sirsa"],corridor:"Hisar–Fatehabad–Bhiwani belt",marketNote:"Hisar buyer and seller requirements can be saved online for structured follow-up through ROHILLA DRIVE."},
  {slug:"jhajjar",name:"Jhajjar",state:"Haryana",region:"Haryana",aliases:["Jhajjar"],nearby:["Gurugram","Rohtak","Rewari","Charkhi Dadri"],corridor:"Jhajjar–Gurugram–Rohtak belt",marketNote:"Jhajjar customers can use the buyer requirement form when a specific car is not in live inventory."},
  {slug:"jind",name:"Jind",state:"Haryana",region:"Haryana",aliases:["Jind"],nearby:["Kaithal","Hisar","Rohtak","Karnal"],corridor:"Jind–Kaithal–Rohtak belt",marketNote:"ROHILLA DRIVE accepts used-car purchase and sale requirements from Jind with source-tracked enquiries."},
  {slug:"kaithal",name:"Kaithal",state:"Haryana",region:"Haryana",aliases:["Kaithal"],nearby:["Kurukshetra","Karnal","Jind","Patiala"],corridor:"Kaithal–Kurukshetra–Patiala belt",marketNote:"Kaithal customers can share the exact car they want or request a sell-car callback through the same platform."},
  {slug:"karnal",name:"Karnal",state:"Haryana",region:"Haryana",aliases:["Karnal"],nearby:["Panipat","Kurukshetra","Kaithal","Yamunanagar"],corridor:"Karnal–Panipat–Kurukshetra corridor",marketNote:"Karnal enquiries can be captured even if the requested car is not yet published in the catalogue."},
  {slug:"kurukshetra",name:"Kurukshetra",state:"Haryana",region:"Haryana",aliases:["Kurukshetra","Thanesar","Thānesar"],nearby:["Ambala","Karnal","Kaithal","Yamunanagar"],corridor:"Kurukshetra–Ambala–Karnal corridor",marketNote:"Kurukshetra and Thanesar buyers and sellers can submit requirements directly to ROHILLA DRIVE for follow-up."},
  {slug:"mahendragarh",name:"Mahendragarh",state:"Haryana",region:"Haryana",aliases:["Mahendragarh","Narnaul"],nearby:["Rewari","Charkhi Dadri","Jhajjar","Alwar"],corridor:"Mahendragarh–Narnaul–Rewari belt",marketNote:"Mahendragarh and Narnaul customers can send buying or selling requirements without waiting for a matching live listing."},
  {slug:"nuh",name:"Nuh",state:"Haryana",region:"Haryana",aliases:["Nuh","Mewat"],nearby:["Gurugram","Palwal","Faridabad","Alwar"],corridor:"Nuh–Gurugram–Alwar belt",marketNote:"Nuh used-car requirements can be saved online with model, budget, city and timing for direct follow-up."},
  {slug:"palwal",name:"Palwal",state:"Haryana",region:"Haryana",aliases:["Palwal"],nearby:["Faridabad","Nuh","Gurugram","Delhi NCR"],corridor:"Palwal–Faridabad–Delhi corridor",marketNote:"Palwal buyers and individual sellers can use ROHILLA DRIVE for structured enquiry capture and WhatsApp continuation."},
  {slug:"panchkula",name:"Panchkula",state:"Haryana",region:"Haryana",aliases:["Panchkula"],nearby:["Chandigarh","Ambala","Mohali","Zirakpur"],corridor:"Panchkula–Chandigarh–Ambala tri-city corridor",marketNote:"Panchkula sits in the core tri-city catchment where ROHILLA DRIVE can handle buyer and seller vehicle requirements."},
  {slug:"panipat",name:"Panipat",state:"Haryana",region:"Haryana",aliases:["Panipat"],nearby:["Karnal","Sonipat","Jind","Rohtak"],corridor:"Panipat–Karnal–Sonipat corridor",marketNote:"Panipat customers can share a target model and budget or send a sell-car request for direct follow-up."},
  {slug:"rewari",name:"Rewari",state:"Haryana",region:"Haryana",aliases:["Rewari"],nearby:["Gurugram","Jhajjar","Mahendragarh","Alwar"],corridor:"Rewari–Gurugram–Alwar corridor",marketNote:"Rewari buyer and seller enquiries are supported through the ROHILLA DRIVE lead workflow."},
  {slug:"rohtak",name:"Rohtak",state:"Haryana",region:"Haryana",aliases:["Rohtak"],nearby:["Jhajjar","Bhiwani","Jind","Sonipat"],corridor:"Rohtak–Jhajjar–Bhiwani belt",marketNote:"Rohtak customers can submit exact car requirements or sell-car requests and continue on WhatsApp after the lead is saved."},
  {slug:"sirsa",name:"Sirsa",state:"Haryana",region:"Haryana",aliases:["Sirsa"],nearby:["Fatehabad","Hisar","Hanumangarh","Bathinda"],corridor:"Sirsa–Fatehabad–Hanumangarh belt",marketNote:"Sirsa is covered for used-car buyer and seller enquiry capture even when local inventory is not currently live."},
  {slug:"sonipat",name:"Sonipat",state:"Haryana",region:"Haryana",aliases:["Sonipat","Sonepat"],nearby:["Panipat","Rohtak","Delhi","Jind"],corridor:"Sonipat–Panipat–Delhi corridor",marketNote:"Sonipat buyers can save a model and budget requirement while sellers can request a callback or submit full vehicle details."},
  {slug:"yamunanagar",name:"Yamunanagar",state:"Haryana",region:"Haryana",aliases:["Yamunanagar","Jagadhri"],nearby:["Ambala","Kurukshetra","Saharanpur","Panchkula"],corridor:"Yamunanagar–Ambala–Kurukshetra corridor",marketNote:"Yamunanagar is a nearby operating market for ROHILLA DRIVE, with buyer and seller requirements handled through the same platform."},

  {slug:"chandigarh",name:"Chandigarh",state:"Chandigarh",region:"Chandigarh",aliases:["Chandigarh"],nearby:["Panchkula","Mohali","Zirakpur","Ambala"],corridor:"Chandigarh tri-city and Ambala corridor",marketNote:"Chandigarh buyers and sellers can submit used-car requirements with ROHILLA DRIVE while checking current network inventory."},

  {slug:"punjab",name:"Punjab",state:"Punjab",region:"Punjab",aliases:[],nearby:["Chandigarh","Haryana","Mohali","Patiala"],corridor:"Punjab–Chandigarh–Haryana network",marketNote:"ROHILLA DRIVE accepts buyer and seller requirements from Punjab, with initial focus on markets closest to Chandigarh and Ambala.",hub:true},
  {slug:"mohali",name:"Mohali",state:"Punjab",region:"Punjab",aliases:["Mohali","Sahibzada Ajit Singh Nagar","SAS Nagar"],nearby:["Chandigarh","Panchkula","Zirakpur","Ambala"],corridor:"Mohali–Chandigarh–Panchkula tri-city corridor",marketNote:"Mohali and SAS Nagar are part of the immediate tri-city catchment for used-car buyer and seller requirements."},
  {slug:"zirakpur",name:"Zirakpur",state:"Punjab",region:"Punjab",aliases:["Zirakpur"],nearby:["Chandigarh","Panchkula","Mohali","Ambala"],corridor:"Zirakpur–Chandigarh–Ambala highway corridor",marketNote:"Zirakpur sits directly on the Chandigarh–Ambala corridor and is covered for ROHILLA DRIVE buyer and seller enquiries."},
  {slug:"patiala",name:"Patiala",state:"Punjab",region:"Punjab",aliases:["Patiala"],nearby:["Ambala","Rajpura","Sangrur","Fatehgarh Sahib"],corridor:"Patiala–Rajpura–Ambala corridor",marketNote:"Patiala customers can submit used-car requirements and sell-car enquiries directly through ROHILLA DRIVE."},
  {slug:"fatehgarh-sahib",name:"Fatehgarh Sahib",state:"Punjab",region:"Punjab",aliases:["Fatehgarh Sahib","Sirhind"],nearby:["Patiala","Mohali","Ludhiana","Ambala"],corridor:"Fatehgarh Sahib–Sirhind–Patiala corridor",marketNote:"Fatehgarh Sahib and Sirhind buyer/seller requirements can be captured online and routed for follow-up."},
  {slug:"rupnagar",name:"Rupnagar",state:"Punjab",region:"Punjab",aliases:["Rupnagar","Ropar"],nearby:["Mohali","Chandigarh","Fatehgarh Sahib","Nawanshahr"],corridor:"Rupnagar–Mohali–Chandigarh corridor",marketNote:"Rupnagar and Ropar used-car enquiries are covered through the broader Chandigarh–Punjab network."},
  {slug:"ludhiana",name:"Ludhiana",state:"Punjab",region:"Punjab",aliases:["Ludhiana"],nearby:["Fatehgarh Sahib","Jalandhar","Sangrur","Patiala"],corridor:"Ludhiana–Sirhind–Patiala corridor",marketNote:"Ludhiana buyer and seller requirements can be submitted to ROHILLA DRIVE even when the matching vehicle is outside current live inventory."},
  {slug:"sangrur",name:"Sangrur",state:"Punjab",region:"Punjab",aliases:["Sangrur"],nearby:["Patiala","Ludhiana","Barnala","Kaithal"],corridor:"Sangrur–Patiala–Kaithal belt",marketNote:"Sangrur customers can save buy/sell requirements for structured follow-up through ROHILLA DRIVE."},

  {slug:"rajasthan",name:"Rajasthan",state:"Rajasthan",region:"Rajasthan",aliases:[],nearby:["Haryana","Delhi NCR","Jaipur","Alwar"],corridor:"Rajasthan–Haryana north-west network",marketNote:"ROHILLA DRIVE accepts vehicle buying and selling requirements from Rajasthan, beginning with major and Haryana-border markets.",hub:true},
  {slug:"alwar",name:"Alwar",state:"Rajasthan",region:"Rajasthan",aliases:["Alwar"],nearby:["Rewari","Nuh","Bhiwadi","Jaipur"],corridor:"Alwar–Rewari–Gurugram corridor",marketNote:"Alwar is a natural Haryana-border market for buyer and seller vehicle requirements."},
  {slug:"bhiwadi",name:"Bhiwadi",state:"Rajasthan",region:"Rajasthan",aliases:["Bhiwadi"],nearby:["Rewari","Gurugram","Alwar","Dharuhera"],corridor:"Bhiwadi–Dharuhera–Gurugram corridor",marketNote:"Bhiwadi customers can submit specific used-car requirements or a car-for-sale enquiry through ROHILLA DRIVE."},
  {slug:"jaipur",name:"Jaipur",state:"Rajasthan",region:"Rajasthan",aliases:["Jaipur"],nearby:["Alwar","Sikar","Ajmer","Delhi NCR"],corridor:"Jaipur–Alwar–Delhi corridor",marketNote:"Jaipur is covered as a major Rajasthan market for ROHILLA DRIVE buyer and seller enquiry capture."},
  {slug:"sikar",name:"Sikar",state:"Rajasthan",region:"Rajasthan",aliases:["Sikar"],nearby:["Jaipur","Jhunjhunu","Churu","Rewari"],corridor:"Sikar–Jhunjhunu–Jaipur belt",marketNote:"Sikar customers can share model, budget and timing or submit a sell-car request for follow-up."},
  {slug:"jhunjhunu",name:"Jhunjhunu",state:"Rajasthan",region:"Rajasthan",aliases:["Jhunjhunu"],nearby:["Sikar","Churu","Mahendragarh","Rewari"],corridor:"Jhunjhunu–Sikar–Mahendragarh belt",marketNote:"Jhunjhunu is covered for used-car enquiries through the Rajasthan–Haryana network."},
  {slug:"churu",name:"Churu",state:"Rajasthan",region:"Rajasthan",aliases:["Churu"],nearby:["Sikar","Jhunjhunu","Bikaner","Hisar"],corridor:"Churu–Sikar–Hisar belt",marketNote:"Churu buyer and seller vehicle requirements can be saved online for direct follow-up."},
  {slug:"hanumangarh",name:"Hanumangarh",state:"Rajasthan",region:"Rajasthan",aliases:["Hanumangarh"],nearby:["Sirsa","Sri Ganganagar","Fatehabad","Bathinda"],corridor:"Hanumangarh–Sirsa–Sri Ganganagar belt",marketNote:"Hanumangarh is included in the north Rajasthan coverage area closest to Haryana and Punjab."},
  {slug:"sri-ganganagar",name:"Sri Ganganagar",state:"Rajasthan",region:"Rajasthan",aliases:["Sri Ganganagar","Ganganagar"],nearby:["Hanumangarh","Abohar","Sirsa","Bathinda"],corridor:"Sri Ganganagar–Hanumangarh–Sirsa belt",marketNote:"Sri Ganganagar buyers and sellers can submit vehicle requirements to ROHILLA DRIVE for follow-up."},
  {slug:"bharatpur",name:"Bharatpur",state:"Rajasthan",region:"Rajasthan",aliases:["Bharatpur"],nearby:["Alwar","Mathura","Palwal","Jaipur"],corridor:"Bharatpur–Alwar–Palwal belt",marketNote:"Bharatpur is covered for used-car buyer and seller enquiries across the Rajasthan–Haryana edge market."}
];

export function getMarketLocation(slug:string){return marketLocations.find(x=>x.slug===slug)}
export function buyPath(x:MarketLocation){return x.legacyBuyPath||`/used-cars/${x.slug}`}
export function sellPath(x:MarketLocation){return x.legacySellPath||`/sell-car/${x.slug}`}
