-- Secure private photo intake for individual seller submissions.
-- Public visitors may upload only to exact object paths predeclared on a recent
-- Sell/List lead. Objects are never publicly readable.

alter table public.leads
  add column if not exists public_reference text,
  add column if not exists submission_token uuid,
  add column if not exists private_media_paths text[] not null default '{}'::text[];

comment on column public.leads.public_reference is
  'Customer-facing request reference generated by the application.';
comment on column public.leads.submission_token is
  'Random token binding an anonymous seller submission to its private media folder.';
comment on column public.leads.private_media_paths is
  'Private storage object paths associated with this lead. Never expose directly to public users.';

create index if not exists idx_leads_submission_token
  on public.leads(submission_token)
  where submission_token is not null;

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values (
  'seller-submission-photos',
  'seller-submission-photos',
  false,
  8388608,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif']::text[]
)
on conflict (id) do update
set public=false,
    file_size_limit=excluded.file_size_limit,
    allowed_mime_types=excluded.allowed_mime_types;

create or replace function public.can_upload_seller_submission_object(object_name text)
returns boolean
language sql
security definer
stable
set search_path = public, storage, pg_temp
as $$
  select exists (
    select 1
    from public.leads l
    where l.submission_token is not null
      and l.submission_token::text = split_part(object_name,'/',1)
      and l.source = 'customer_sell_page'
      and l.enquiry_type = 'sell_vehicle'
      and l.created_at >= now() - interval '2 hours'
      and object_name = any(l.private_media_paths)
  );
$$;

revoke all on function public.can_upload_seller_submission_object(text) from public;
grant execute on function public.can_upload_seller_submission_object(text) to anon, authenticated;

drop policy if exists "seller_upload_predeclared_private_photos" on storage.objects;
create policy "seller_upload_predeclared_private_photos"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id='seller-submission-photos'
  and public.can_upload_seller_submission_object(name)
);

drop policy if exists "admin_manage_seller_submission_photos" on storage.objects;
create policy "admin_manage_seller_submission_photos"
on storage.objects
for all
to authenticated
using (
  bucket_id='seller-submission-photos'
  and (select public.is_admin())
)
with check (
  bucket_id='seller-submission-photos'
  and (select public.is_admin())
);
