"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../supabaseClient";

type Car={id:string;brand:string;model:string;variant?:string;year?:number;status:string;asking_price?:number;city?:string};
type PrivateRow={id:string;purchase_price?:number|null;purchase_date?:string|null;refurbishment_cost?:number|null;transport_cost?:number|null;other_cost?:number|null;sale_price?:number|null;sale_date?:string|null;buyer_private?:any;seller_private?:any;rc_status?:string|null;rc_transfer_date?:string|null;internal_notes?:string|null;total_cost?:number|null;margin?:number|null};
const money=(n:any)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
const blank=(car:Car)=>({id:car.id,purchase_price:"",purchase_date:"",refurbishment_cost:"0",transport_cost:"0",other_cost:"0",sale_price:"",sale_date:"",seller_name:"",seller_phone:"",buyer_name:"",buyer_phone:"",rc_status:"pending",rc_transfer_date:"",internal_notes:"",vehicle_status:car.status});

export default function FinanceRC(){
 const db=supabase();
 const [ready,setReady]=useState(false);const [cars,setCars]=useState<Car[]>([]);const [rows,setRows]=useState<Record<string,PrivateRow>>({});const [editing,setEditing]=useState<any>(null);const [msg,setMsg]=useState("");const [filter,setFilter]=useState("all");
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Admin login required.");return}const {data:aal}=await db.auth.mfa.getAuthenticatorAssuranceLevel();const {data:isAdmin}=await db.rpc("is_admin");if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Open the Admin Control Room and complete Authenticator verification first.");return}setReady(true);await load()})()},[]);
 async function load(){const [a,b]=await Promise.all([db.from("vehicles").select("id,brand,model,variant,year,status,asking_price,city").order("created_at",{ascending:false}),db.from("vehicle_private").select("*")]);if(a.error){setMsg(a.error.message);return}if(b.error){setMsg(b.error.message);return}setCars((a.data||[]) as Car[]);const map:Record<string,PrivateRow>={};(b.data||[]).forEach((x:any)=>map[x.id]=x);setRows(map)}
 function open(car:Car){const r=rows[car.id];setEditing(r?{...blank(car),...r,seller_name:r.seller_private?.name||"",seller_phone:r.seller_private?.phone||"",buyer_name:r.buyer_private?.name||"",buyer_phone:r.buyer_private?.phone||"",vehicle_status:car.status}:blank(car));setMsg("")}
 function calc(x:any){const total=Number(x.purchase_price||0)+Number(x.refurbishment_cost||0)+Number(x.transport_cost||0)+Number(x.other_cost||0);const margin=Number(x.sale_price||0)-total;return {total,margin}}
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setMsg("Saving deal ledger…");const payload={id:editing.id,purchase_price:editing.purchase_price===""?null:Number(editing.purchase_price),purchase_date:editing.purchase_date||null,refurbishment_cost:Number(editing.refurbishment_cost||0),transport_cost:Number(editing.transport_cost||0),other_cost:Number(editing.other_cost||0),sale_price:editing.sale_price===""?null:Number(editing.sale_price),sale_date:editing.sale_date||null,seller_private:{name:editing.seller_name||null,phone:editing.seller_phone||null},buyer_private:{name:editing.buyer_name||null,phone:editing.buyer_phone||null},rc_status:editing.rc_status||"pending",rc_transfer_date:editing.rc_transfer_date||null,internal_notes:editing.internal_notes||null,updated_at:new Date().toISOString()};const {error}=await db.from("vehicle_private").upsert(payload,{onConflict:"id"});if(error){setMsg(error.message);return}const carUpdate=await db.from("vehicles").update({status:editing.vehicle_status}).eq("id",editing.id);if(carUpdate.error){setMsg(carUpdate.error.message);return}const {total,margin}=calc(editing);await db.from("vehicle_events").insert({vehicle_id:editing.id,event_type:"deal_ledger_updated",event_data:{purchase_price:payload.purchase_price,total_cost:total,sale_price:payload.sale_price,margin,rc_status:payload.rc_status,vehicle_status:editing.vehicle_status}});setMsg("Purchase / Sale / Margin / RC saved ✓");setEditing(null);await load()}
 const joined=useMemo(()=>cars.map(c=>({car:c,p:rows[c.id]})),[cars,rows]);
 const visible=joined.filter(x=>filter==="all"?true:filter==="rc"?!["transferred","completed"].includes(String(x.p?.rc_status||"pending").toLowerCase()):x.car.status===filter);
 const totals=useMemo(()=>joined.reduce((a,x)=>{const p=x.p;a.stock+=x.car.status!=="sold"?Number(p?.total_cost||0):0;a.sales+=Number(p?.sale_price||0);a.margin+=p?.sale_price?Number(p?.margin||0):0;if(!["transferred","completed"].includes(String(p?.rc_status||"pending").toLowerCase()))a.rc++;return a},{stock:0,sales:0,margin:0,rc:0}),[joined]);
 if(!ready)return <main><section className="section"><h1>Finance & RC Control</h1><p>{msg||"Checking Admin security…"}</p><a href="/admin">Back to Admin</a></section></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE</b><small>Purchase • Sale • Margin • RC</small></div><div className="row"><a className="call" href="/admin">Control Room</a><a className="call" href="/admin/poster-scan">Smart Poster Scan</a></div></header>
 <section className="section"><h1>Deal Ledger & RC Tracking</h1><p>Private owner-only financial control. Nothing here is shown on the public vehicle page.</p><div className="grid"><article className="application"><b>Stock Cost</b><h2>{money(totals.stock)}</h2><small>landed cost of non-sold vehicles</small></article><article className="application"><b>Recorded Sales</b><h2>{money(totals.sales)}</h2><small>sale values entered</small></article><article className="application"><b>Gross Margin</b><h2>{money(totals.margin)}</h2><small>sale − purchase − refurbishment − transport − other</small></article><article className="application"><b>RC Pending</b><h2>{totals.rc}</h2><small>vehicles not marked transferred/completed</small></article></div><div className="row" style={{marginTop:16}}><button onClick={()=>setFilter("all")}>All</button><button onClick={()=>setFilter("published")}>In Stock</button><button onClick={()=>setFilter("sold")}>Sold</button><button onClick={()=>setFilter("rc")}>RC Pending</button><button onClick={load}>Refresh</button></div>{msg&&<p>{msg}</p>}</section>
 <section className="section"><h2>Vehicles ({visible.length})</h2>{visible.length===0?<p>No matching vehicles.</p>:<div className="grid">{visible.map(({car,p})=><article className="card" key={car.id}><div className="body"><h3>{car.brand} {car.model} {car.variant||""}</h3><p>{car.year||""} • {car.city||""} • {car.status}</p><p>Purchase: <b>{money(p?.purchase_price)}</b><br/>Total Cost: <b>{money(p?.total_cost)}</b><br/>Sale: <b>{money(p?.sale_price)}</b><br/>Margin: <b>{money(p?.sale_price?p?.margin:0)}</b></p><small>RC: {p?.rc_status||"pending"}{p?.rc_transfer_date?` • ${p.rc_transfer_date}`:""}</small><div className="row"><button onClick={()=>open(car)}>{p?"Edit Ledger":"Add Purchase / Sale"}</button></div></div></article>)}</div>}</section>
 {editing&&<div className="overlay"><div className="modal"><button className="x" onClick={()=>setEditing(null)}>×</button><h2>Deal Ledger</h2><form className="adminForm" onSubmit={save}><h3>Purchase</h3><input type="number" placeholder="Purchase Price ₹" value={editing.purchase_price??""} onChange={e=>setEditing({...editing,purchase_price:e.target.value})}/><input type="date" value={editing.purchase_date||""} onChange={e=>setEditing({...editing,purchase_date:e.target.value})}/><input type="number" placeholder="Refurbishment ₹" value={editing.refurbishment_cost??0} onChange={e=>setEditing({...editing,refurbishment_cost:e.target.value})}/><input type="number" placeholder="Transport ₹" value={editing.transport_cost??0} onChange={e=>setEditing({...editing,transport_cost:e.target.value})}/><input type="number" placeholder="Other Cost ₹" value={editing.other_cost??0} onChange={e=>setEditing({...editing,other_cost:e.target.value})}/><input placeholder="Seller Name" value={editing.seller_name||""} onChange={e=>setEditing({...editing,seller_name:e.target.value})}/><input placeholder="Seller Phone" value={editing.seller_phone||""} onChange={e=>setEditing({...editing,seller_phone:e.target.value})}/><h3>Sale</h3><input type="number" placeholder="Sale Price ₹" value={editing.sale_price??""} onChange={e=>setEditing({...editing,sale_price:e.target.value})}/><input type="date" value={editing.sale_date||""} onChange={e=>setEditing({...editing,sale_date:e.target.value})}/><input placeholder="Buyer Name" value={editing.buyer_name||""} onChange={e=>setEditing({...editing,buyer_name:e.target.value})}/><input placeholder="Buyer Phone" value={editing.buyer_phone||""} onChange={e=>setEditing({...editing,buyer_phone:e.target.value})}/><h3>RC & Status</h3><select value={editing.rc_status||"pending"} onChange={e=>setEditing({...editing,rc_status:e.target.value})}><option value="pending">RC Pending</option><option value="documents_pending">Documents Pending</option><option value="submitted">Submitted</option><option value="in_process">In Process</option><option value="transferred">Transferred</option><option value="completed">Completed</option></select><input type="date" value={editing.rc_transfer_date||""} onChange={e=>setEditing({...editing,rc_transfer_date:e.target.value})}/><select value={editing.vehicle_status||"published"} onChange={e=>setEditing({...editing,vehicle_status:e.target.value})}><option value="draft">Draft</option><option value="published">Published / In Stock</option><option value="sold">Sold</option><option value="archived">Archived</option></select><textarea placeholder="Internal notes (private)" value={editing.internal_notes||""} onChange={e=>setEditing({...editing,internal_notes:e.target.value})}/><div className="application"><b>Live calculation</b><p>Total Cost: {money(calc(editing).total)}<br/>Margin: {money(calc(editing).margin)}</p></div><button>Save Ledger</button></form></div></div>}
 </main>
}
