import CustomerBackBar from "../components/CustomerBackBar";

export const metadata={title:"Rohilla Business Hub",description:"Join the Rohilla Drive automotive business network as an OEM/authorised new vehicle dealer, pre-owned dealer, workshop, inspector, finance/insurance professional, mobility operator, recycler or other automotive business.",alternates:{canonical:"/business-hub"},openGraph:{url:"/business-hub",title:"Rohilla Business Hub | ROHILLA DRIVE",description:"OEM/new-vehicle dealership, pre-owned, service, mobility and automotive business network."}};

type BusinessType={name:string;desc:string;register:string;login:string;portal:string};
const businessTypes:BusinessType[]=[
 {name:"OEM / Authorised New Vehicle Dealer",desc:"OEM dealership, authorised showroom or sales team: receive structured new-vehicle demand, quote/test-drive opportunities and multi-brand customer routing.",register:"/dealer?mode=signup&type=oem",login:"/dealer?mode=login&type=oem",portal:"Dealer / OEM Portal"},
 {name:"Pre-Owned / Used Vehicle Dealer",desc:"Regular inventory, dealer submissions, sourcing, finance/margin/RC tools and Rohilla Intelligence growth workflows.",register:"/dealer?mode=signup&type=preowned",login:"/dealer?mode=login&type=preowned",portal:"Dealer Portal"},
 {name:"Workshop / Repairs / Detailing",desc:"Receive assigned jobs, manage work status and build a verified service profile.",register:"/partner?mode=signup&category=Workshop%20%2F%20Repairs",login:"/partner?mode=login",portal:"Service Provider Portal"},
 {name:"Inspection / Verification",desc:"Vehicle inspection and verification assignments through the Rohilla network.",register:"/partner?mode=signup&category=Car%20Inspection",login:"/partner?mode=login",portal:"Inspection Partner Portal"},
 {name:"Finance / Insurance / RC-RTO",desc:"Qualified customer requirements with controlled handoff and workflow tracking.",register:"/partner?mode=signup&category=Finance%20DSA",login:"/partner?mode=login",portal:"Business Partner Portal"},
 {name:"Taxi / Self-Drive / Chauffeur / Fleet",desc:"Mobility and corporate/fleet requirements routed through one business network.",register:"/partner?mode=signup&category=Fleet%20%2F%20Corporate%20Mobility",login:"/partner?mode=login",portal:"Mobility Partner Portal"},
 {name:"Commercial / Transport / Logistics",desc:"Commercial vehicle, delivery, fleet and transporter opportunities.",register:"/partner?mode=signup&category=Vehicle%20Delivery%20%2F%20Logistics",login:"/partner?mode=login",portal:"Logistics Partner Portal"},
 {name:"EV / Tyres / Battery / RSA",desc:"Future mobility, roadside and vehicle-support services.",register:"/partner?mode=signup&category=EV%20Services",login:"/partner?mode=login",portal:"Service Partner Portal"},
 {name:"RVSF / Recycler / Scrap Buyer",desc:"Responsible end-of-life vehicle and recycler quote opportunities.",register:"/partner?mode=signup&category=Registered%20Vehicle%20Scrapping%20Facility%20%28RVSF%29",login:"/partner?mode=login",portal:"Recycler / RVSF Portal"},
 {name:"Multilingual / Cross-State Business",desc:"Serve customers across language and state boundaries using Rohilla Language Bridge and translated communication tools.",register:"/partner?mode=signup",login:"/partner?mode=login",portal:"Business Hub Partner Portal"},
 {name:"Other Automotive Business",desc:"If your business touches the vehicle lifecycle, apply and let Rohilla Drive classify the right workflow.",register:"/partner?mode=signup&category=Other%20Automobile%20Service",login:"/partner?mode=login",portal:"Business Hub Partner Portal"}
];

export default function BusinessHub(){return <main>
 <CustomerBackBar/>
 <header><div className="brand"><b>ROHILLA DRIVE</b><small>ROHILLA BUSINESS HUB</small></div><div className="row"><a className="call" href="/new-vehicles">New Vehicle Assistance</a><a className="call" href="/language-assist">Language Bridge</a></div></header>
 <section className="hero"><div className="heroText"><span>B2B AUTOMOTIVE NETWORK</span><h1>Do business with Rohilla Drive — not just list on it.</h1><p>OEM/authorised new vehicle dealer, pre-owned dealer, workshop, inspector, finance/insurance professional, mobility operator, transporter, RVSF or another automotive business: choose your role and register directly from this page.</p><p><b>One network. Every vehicle. Every language.</b></p><div className="row"><a className="call" href="/dealer?mode=signup&type=oem">Create OEM / Dealer Account</a><a className="call" href="/partner?mode=signup">Create Service / Partner Account</a></div></div></section>
 <section className="section"><div className="grid">{businessTypes.map(item=><article className="application" key={item.name}><h2>{item.name}</h2><p>{item.desc}</p><div className="row"><a className="call" href={item.register}>Create Account / Register</a><a className="call" href={item.login}>Login</a></div><small>{item.portal}</small></article>)}</div></section>
 <section className="section dark"><div className="about"><h2>No link-request step.</h2><p>Businesses can open the correct registration or login flow directly from Rohilla Business Hub. OEM/new-vehicle and pre-owned businesses enter the Dealer/OEM portal; workshops, inspection, finance, mobility, logistics, RVSF and other service businesses enter the Business Hub Partner portal.</p><p>Customer contact and private business data remain permission-controlled inside Rohilla Drive.</p></div></section>
 </main>}
