import CustomerBackBar from "../components/CustomerBackBar";

export const metadata={title:"Rohilla Business Hub",description:"Join the ROHILLA DRIVE business network for OEM/authorised dealers, pre-owned dealers, workshops, mobility, inspection and automotive services.",alternates:{canonical:"/business-hub"},openGraph:{url:"/business-hub",title:"Rohilla Business Hub | ROHILLA DRIVE",description:"OEM/new-vehicle dealership, pre-owned, service, mobility and automotive business network."}};

type BusinessType={name:string;desc:string;register:string;login:string;portal:string};
const partner=(category:string)=>`/join/partner?category=${encodeURIComponent(category)}`;
const businessTypes:BusinessType[]=[
 {name:"OEM / Authorised New Vehicle Dealer",desc:"OEM dealership, authorised showroom or official sales team: apply for eligible new-vehicle enquiry routing, quote/test-drive coordination and multi-brand customer workflows. Platform approval is not OEM certification.",register:"/join/oem",login:"/dealer",portal:"Dealer / OEM Portal"},
 {name:"Pre-Owned / Used Vehicle Dealer",desc:"Inventory submissions, sourcing workflows, finance/margin/RC tracking and Rohilla Drive growth tools, subject to Admin approval and platform permissions.",register:"/join/preowned",login:"/dealer",portal:"Dealer Portal"},
 {name:"Workshop / Repairs / Detailing",desc:"Apply to receive relevant assigned jobs and manage work status. Rohilla Drive approval is a platform-access decision, not a professional or government certification.",register:partner("Workshop / Repairs"),login:"/partner",portal:"Service Provider Portal"},
 {name:"Inspection / Verification",desc:"Apply for eligible inspection or verification assignments. Partners remain responsible for competence, truthful reporting and any required authorisation.",register:partner("Car Inspection"),login:"/partner",portal:"Inspection Partner Portal"},
 {name:"Finance / Insurance / RC-RTO",desc:"Customer requirements may be routed only to appropriately authorised or licensed providers where required. Provider eligibility, advice, approval and compliance remain with that provider.",register:partner("Finance DSA"),login:"/partner",portal:"Business Partner Portal"},
 {name:"Taxi / Self-Drive / Chauffeur / Fleet",desc:"Apply for eligible mobility and corporate/fleet requirements. Operators remain responsible for permits, licences, insurance and applicable transport rules.",register:partner("Fleet / Corporate Mobility"),login:"/partner",portal:"Mobility Partner Portal"},
 {name:"Commercial / Transport / Logistics",desc:"Apply for commercial vehicle, delivery, fleet and transporter workflows subject to service-area availability and required permits or registrations.",register:partner("Vehicle Delivery / Logistics"),login:"/partner",portal:"Logistics Partner Portal"},
 {name:"EV / Tyres / Battery / RSA",desc:"Apply for relevant EV, roadside and vehicle-support service workflows, subject to capability and service-area review.",register:partner("EV Services"),login:"/partner",portal:"Service Partner Portal"},
 {name:"RVSF / Recycler / Scrap Buyer",desc:"End-of-life vehicle workflows distinguish a registered RVSF from a local recycler or scrap buyer. RVSF status must be supported by the required registration or authorisation.",register:partner("Registered Vehicle Scrapping Facility (RVSF)"),login:"/partner",portal:"Recycler / RVSF Portal"},
 {name:"Multilingual / Cross-State Business",desc:"Use language and cross-state coordination tools for eligible workflows. Local legal, tax, transport and licensing requirements continue to apply.",register:"/join/partner",login:"/partner",portal:"Business Hub Partner Portal"},
 {name:"Other Automotive Business",desc:"If your business touches the vehicle lifecycle, apply and Rohilla Drive can classify the relevant workflow after review.",register:partner("Other Automobile Service"),login:"/partner",portal:"Business Hub Partner Portal"}
];

export default function BusinessHub(){return <main>
 <CustomerBackBar/>
 <header><div className="brand"><b>ROHILLA DRIVE</b><small>ROHILLA BUSINESS HUB</small></div><div className="row"><a className="call" href="/new-vehicles">New Vehicle Assistance</a><a className="call" href="/language-assist">Language Bridge</a></div></header>
 <section className="hero"><div className="heroText"><span>B2B AUTOMOTIVE NETWORK</span><h1>Do business with Rohilla Drive — not just list on it.</h1><p>OEM/authorised new vehicle dealer, pre-owned dealer, workshop, inspector, mobility operator, transporter, RVSF/recycler or another automotive business: choose your role and apply directly. Regulated services such as finance or insurance must be handled only by appropriately authorised or licensed providers.</p><p><b>One network. Every vehicle. Every language.</b></p><div className="row"><a className="call" href="/join/oem">Create OEM / New Vehicle Dealer Account</a><a className="call" href="/join/preowned">Create Pre-Owned Dealer Account</a><a className="call" href="/join/partner">Create Service / Partner Account</a></div></div></section>
 <section className="section"><div className="notice"><b>Important:</b> Rohilla Drive approval provides platform access only. It does not certify an applicant's OEM status, professional qualification, government registration, licence or statutory compliance. Applicants remain responsible for accurate declarations and required permissions.</div><div className="grid">{businessTypes.map(item=><article className="application" key={item.name}><h2>{item.name}</h2><p>{item.desc}</p><div className="row"><a className="call" href={item.register}>Create Account / Register</a><a className="call" href={item.login}>Login</a></div><small>{item.portal}</small></article>)}</div></section>
 <section className="section dark"><div className="about"><h2>Direct registration, followed by review.</h2><p>Businesses can open the relevant registration form or login directly from Rohilla Business Hub. Creating an account does not guarantee approval, enquiries, revenue, leads or assignments.</p><p>Customer contact and private business data remain permission-controlled inside Rohilla Drive.</p></div></section>
 </main>}
