export const metadata={title:"Rohilla Business Hub",description:"Join the Rohilla Drive automotive business network as an OEM/authorised new vehicle dealer, pre-owned dealer, workshop, inspector, finance/insurance professional, mobility operator, recycler or other automotive business.",alternates:{canonical:"/business-hub"},openGraph:{url:"/business-hub",title:"Rohilla Business Hub | ROHILLA DRIVE",description:"OEM/new-vehicle dealership, pre-owned, service, mobility and automotive business network."}};

type BusinessType={name:string;desc:string;register:string;login:string;portal:string};
const partner=(category:string)=>`/join/partner?category=${encodeURIComponent(category)}`;
const businessTypes:BusinessType[]=[
 {name:"OEM / Authorised New Vehicle Dealer",desc:"OEM dealership, authorised showroom or sales team: receive structured new-vehicle demand, quote/test-drive opportunities and multi-brand customer routing.",register:"/join/oem",login:"/dealer",portal:"Dealer / OEM Portal"},
 {name:"Pre-Owned / Used Vehicle Dealer",desc:"Regular inventory, dealer submissions, sourcing, finance/margin/RC tools and Rohilla Intelligence growth workflows.",register:"/join/preowned",login:"/dealer",portal:"Dealer Portal"},
 {name:"Workshop / Repairs / Detailing",desc:"Receive assigned jobs, manage work status and build a verified service profile.",register:partner("Workshop / Repairs"),login:"/partner",portal:"Service Provider Portal"},
 {name:"Inspection / Verification",desc:"Vehicle inspection and verification assignments through the Rohilla network.",register:partner("Car Inspection"),login:"/partner",portal:"Inspection Partner Portal"},
 {name:"Finance / Insurance / RC-RTO",desc:"Qualified customer requirements with controlled handoff and workflow tracking.",register:partner("Finance DSA"),login:"/partner",portal:"Business Partner Portal"},
 {name:"Taxi / Self-Drive / Chauffeur / Fleet",desc:"Mobility and corporate/fleet requirements routed through one business network.",register:partner("Fleet / Corporate Mobility"),login:"/partner",portal:"Mobility Partner Portal"},
 {name:"Commercial / Transport / Logistics",desc:"Commercial vehicle, delivery, fleet and transporter opportunities.",register:partner("Vehicle Delivery / Logistics"),login:"/partner",portal:"Logistics Partner Portal"},
 {name:"EV / Tyres / Battery / RSA",desc:"Future mobility, roadside and vehicle-support services.",register:partner("EV Services"),login:"/partner",portal:"Service Partner Portal"},
 {name:"RVSF / Recycler / Scrap Buyer",desc:"Responsible end-of-life vehicle and recycler quote opportunities.",register:partner("Registered Vehicle Scrapping Facility (RVSF)"),login:"/partner",portal:"Recycler / RVSF Portal"},
 {name:"Other Automotive Business",desc:"If your business touches the vehicle lifecycle, apply and let Rohilla Drive classify the right workflow.",register:partner("Other Automobile Service"),login:"/partner",portal:"Business Hub Partner Portal"}
];

export default function BusinessHub(){return <main>
 <header><div className="brand"><b>ROHILLA DRIVE</b><small>ROHILLA BUSINESS HUB</small></div><div className="row"><a className="call" href="/">Customer Website</a><a className="call" href="/new-vehicles">New Vehicle Assistance</a></div></header>
 <section className="hero"><div className="heroText"><span>B2B AUTOMOTIVE NETWORK</span><h1>Do business with Rohilla Drive — not just list on it.</h1><p>Choose what kind of automotive business you run. Registration and login are available directly here — no separate link request is needed.</p><div className="row"><a className="call" href="/join/oem">Create OEM / New Vehicle Dealer Account</a><a className="call" href="/join/preowned">Create Pre-Owned Dealer Account</a><a className="call" href="/join/partner">Create Service / Partner Account</a></div></div></section>
 <section className="section"><div className="grid">{businessTypes.map(item=><article className="application" key={item.name}><h2>{item.name}</h2><p>{item.desc}</p><div className="row"><a className="call" href={item.register}>Create Account / Register</a><a className="call" href={item.login}>User Login</a></div><small>{item.portal}</small></article>)}</div></section>
 <section className="section dark"><div className="about"><h2>Register or login from this page.</h2><p>OEM/new-vehicle dealers, pre-owned dealers and service/mobility businesses can open the exact registration form directly from Rohilla Business Hub. Existing approved users can login from the same card.</p><p>Customer contact and private business data remain permission-controlled inside Rohilla Drive.</p></div></section>
 </main>}
