create extension if not exists pgcrypto;
create table if not exists profiles(id uuid primary key references auth.users(id) on delete cascade,role text not null check(role in ('owner','admin','manager','sales','inspector','dealer','partner')),name text,phone text,active boolean default true,created_at timestamptz default now());
create table if not exists vehicles(id uuid primary key default gen_random_uuid(),partner_id uuid references profiles(id),brand text not null,model text not null,variant text,year int,km int,fuel text,owner_count int,asking_price numeric,city text,public_notes text,status text not null default 'draft' check(status in ('draft','published','sold','archived')),created_at timestamptz default now());
create table if not exists vehicle_photos(id uuid primary key default gen_random_uuid(),vehicle_id uuid references vehicles(id) on delete cascade,url text not null,path text,sort_order int default 0,created_at timestamptz default now());
create table if not exists leads(id uuid primary key default gen_random_uuid(),vehicle_id uuid references vehicles(id),partner_id uuid references profiles(id),customer_name text,customer_phone text,requirement text,message text,status text default 'new',source text,created_at timestamptz default now(),outcome text);
create table if not exists collaboration_requests(id uuid primary key default gen_random_uuid(),business_name text,contact text,category text,city text,message text,status text default 'new',created_at timestamptz default now());
create table if not exists dealer_applications(id uuid primary key default gen_random_uuid(),business_name text,contact_name text,mobile text,city text,address text,inventory_count int,services text,message text,status text default 'new',created_at timestamptz default now());
create table if not exists social_posts(id uuid primary key default gen_random_uuid(),vehicle_id uuid references vehicles(id) on delete cascade,platform text not null check(platform in ('instagram','facebook','youtube')),caption text,media_urls jsonb default '[]'::jsonb,status text default 'queued' check(status in ('queued','published','failed')),published_at timestamptz,error text,created_at timestamptz default now());

alter table profiles enable row level security; alter table vehicles enable row level security; alter table vehicle_photos enable row level security; alter table leads enable row level security; alter table collaboration_requests enable row level security; alter table dealer_applications enable row level security; alter table social_posts enable row level security;

drop policy if exists "public published vehicles" on vehicles; create policy "public published vehicles" on vehicles for select using(status='published');
drop policy if exists "public photos of published vehicles" on vehicle_photos; create policy "public photos of published vehicles" on vehicle_photos for select using(exists(select 1 from vehicles v where v.id=vehicle_id and v.status='published'));
drop policy if exists "admins manage vehicles" on vehicles; create policy "admins manage vehicles" on vehicles for all using(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager'))) with check(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager')));
drop policy if exists "admins manage photos" on vehicle_photos; create policy "admins manage photos" on vehicle_photos for all using(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager'))) with check(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager')));
drop policy if exists "dealer own vehicles" on vehicles; create policy "dealer own vehicles" on vehicles for select using(partner_id=auth.uid());
drop policy if exists "dealer insert own vehicles" on vehicles; create policy "dealer insert own vehicles" on vehicles for insert with check(partner_id=auth.uid() and status='draft');
drop policy if exists "dealer update own vehicles" on vehicles; create policy "dealer update own vehicles" on vehicles for update using(partner_id=auth.uid()) with check(partner_id=auth.uid() and status='draft');
drop policy if exists "dealer own photos" on vehicle_photos; create policy "dealer own photos" on vehicle_photos for select using(exists(select 1 from vehicles v where v.id=vehicle_id and v.partner_id=auth.uid()));
drop policy if exists "dealer upload photos" on vehicle_photos; create policy "dealer upload photos" on vehicle_photos for insert with check(exists(select 1 from vehicles v where v.id=vehicle_id and v.partner_id=auth.uid()));
drop policy if exists "admins read leads" on leads; create policy "admins read leads" on leads for select using(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager','sales')));
drop policy if exists "public create leads" on leads; create policy "public create leads" on leads for insert with check(true);
drop policy if exists "admins manage collaboration" on collaboration_requests; create policy "admins manage collaboration" on collaboration_requests for all using(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager'))) with check(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager')));
drop policy if exists "public create collaboration" on collaboration_requests; create policy "public create collaboration" on collaboration_requests for insert with check(true);
drop policy if exists "public create dealer application" on dealer_applications; create policy "public create dealer application" on dealer_applications for insert with check(true);
drop policy if exists "admins manage dealer applications" on dealer_applications; create policy "admins manage dealer applications" on dealer_applications for all using(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager'))) with check(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager')));
drop policy if exists "admins manage social posts" on social_posts; create policy "admins manage social posts" on social_posts for all using(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager'))) with check(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager')));


create table if not exists vehicle_private(id uuid primary key references vehicles(id) on delete cascade,purchase_price numeric,purchase_date date,refurbishment_cost numeric default 0,transport_cost numeric default 0,other_cost numeric default 0,sale_price numeric,buyer_private jsonb,seller_private jsonb,rc_status text,rc_transfer_date date,internal_notes text,updated_at timestamptz default now());
create table if not exists vehicle_events(id uuid primary key default gen_random_uuid(),vehicle_id uuid references vehicles(id) on delete cascade,event_type text not null,event_data jsonb default '{}'::jsonb,actor_id uuid references auth.users(id),created_at timestamptz default now());
create table if not exists service_requests(id uuid primary key default gen_random_uuid(),vehicle_id uuid references vehicles(id),customer_name text not null,customer_phone text not null,category text not null,vehicle_location text,customer_location text,details text,photo_urls jsonb default '[]'::jsonb,preferred_time text,status text default 'new',assigned_partner_id uuid references profiles(id),created_at timestamptz default now(),updated_at timestamptz default now());

alter table vehicle_private enable row level security; alter table vehicle_events enable row level security; alter table service_requests enable row level security;
drop policy if exists "admins manage private vehicle data" on vehicle_private; create policy "admins manage private vehicle data" on vehicle_private for all using(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager'))) with check(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager')));
drop policy if exists "admins read vehicle events" on vehicle_events; create policy "admins read vehicle events" on vehicle_events for select using(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager','sales','inspector')));
drop policy if exists "admins create vehicle events" on vehicle_events; create policy "admins create vehicle events" on vehicle_events for insert with check(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager','sales','inspector','dealer','partner')));
drop policy if exists "public create service requests" on service_requests; create policy "public create service requests" on service_requests for insert with check(true);
drop policy if exists "admins manage service requests" on service_requests; create policy "admins manage service requests" on service_requests for all using(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager','sales'))) with check(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager','sales')));
drop policy if exists "partners read assigned service requests" on service_requests; create policy "partners read assigned service requests" on service_requests for select using(assigned_partner_id=auth.uid());
drop policy if exists "partners update assigned service requests" on service_requests; create policy "partners update assigned service requests" on service_requests for update using(assigned_partner_id=auth.uid()) with check(assigned_partner_id=auth.uid());

insert into storage.buckets(id,name,public) values('vehicle-photos','vehicle-photos',true) on conflict(id) do nothing;
drop policy if exists "public read vehicle photos" on storage.objects; create policy "public read vehicle photos" on storage.objects for select using(bucket_id='vehicle-photos');
drop policy if exists "admins upload vehicle photos" on storage.objects; create policy "admins upload vehicle photos" on storage.objects for insert with check(bucket_id='vehicle-photos' and exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager')));
drop policy if exists "dealer upload vehicle photos" on storage.objects; create policy "dealer upload vehicle photos" on storage.objects for insert with check(bucket_id='vehicle-photos' and exists(select 1 from profiles p where p.id=auth.uid() and p.role='dealer') and exists(select 1 from vehicles v where v.id::text=split_part(name,'/',1) and v.partner_id=auth.uid() and v.status='draft'));
drop policy if exists "admins update vehicle photos" on storage.objects; create policy "admins update vehicle photos" on storage.objects for update using(bucket_id='vehicle-photos' and exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager')));
drop policy if exists "admins delete vehicle photos" on storage.objects; create policy "admins delete vehicle photos" on storage.objects for delete using(bucket_id='vehicle-photos' and exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('owner','admin','manager')));
