"use client";
import {useEffect,useRef,useState} from 'react'; import {supabase} from '../supabaseClient';
export default function Admin(){const db=supabase();const [session,setSession]=useState<any>(null);const [accessDenied,setAccessDenied]=useState(false);const [cars,setCars]=useState<any[]>([]);const [apps,setApps]=useState<any[]>([]);const [partnerApps,setPartnerApps]=useState<any[]>([]);const [partners,setPartners]=useState<any[]>([]);const [requests,setRequests]=useState<any[]>([]);const [salesLeads,setSalesLeads]=useState<any[]>([]);const [msg,setMsg]=useState('');const [files,setFiles]=useState<File[]>([]);const [f,setF]=useState<any>({});const [editing,setEditing]=useState<any>(null);const [editFiles,setEditFiles]=useState<File[]>([]);const [mfaMode,setMfaMode]=useState<'none'|'setup'|'challenge'>('none');const [mfaFactor,setMfaFactor]=useState<any>(null);const [mfaData,setMfaData]=useState<any>(null);const [mfaCode,setMfaCode]=useState('');const [mfaBusy,setMfaBusy]=useState(false);const [quickText,setQuickText]=useState('');const [soldVehicleId,setSoldVehicleId]=useState('');const [publishing,setPublishing]=useState(false);const [publishProgress,setPublishProgress]=useState({stage:'Ready',done:0,total:0,percent:0});const [duplicateWarning,setDuplicateWarning]=useState<any>(null);const [allowDuplicateOnce,setAllowDuplicateOnce]=useState(false);const publishLock=useRef(false);const submissionId=useRef('');
useEffect(()=>{db.auth.getSession().then(async({data})=>{if(data.session){setSession(data.session);await ensureMfa(data.session)}})},[]);
async function load(){const [a,b,c,d,e,g]=await Promise.all([db.from('vehicles').select('*,vehicle_photos(id,url,path,sort_order)').order('created_at',{ascending:false}),db.from('dealer_applications').select('*').order('created_at',{ascending:false}),db.from('collaboration_requests').select('*').order('created_at',{ascending:false}),db.from('profiles').select('id,name,phone,business_name,service_categories,city,active').eq('role','partner').order('created_at',{ascending:false}),db.from('service_requests').select('id,customer_name,customer_phone,category,customer_location,vehicle_location,details,preferred_time,status,assigned_partner_id,created_at,vehicle:vehicles(brand,model,variant,year)').order('created_at',{ascending:false}),db.from('leads').select('id,vehicle_id,customer_name,customer_phone,requirement,message,status,source,enquiry_type,new_or_used,created_at').order('created_at',{ascending:false})]);setCars(a.data||[]);setApps(b.data||[]);setPartnerApps(c.data||[]);setPartners(d.data||[]);setRequests((e.data||[]).map((x:any)=>({...x,vehicle:Array.isArray(x.vehicle)?x.vehicle[0]||null:x.vehicle})));setSalesLeads(g.data||[]);}
async function ensureMfa(sess:any){setMsg('Checking administrator security…');const {data:profile,error:profileErr}=await db.from('profiles').select('role,active').eq('id',sess.user.id).single();if(profileErr||!profile||!profile.active||!['owner','admin'].includes(profile.role)){setAccessDenied(true);setMsg('This account does not have administrator access.');return}setAccessDenied(false);const {data:aal,error:aalErr}=await db.auth.mfa.getAuthenticatorAssuranceLevel();if(aalErr){setMsg(aalErr.message);return}const {data:fac,error:facErr}=await db.auth.mfa.listFactors();if(facErr){setMsg(facErr.message);return}const verified=(fac?.totp||[]).find((x:any)=>x.status==='verified');if(!verified){const {data,error}=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'ROHILLA DRIVE Administrator'});if(error){setMsg(error.message);return}setMfaData(data);setMfaMode('setup');setMsg('Scan the QR code with your authenticator app, then enter the 6-digit verification code.');return}setMfaFactor(verified);if(aal?.currentLevel==='aal2'){const {data:isAdmin,error:adminErr}=await db.rpc('is_admin');if(adminErr||!isAdmin){setAccessDenied(true);setMsg('This account is not authorised for the Administration Console.');return}setMfaMode('none');setMsg('');load();return}setMfaMode('challenge');setMsg('Enter your 6-digit authenticator code.');}
async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const x=new FormData(e.currentTarget);setMsg('Signing in…');const {data,error}=await db.auth.signInWithPassword({email:String(x.get('email')),password:String(x.get('password'))});if(error){setMsg(error.message);return}setSession(data.session);await ensureMfa(data.session)}
async function verifySetup(){if(!mfaData?.id||mfaCode.length!==6)return;setMfaBusy(true);const {error}=await db.auth.mfa.challengeAndVerify({factorId:mfaData.id,code:mfaCode});setMfaBusy(false);if(error){setMsg(error.message);return}setMfaMode('none');setMfaData(null);setMfaCode('');setMsg('Authenticator enabled.');await ensureMfa(session)}
async function verifyChallenge(){if(!mfaFactor?.id||mfaCode.length!==6)return;setMfaBusy(true);const {error}=await db.auth.mfa.challengeAndVerify({factorId:mfaFactor.id,code:mfaCode});setMfaBusy(false);if(error){setMsg(error.message);return}setMfaMode('none');setMfaCode('');setMsg('Administrator verified.');await ensureMfa(session)}
async function uploadPhotos(vehicleId:string, chosen:File[]){
 const rows:any[]=[];let completed=0;const batchSize=4;
 for(let i=0;i<chosen.length;i+=batchSize){
  const batch=chosen.slice(i,i+batchSize);
  const uploaded=await Promise.all(batch.map(async(file,batchIndex)=>{
   const n=i+batchIndex;const path=`${vehicleId}/${Date.now()}-${n}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'')}`;
   const up=await db.storage.from('vehicle-photos').upload(path,file,{upsert:false});if(up.error)throw new Error(up.error.message);
   const pub=db.storage.from('vehicle-photos').getPublicUrl(path).data.publicUrl;
   completed++;setPublishProgress({stage:`Uploading photos ${completed}/${chosen.length}`,done:completed,total:chosen.length,percent:20+Math.round((completed/Math.max(chosen.length,1))*65)});
   return {vehicle_id:vehicleId,url:pub,sort_order:n,path};
  }));
  rows.push(...uploaded);
  const {error}=await db.from('vehicle_photos').insert(uploaded);if(error)throw new Error(error.message);
 }
 return rows.map(row=>row.url);
}
async function findDuplicateVehicle(){
 const {data,error}=await db.from('vehicles').select('id,brand,model,variant,year,km,fuel,owner_count,asking_price,city,status,created_at')
  .ilike('brand',String(f.brand||'').trim()).ilike('model',String(f.model||'').trim()).eq('year',Number(f.year)).eq('km',Number(f.km))
  .eq('fuel',String(f.fuel||'')).eq('owner_count',Number(f.owner_count)).eq('asking_price',Number(f.price)).in('status',['published','draft','sold'])
  .order('created_at',{ascending:false}).limit(10);
 if(error)throw new Error(error.message);
 const norm=(v:any)=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ');
 return (data||[]).find((v:any)=>norm(v.variant)===norm(f.variant)&&norm(v.city)===norm(f.city))||null;
}
function parseVehicleText(input:string){
 const clean=input.replace(/\r/g,' ').replace(/[•|]+/g,' ').replace(/\s+/g,' ').trim();const lower=clean.toLowerCase();
 const modelBrands:Record<string,string>={'grand vitara':'Maruti Suzuki','wagon r':'Maruti Suzuki','wagonr':'Maruti Suzuki','brezza':'Maruti Suzuki','baleno':'Maruti Suzuki','swift':'Maruti Suzuki','alto':'Maruti Suzuki','celerio':'Maruti Suzuki','dzire':'Maruti Suzuki','ertiga':'Maruti Suzuki','fronx':'Maruti Suzuki','s-cross':'Maruti Suzuki','grand i10':'Hyundai','i20':'Hyundai','creta':'Hyundai','venue':'Hyundai','verna':'Hyundai','aura':'Hyundai','alcazar':'Hyundai','tucson':'Hyundai','seltos':'Kia','sonet':'Kia','carens':'Kia','wr-v':'Honda','wrv':'Honda','amaze':'Honda','elevate':'Honda','city':'Honda','innova crysta':'Toyota','innova':'Toyota','fortuner':'Toyota','glanza':'Toyota','hyryder':'Toyota','xuv700':'Mahindra','xuv500':'Mahindra','scorpio':'Mahindra','thar':'Mahindra','bolero':'Mahindra','harrier':'Tata','safari':'Tata','nexon':'Tata','punch':'Tata','tiago':'Tata','altroz':'Tata','aria':'Tata','polo':'Volkswagen','vento':'Volkswagen','virtus':'Volkswagen','taigun':'Volkswagen','superb':'Skoda','octavia':'Skoda','rapid':'Skoda','kushaq':'Skoda','slavia':'Skoda','kwid':'Renault','duster':'Renault','kiger':'Renault','triber':'Renault','ecosport':'Ford','endeavour':'Ford','figo':'Ford','hector':'MG','astor':'MG','compass':'Jeep','meridian':'Jeep','c200':'Mercedes-Benz','c-class':'Mercedes-Benz','e-class':'Mercedes-Benz','gla':'Mercedes-Benz','glc':'Mercedes-Benz','evoque':'Land Rover','discovery sport':'Land Rover','xc40':'Volvo','xc60':'Volvo','es 300h':'Lexus'};
 const brandAliases:[string,string][]=[['maruti suzuki','Maruti Suzuki'],['maruti','Maruti Suzuki'],['hyundai','Hyundai'],['kia','Kia'],['honda','Honda'],['toyota','Toyota'],['mahindra','Mahindra'],['tata','Tata'],['volkswagen','Volkswagen'],['skoda','Skoda'],['renault','Renault'],['nissan','Nissan'],['ford','Ford'],['mercedes','Mercedes-Benz'],['bmw','BMW'],['audi','Audi'],['land rover','Land Rover'],['range rover','Land Rover'],['mg','MG'],['jeep','Jeep'],['volvo','Volvo'],['lexus','Lexus']];
 const model=Object.keys(modelBrands).sort((a,b)=>b.length-a.length).find(name=>lower.includes(name))||'';
 let brand=brandAliases.find(([key])=>lower.includes(key))?.[1]||modelBrands[model]||'';
 const yearMatch=clean.match(/\b(20(?:0\d|1\d|2\d))(?:\s*\/\s*(20(?:0\d|1\d|2\d)))?\b/);const year=yearMatch?.[1]||'';
 const lakhKm=lower.match(/(\d+(?:\.\d+)?)\s*(?:lac|lakh|lacs|lakhs)\s*(?:km|kms|driven)\b/i);
 const directKm=lower.match(/(\d{1,3}(?:,\d{3})+|\d{4,6})\s*(?:km|kms|kilomet(?:er|re)s?|driven)\b/i);
 const km=lakhKm?Math.round(Number(lakhKm[1])*100000):directKm?Number(directKm[1].replace(/,/g,'')):'';
 const priceMatch=lower.match(/(?:asking(?:\s*price)?|price|rate|₹|rs\.?|inr)\s*[:=-]?\s*(\d+(?:[.,]\d+)*)\s*(lac|lakh|lacs|lakhs|l)?/i);
 let price:number|string='';if(priceMatch){const raw=Number(priceMatch[1].replace(/,/g,''));price=Math.round((priceMatch[2]||raw<1000)?raw*100000:raw)}
 const ownerMatch=lower.match(/\b([1-9])\s*(?:st|nd|rd|th)?\s*owner\b|\b(first|second|third|fourth)\s*owner\b/i);
 const ownerWords:Record<string,number>={first:1,second:2,third:3,fourth:4};const owner=ownerMatch?(ownerMatch[1]?Number(ownerMatch[1]):ownerWords[String(ownerMatch[2]).toLowerCase()]):'';
 const fuelMatch=lower.match(/\b(petrol|diesel|cng|electric|ev|hybrid)\b/i);const fuel=fuelMatch?(fuelMatch[1].toLowerCase()==='ev'?'Electric':fuelMatch[1][0].toUpperCase()+fuelMatch[1].slice(1).toLowerCase()):'';
 const cityMatch=clean.match(/(?:location|city)\s*[:=-]?\s*([A-Za-z ]{2,28}?)(?=\s+(?:price|rate|₹|rs\.?|\d{4,6}\s*km|\d+\s*(?:st|nd|rd|th)?\s*owner)|$)/i);const city=cityMatch?.[1]?.trim()||'Ambala City';
 let variant='';const variantMatch=clean.match(/\b(AX7L|AX7|HTX\+?|GTX\+?|X-?Line|RXT|RXZ|Titanium(?:\s+Plus)?|Trendline|Trend|Highline|Sportz|Asta|Era|Delta|Zeta|Alpha|ZXI(?:\+|\(O\))?|VXI(?:\+|\(O\))?|VDI|LDI|VX|ZX|XZ\+|XT\+|XZ|XT|HSE|SE|L&K|EX|SX\+?)\b/i);if(variantMatch)variant=variantMatch[1];else if(model){const idx=lower.indexOf(model.toLowerCase());if(idx>=0){const tail=clean.slice(idx+model.length).trim();variant=tail.split(/\b(?:petrol|diesel|cng|electric|hybrid|automatic|manual|amt|dct|cvt|\d+\s*(?:st|nd|rd|th)?\s*owner|\d[\d,.]*\s*(?:km|kms|lac|lakh)|price|rate|asking|₹|rs\.)\b/i)[0].trim().replace(/^(?:-|:)+|(?:-|:)+$/g,'').trim();if(variant.split(/\s+/).length>5)variant=''}}
 return {brand,model:model?model.replace(/\b\w/g,x=>x.toUpperCase()):'',variant,year,km,fuel,owner_count:owner,price,city,notes:input.trim()};
}
function applyQuickDetails(){if(!quickText.trim()){setMsg('Paste the vehicle details first.');return}const parsed=parseVehicleText(quickText);setF((prev:any)=>({...prev,...Object.fromEntries(Object.entries(parsed).filter(([,v])=>v!==''&&v!==undefined))}));const missing=['brand','model','year','km','fuel','owner_count','price'].filter(key=>(parsed as any)[key]===''||(parsed as any)[key]===undefined);setMsg(missing.length?'Details read. Please check: '+missing.join(', ')+'.':'Details auto-filled. Add photos and publish.');}
async function add(e:React.FormEvent){
 e.preventDefault();if(publishLock.current)return;
 const missing=[['brand','Brand'],['model','Model'],['year','Year'],['km','KM'],['fuel','Fuel'],['owner_count','Owner'],['price','Price'],['city','City']].filter(([key])=>!String(f[key]??'').trim()).map(([,label])=>label);
 if(missing.length){setMsg('Please check missing details: '+missing.join(', ')+'.');return}if(files.length<1){setMsg('Please select at least 1 photo.');return}
 publishLock.current=true;setPublishing(true);setDuplicateWarning(null);setPublishProgress({stage:'Checking for duplicate listing…',done:0,total:files.length,percent:5});setMsg('Submitting vehicle… please do not tap Publish again.');
 try{
  if(!allowDuplicateOnce){
   const existing=await findDuplicateVehicle();
   if(existing){setDuplicateWarning(existing);setMsg(`Duplicate blocked: ${existing.year} ${existing.brand} ${existing.model} is already in inventory.`);setPublishProgress({stage:'Duplicate blocked',done:0,total:files.length,percent:0});return}
  }
  if(!submissionId.current)submissionId.current=crypto.randomUUID();
  setPublishProgress({stage:'Creating secure draft…',done:0,total:files.length,percent:12});
  const {data,error}=await db.from('vehicles').insert({brand:f.brand,model:f.model,variant:f.variant,year:Number(f.year),km:Number(f.km),fuel:f.fuel,owner_count:Number(f.owner_count),asking_price:Number(f.price),city:f.city,public_notes:f.notes||'',status:'draft',client_submission_id:submissionId.current}).select().single();
  if(error){
   if((error as any)?.code==='23505'){setMsg('This vehicle submission was already received. Duplicate prevented.');setPublishProgress({stage:'Duplicate prevented',done:0,total:files.length,percent:100});await load();return}
   throw new Error(error.message);
  }
  setPublishProgress({stage:'Uploading vehicle photos…',done:0,total:files.length,percent:20});
  let media:string[]=[];
  try{media=await uploadPhotos(data.id,files)}catch(err:any){await db.from('vehicles').update({status:'archived'}).eq('id',data.id);submissionId.current='';setAllowDuplicateOnce(false);setMsg((err?.message?err.message+' — ':'')+'Upload interrupted. Incomplete attempt is hidden; press Publish to retry safely.');setPublishProgress({stage:'Upload interrupted — safe to retry',done:0,total:files.length,percent:0});await load();return}
  setPublishProgress({stage:'Finalizing listing…',done:files.length,total:files.length,percent:92});
  const published=await db.from('vehicles').update({status:'published'}).eq('id',data.id);if(published.error)throw new Error(published.error.message);
  setPublishProgress({stage:'Published. Preparing social queue…',done:files.length,total:files.length,percent:97});
  const social=await db.from('social_posts').insert(['instagram','facebook','youtube'].map(platform=>({vehicle_id:data.id,platform,caption:`${data.brand} ${data.model} ${data.variant||''} | ₹${data.asking_price}`,media_urls:media,status:'queued'})));
  setF({});setFiles([]);setQuickText('');setAllowDuplicateOnce(false);submissionId.current='';setPublishProgress({stage:'Vehicle published successfully',done:files.length,total:files.length,percent:100});
  setMsg(social.error?'Vehicle published. Social queue was not created, but the website listing is live.':'Vehicle published successfully. You can safely add the next car.');
  await load();
 }catch(err:any){setMsg(err?.message||'Vehicle submission failed. Please try again.');setPublishProgress({stage:'Submission failed',done:0,total:files.length,percent:0})}
 finally{publishLock.current=false;setPublishing(false)}
}
function startEdit(c:any){setEditing({...c});setEditFiles([]);setMsg('')}
async function saveEdit(e:React.FormEvent){e.preventDefault();if(!editing)return;setMsg('Saving changes…');const {error}=await db.from('vehicles').update({brand:editing.brand,model:editing.model,variant:editing.variant,year:Number(editing.year),km:Number(editing.km),fuel:editing.fuel,owner_count:Number(editing.owner_count),asking_price:Number(editing.asking_price),city:editing.city,public_notes:editing.public_notes||'',status:editing.status}).eq('id',editing.id);if(error){setMsg(error.message);return}try{if(editFiles.length)await uploadPhotos(editing.id,editFiles);setEditing(null);setEditFiles([]);setMsg('Vehicle updated.');load()}catch(err:any){setMsg(err.message)}}
async function deletePhoto(p:any){if(!confirm('Delete this photo?'))return;const {error}=await db.from('vehicle_photos').delete().eq('id',p.id);if(error){setMsg(error.message);return}if(p.path)await db.storage.from('vehicle-photos').remove([p.path]);if(editing){setEditing({...editing,vehicle_photos:(editing.vehicle_photos||[]).filter((x:any)=>x.id!==p.id)})}}
async function status(id:string,status:string){const {error}=await db.from('vehicles').update({status}).eq('id',id);if(error)setMsg(error.message);load()}
async function appStatus(id:string,status:string){const {data,error}=await db.from('dealer_applications').update({status}).eq('id',id).select('applicant_user_id').single();if(error){setMsg(error.message);return}if(status==='approved'&&data?.applicant_user_id){const p=await db.from('profiles').update({role:'dealer',active:true}).eq('id',data.applicant_user_id);if(p.error){setMsg(p.error.message);return}}if(status==='rejected'&&data?.applicant_user_id){await db.from('profiles').update({active:false}).eq('id',data.applicant_user_id)}setMsg(`Dealer application ${status}.`);load()}
async function partnerStatus(id:string,status:string){const {data,error}=await db.from('collaboration_requests').update({status}).eq('id',id).select('applicant_user_id').single();if(error){setMsg(error.message);return}if(status==='approved'&&data?.applicant_user_id){const p=await db.from('profiles').update({role:'partner',active:true}).eq('id',data.applicant_user_id);if(p.error){setMsg(p.error.message);return}}if(status==='rejected'&&data?.applicant_user_id){await db.from('profiles').update({active:false}).eq('id',data.applicant_user_id)}setMsg(`Partner application ${status}.`);load()}
async function assignRequest(id:string,partnerId:string){const {error}=await db.from('service_requests').update({assigned_partner_id:partnerId||null,status:partnerId?'assigned':'new',updated_at:new Date().toISOString()}).eq('id',id);if(error){setMsg(error.message);return}setMsg(partnerId?'Request assigned to partner.':'Assignment removed.');load()}
async function leadStatus(id:string,status:string){const {error}=await db.from('leads').update({status}).eq('id',id);if(error){setMsg(error.message);return}setMsg(`Customer lead marked ${status}.`);load()}
const publishedCars=cars.filter(c=>c.status==='published').length;
const openSales=salesLeads.filter(l=>!['closed','lost','completed'].includes(String(l.status||'new'))).length;
const openServices=requests.filter(r=>!['completed','closed','cancelled'].includes(String(r.status||'new'))).length;
const pendingApprovals=apps.filter(a=>['new','reviewing'].includes(String(a.status||'new'))).length+partnerApps.filter(a=>['new','reviewing'].includes(String(a.status||'new'))).length;
if(accessDenied)return <main><div className="auth"><h1>ROHILLA DRIVE</h1><h2>Administration Console</h2><p>{msg}</p><div className="row"><a className="call" href="/dealer">Dealer Workspace</a><a className="call" href="/partner">Partner Workspace</a><a className="call" href="/">Public Website</a></div><button onClick={()=>db.auth.signOut().then(()=>location.reload())}>Sign Out</button></div></main>;if(!session)return <main><div className="auth"><h1>ROHILLA DRIVE</h1><h2>Administration Console</h2><p>Secure access for authorised administration users.</p><form onSubmit={login}><input name="email" type="email" placeholder="Administrator email" required/><input name="password" type="password" placeholder="Password" required/><button>Sign In</button></form><p>{msg}</p></div></main>;
if(mfaMode==='setup')return <main><div className="auth"><h1>Administrator Security Setup</h1><p>Scan the QR code with your authenticator app, then enter the 6-digit verification code.</p>{mfaData?.totp?.qr_code&&<img src={mfaData.totp.qr_code} alt="Authenticator QR code" style={{width:220,height:220,background:'#fff',padding:12,borderRadius:12}}/>}<p style={{wordBreak:'break-all',fontSize:12}}>Manual setup key: {mfaData?.totp?.secret}</p><input inputMode="numeric" maxLength={6} placeholder="6-digit code" value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/g,'').slice(0,6))}/><button disabled={mfaBusy||mfaCode.length!==6} onClick={verifySetup}>{mfaBusy?'Verifying…':'Verify & Enable Authenticator'}</button><p>{msg}</p><button onClick={()=>db.auth.signOut().then(()=>location.reload())}>Cancel and Sign Out</button></div></main>;
if(mfaMode==='challenge')return <main><div className="auth"><h1>ROHILLA DRIVE</h1><h2>Administration Console</h2><p>Multi-factor authentication required.</p><input autoFocus inputMode="numeric" maxLength={6} placeholder="6-digit code" value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/g,'').slice(0,6))}/><button disabled={mfaBusy||mfaCode.length!==6} onClick={verifyChallenge}>{mfaBusy?'Verifying…':'Verify Code'}</button><p>{msg}</p><button onClick={()=>db.auth.signOut().then(()=>location.reload())}>Sign Out</button></div></main>;
return <main><header><div className="brand"><b>ROHILLA DRIVE</b><small>Administration Console</small></div><div className="row"><a className="call" href="/admin/verification">Verification Operations</a><button onClick={()=>db.auth.signOut().then(()=>location.reload())}>Sign Out</button></div></header>
<section className="section adminDashboardIntro">
 <div className="adminEyebrow">ADMINISTRATION</div>
 <div className="adminDashboardHeading"><div><h1>Operations Dashboard</h1><p>Your fastest actions stay at the top: paste vehicle details, publish inventory and mark sold cars without hunting through menus.</p></div><div className="adminHeaderActions"><a href="#quick-add">Quick Add Vehicle</a><a className="secondaryAction" href="#quick-sold">Mark Vehicle Sold</a></div></div>
 <div className="adminFastDesk">
  <div className="adminFastCard adminFastAdd" id="quick-add"><span>FAST VEHICLE INTAKE</span><h2>Paste full car details</h2><p>Paste the same text you normally send on WhatsApp. Year, KM, fuel, owner, price, brand/model and location are read automatically where possible.</p><textarea rows={5} value={quickText} onChange={e=>setQuickText(e.target.value)} placeholder={"Example:\n2019 Creta EX 1.4 Diesel, 2nd owner, 1.20 lac km, Ambala City, price 6.45 lakh, all original"} /><button type="button" onClick={applyQuickDetails}>Auto-Fill Vehicle Details</button></div>
  <div className="adminFastCard adminFastSold" id="quick-sold"><span>FAST INVENTORY ACTION</span><h2>Mark a vehicle sold</h2><p>Select any live vehicle and remove it from available inventory immediately.</p><select value={soldVehicleId} onChange={e=>setSoldVehicleId(e.target.value)}><option value="">Select published vehicle</option>{cars.filter(c=>c.status==='published').map(c=><option key={c.id} value={c.id}>{c.year} {c.brand} {c.model} {c.variant||''}</option>)}</select><button type="button" disabled={!soldVehicleId} onClick={async()=>{if(!soldVehicleId)return;await status(soldVehicleId,'sold');setSoldVehicleId('');setMsg('Vehicle marked sold.')}}>Mark Vehicle Sold</button><a href="#inventory-list">Open Full Inventory</a></div>
 </div>
 <div className="adminOverviewGrid">
  <a href="/admin/add-vehicle" className="adminOverviewCard"><span>Published Inventory</span><strong>{publishedCars}</strong><small>Live vehicles</small></a>
  <a href="#customer-leads" className="adminOverviewCard"><span>Open Customer Leads</span><strong>{openSales}</strong><small>Needs follow-up</small></a>
  <a href="/admin/service-operations" className="adminOverviewCard"><span>Service Requests</span><strong>{openServices}</strong><small>Active queue</small></a>
  <a href="/admin/partner-kyc" className="adminOverviewCard"><span>Pending Approvals</span><strong>{pendingApprovals}</strong><small>Dealer + partner</small></a>
 </div>
 <div className="adminQuickActions">
  <a href="/admin/seller-submissions"><b>Seller Submissions</b><span>Review cars submitted by customers</span></a>
  <a href="/admin/deal-rooms"><b>Deal Management</b><span>Track active negotiations and handoffs</span></a>
  <a href="/admin/revenue"><b>Revenue & Collections</b><span>Monitor money movement and collections</span></a>
  <a href="/admin/connections"><b>Integrations</b><span>Manage connected business services</span></a>
 </div>
</section>
<section className="section adminVehiclePanel"><div className="adminSectionKicker">READY TO PUBLISH</div><h2>Add Vehicle</h2><p>Paste details above, check the summary, add photos and publish. Open manual details only if something needs correction.</p><form className="adminForm adminFastPublishForm" onSubmit={add}><div className="adminParsedSummary"><div><span>VEHICLE</span><b>{f.brand||'—'} {f.model||''} {f.variant||''}</b></div><div><span>DETAILS</span><b>{f.year||'—'} • {f.km?Number(f.km).toLocaleString('en-IN')+' km':'—'} • {f.fuel||'—'} • {f.owner_count?f.owner_count+' Owner':'—'}</b></div><div><span>PRICE / CITY</span><b>{f.price?'₹'+Number(f.price).toLocaleString('en-IN'):'—'} • {f.city||'—'}</b></div></div><details className="adminManualDetails"><summary>Review / correct parsed details</summary><div className="adminManualGrid"><input placeholder="Brand" value={f.brand||''} onChange={e=>setF({...f,brand:e.target.value})}/><input placeholder="Model" value={f.model||''} onChange={e=>setF({...f,model:e.target.value})}/><input placeholder="Variant" value={f.variant||''} onChange={e=>setF({...f,variant:e.target.value})}/><input type="number" placeholder="Year" value={f.year||''} onChange={e=>setF({...f,year:e.target.value})}/><input type="number" placeholder="KM" value={f.km||''} onChange={e=>setF({...f,km:e.target.value})}/><input placeholder="Fuel" value={f.fuel||''} onChange={e=>setF({...f,fuel:e.target.value})}/><input type="number" placeholder="Owners" value={f.owner_count||''} onChange={e=>setF({...f,owner_count:e.target.value})}/><input type="number" placeholder="Asking Price ₹" value={f.price||''} onChange={e=>setF({...f,price:e.target.value})}/><input placeholder="City" value={f.city||''} onChange={e=>setF({...f,city:e.target.value})}/><textarea placeholder="Description / features" value={f.notes||''} onChange={e=>setF({...f,notes:e.target.value})}/></div></details><label className="upload adminPhotoUpload">Add vehicle photos<input required multiple accept="image/*" type="file" onChange={e=>setFiles(Array.from(e.target.files||[]))}/><span>{files.length?files.length+' photo(s) selected':'Choose photos'}</span></label>{duplicateWarning&&<div className="adminDuplicateWarning"><b>Possible duplicate blocked</b><span>{duplicateWarning.year} {duplicateWarning.brand} {duplicateWarning.model} {duplicateWarning.variant||''} • {Number(duplicateWarning.km).toLocaleString('en-IN')} km • ₹{Number(duplicateWarning.asking_price).toLocaleString('en-IN')}</span><div><button type="button" onClick={()=>document.getElementById('inventory-list')?.scrollIntoView({behavior:'smooth'})}>Open Existing Inventory</button><button type="button" className="secondary" onClick={()=>{setAllowDuplicateOnce(true);setDuplicateWarning(null);setMsg('Duplicate override enabled for one publish only. Press Publish again if this is genuinely a different car.')}}>This Is A Different Car</button></div></div>}
{publishing&&<div className="adminPublishProgress" aria-live="polite"><div><b>{publishProgress.stage}</b><span>{publishProgress.total?Math.min(publishProgress.done,publishProgress.total)+' / '+publishProgress.total+' photos':''}</span></div><div className="adminProgressTrack"><i style={{width:`${publishProgress.percent}%`}}/></div><small>Keep this page open. Publish is locked while submission is running.</small></div>}
<button className="adminPublishButton" disabled={publishing}>{publishing?'Submitting… '+publishProgress.percent+'%':'Publish Vehicle Live'}</button></form><p className="adminActionMessage">{msg}</p></section>
<section className="section" id="inventory-list"><h2>Inventory ({cars.length})</h2>{cars.length===0?<p>No vehicles yet.</p>:<div className="grid">{cars.map(c=><article className="card" key={c.id}><div className="photo real">{c.vehicle_photos?.[0]?.url&&<img src={c.vehicle_photos[0].url}/>}</div><div className="body"><h3>{c.brand} {c.model} {c.variant}</h3><p>{c.year} • {c.km} km • {c.city}</p><strong>₹{Number(c.asking_price).toLocaleString('en-IN')}</strong><small>{c.vehicle_photos?.length||0} photos • {c.status}</small><div className="row"><button onClick={()=>startEdit(c)}>Edit</button>{c.status==='published'?<button onClick={()=>status(c.id,'sold')}>Mark Sold</button>:<button onClick={()=>status(c.id,'published')}>Publish</button>}</div></div></article>)}</div>}</section>
{editing&&<div className="overlay"><div className="modal"><button className="x" onClick={()=>setEditing(null)} aria-label="Close editor">×</button><h2>Edit Vehicle</h2><form className="adminForm" onSubmit={saveEdit}><input required value={editing.brand||''} onChange={e=>setEditing({...editing,brand:e.target.value})} placeholder="Brand"/><input required value={editing.model||''} onChange={e=>setEditing({...editing,model:e.target.value})} placeholder="Model"/><input value={editing.variant||''} onChange={e=>setEditing({...editing,variant:e.target.value})} placeholder="Variant"/><input required type="number" value={editing.year||''} onChange={e=>setEditing({...editing,year:e.target.value})} placeholder="Year"/><input required type="number" value={editing.km||''} onChange={e=>setEditing({...editing,km:e.target.value})} placeholder="KM"/><input required value={editing.fuel||''} onChange={e=>setEditing({...editing,fuel:e.target.value})} placeholder="Fuel"/><input required type="number" value={editing.owner_count||''} onChange={e=>setEditing({...editing,owner_count:e.target.value})} placeholder="Owners"/><input required type="number" value={editing.asking_price||''} onChange={e=>setEditing({...editing,asking_price:e.target.value})} placeholder="Asking Price ₹"/><input required value={editing.city||''} onChange={e=>setEditing({...editing,city:e.target.value})} placeholder="City"/><textarea value={editing.public_notes||''} onChange={e=>setEditing({...editing,public_notes:e.target.value})} placeholder="Description / features"/><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="sold">Sold</option><option value="archived">Archived</option></select><div className="photoStrip">{(editing.vehicle_photos||[]).sort((a:any,b:any)=>a.sort_order-b.sort_order).map((p:any)=><div key={p.id} className="thumb"><img src={p.url}/><button type="button" onClick={()=>deletePhoto(p)}>Delete</button></div>)}</div><label className="upload">Add more photos<input multiple accept="image/*" type="file" onChange={e=>setEditFiles(Array.from(e.target.files||[]))}/></label><button>Save Changes</button></form><p>{msg}</p></div></div>}
<section className="section" id="customer-leads"><h2>Customer Sales, New Vehicle & Listing Leads ({salesLeads.length})</h2>{salesLeads.length===0?<p>No website sales or listing leads yet.</p>:salesLeads.map(l=><article className="application" key={l.id}><b>{String(l.enquiry_type||l.requirement||'Customer enquiry').replaceAll('_',' ')}</b><p>{l.customer_name||'Customer'} • {l.customer_phone||'No phone'} • {l.new_or_used||'vehicle'}</p><p>{l.message||l.requirement||'—'}</p><small>Source: {l.source||'website'} • Status: {l.status||'new'}</small><div className="row"><button onClick={()=>leadStatus(l.id,'contacted')}>Contacted</button><button onClick={()=>leadStatus(l.id,'qualified')}>Qualified</button><button onClick={()=>leadStatus(l.id,'closed')}>Closed</button></div></article>)}</section>
<section className="section"><h2>Dealer Applications ({apps.length})</h2>{apps.length===0?<p>No dealer applications yet.</p>:apps.map(a=><article className="application" key={a.id}><b>{a.business_name}</b><p>{a.contact_name} • {a.mobile} • {a.city} • approx {a.inventory_count||0} vehicles</p><p>{a.services}</p><small>Status: {a.status}</small><div><button onClick={()=>appStatus(a.id,'reviewing')}>Reviewing</button><button onClick={()=>appStatus(a.id,'approved')}>Approve</button><button onClick={()=>appStatus(a.id,'rejected')}>Reject</button></div></article>)}</section>
<section className="section"><h2>Partner Applications ({partnerApps.length})</h2>{partnerApps.length===0?<p>No partner applications yet.</p>:partnerApps.map(a=><article className="application" key={a.id}><b>{a.business_name||'ROHILLA DRIVE Partner'}</b><p>{a.contact} • {a.city} • {a.category}</p><p>{a.message||'—'}</p><small>Status: {a.status}</small><div><button onClick={()=>partnerStatus(a.id,'reviewing')}>Reviewing</button><button onClick={()=>partnerStatus(a.id,'approved')}>Approve</button><button onClick={()=>partnerStatus(a.id,'rejected')}>Reject</button></div></article>)}</section>
<section className="section"><h2>Customer Service Requests ({requests.length})</h2>{requests.length===0?<p>No customer service requests yet.</p>:requests.map(r=><article className="application" key={r.id}><b>{r.category}</b><p>{r.customer_name} • {r.customer_phone} • {r.customer_location||'Location not given'}</p>{r.vehicle&&<p>Vehicle: {r.vehicle.brand} {r.vehicle.model} {r.vehicle.variant||''} {r.vehicle.year||''}</p>}<p>{r.details||'—'}{r.preferred_time?` • Preferred: ${r.preferred_time}`:''}</p><small>Status: {r.status}{r.assigned_partner_id?' • Partner assigned':''}</small><div><select value={r.assigned_partner_id||''} onChange={e=>assignRequest(r.id,e.target.value)}><option value="">{r.assigned_partner_id?'Remove assignment':'Assign Partner'}</option>{partners.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.business_name||p.name||'Partner'} • {p.city||'Area'} • {p.service_categories||'Service'}</option>)}</select></div></article>)}</section>
<section className="section"><h2>Social Publishing Queue</h2><p>Website publishing is independent from social delivery. Instagram/Facebook/YouTube queue records can be created, while automatic external posting still requires the official platform API/OAuth connections.</p></section></main>}
