"use client";
import {useState} from "react";
import {supabase} from "../supabaseClient";
import CustomerBackBar from "./CustomerBackBar";

export default function DealerJoinForm({kind}:{kind:"oem"|"preowned"}){
 const db=supabase();const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 const isOem=kind==="oem";const title=isOem?"OEM / Authorised New Vehicle Dealer":"Pre-Owned / Used Vehicle Dealer";
 async function signup(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("Creating account…");const x=new FormData(e.currentTarget);const email=String(x.get("email")),password=String(x.get("password")),name=String(x.get("name")),mobile=String(x.get("mobile")),business=String(x.get("business_name")),city=String(x.get("city")),address=String(x.get("address"));const service=isOem?"OEM / Authorised New Vehicle Dealer":"Pre-Owned / Used Vehicle Dealer";const {data,error}=await db.auth.signUp({email,password,options:{data:{network_role:"dealer",dealer_type:kind,name,phone:mobile,business_name:business,address,city,service_categories:service}}});if(error){setBusy(false);setMsg(error.message);return}if(!data.user){setBusy(false);setMsg("Account could not be created.");return}const {error:appError}=await db.from("dealer_applications").insert({applicant_user_id:data.user.id,business_name:business,contact_name:name,mobile,city,address,inventory_count:Number(x.get("inventory_count")||0),services:[service,String(x.get("brands")||""),String(x.get("services")||"")].filter(Boolean).join(" • "),message:String(x.get("message")||""),status:"new"});setBusy(false);if(appError){setMsg(appError.message);return}setMsg("Application submitted ✓ Rohilla Drive Admin will review your account. You can use Dealer Login after approval.")}
 return <main><CustomerBackBar/><header><div className="brand"><b>ROHILLA DRIVE</b><small>{title} Registration</small></div><div className="row"><a className="call" href="/dealer">Dealer Login</a><a className="call" href="/business-hub">Business Hub</a></div></header><section className="hero"><div className="heroText"><span>DIRECT REGISTRATION</span><h1>{title}</h1><p>Create the account here. No separate link from Rohilla Drive is required.</p></div></section><section className="section"><form className="adminForm" onSubmit={signup}><input name="name" placeholder="Contact name" required/><input name="business_name" placeholder={isOem?"Dealership / Showroom name":"Business / Dealership name"} required/><input name="mobile" placeholder="Mobile" required/><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" minLength={6} placeholder="Create password" required/><input name="city" placeholder="City / Territory" required/><input name="address" placeholder="Business address" required/>{isOem?<><input name="brands" placeholder="Authorised OEM brand(s)" required/><input name="services" placeholder="New car / bike / commercial / EV / fleet sales team"/></>:<><input name="inventory_count" type="number" min="0" placeholder="Approx inventory count"/><input name="brands" placeholder="Main brands / categories"/><input name="services" placeholder="Cars / SUVs / Two-wheelers / Commercial / EV / other"/></>}<textarea name="message" placeholder="Coverage, team, authorised status, categories and what you want from Rohilla Drive"/><button disabled={busy}>{busy?"Submitting…":"Create Account & Submit for Approval"}</button></form>{msg&&<div className="notice">{msg}</div>}<div className="notice">Already registered? <a href="/dealer"><b>Dealer / OEM Login →</b></a></div></section></main>
}
