"use client";
import {useEffect,useState} from "react";
import {supabase} from "../supabaseClient";

declare global {interface Window{webkitSpeechRecognition?:any;SpeechRecognition?:any}}

export default function GrowthConsole({actorRole,title,homeHref}:{actorRole:"admin"|"dealer"|"partner";title:string;homeHref:string}){
 const db=supabase();const [session,setSession]=useState<any>(null);const [authorized,setAuthorized]=useState(false);const [checking,setChecking]=useState(true);const [command,setCommand]=useState("");const [jobs,setJobs]=useState<any[]>([]);const [cars,setCars]=useState<any[]>([]);const [vehicle,setVehicle]=useState("");const [channels,setChannels]=useState<string[]>(["instagram","facebook","youtube"]);const [msg,setMsg]=useState("");const [listening,setListening]=useState(false);
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();setSession(session);if(!session){setMsg(`${actorRole==="partner"?"Business Hub":actorRole} login required.`);setChecking(false);return}if(actorRole==="admin"){const [{data:aal},{data:isAdmin}]=await Promise.all([db.auth.mfa.getAuthenticatorAssuranceLevel(),db.rpc("is_admin")]);if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Admin + Authenticator verification required.");setChecking(false);return}}else{const {data:p}=await db.from("profiles").select("role,active").eq("id",session.user.id).single();if(!p||p.role!==actorRole||!p.active){setMsg(`Approved ${actorRole==="partner"?"Business Hub Partner":"Dealer"} access required.`);setChecking(false);return}}setAuthorized(true);setChecking(false);await load(session.user.id)})()},[]);
 async function load(uid?:string){const userId=uid||session?.user?.id;if(!userId)return;let q=db.from("automation_jobs").select("*").order("created_at",{ascending:false}).limit(30);if(actorRole!=="admin")q=q.eq("created_by",userId);const {data,error}=await q;if(error){setMsg(error.message);return}setJobs(data||[]);if(actorRole==="dealer"){const {data:v}=await db.from("vehicles").select("id,brand,model,variant,year,status").eq("partner_id",userId).order("created_at",{ascending:false});setCars(v||[])}}
 function toggle(ch:string){setChannels(x=>x.includes(ch)?x.filter(y=>y!==ch):[...x,ch])}
 function structured(text:string){const t=text.toLowerCase();return {hide_plate:/hide.*(number|plate)|number.*hide|plate.*hide/.test(t),keep_plate:/show.*(number|plate)|number.*show/.test(t),multiple_creatives:/multiple|different photo|several|3 photo|4 photo|5 photo/.test(t),poster:/poster|creative|ad image/.test(t),reel:/reel|short|video/.test(t),publish:/post|publish|upload|social/.test(t),seo:/google|seo|search/.test(t),ads:/adword|google ad|ads campaign/.test(t),language:/hindi|hinglish/.test(t)?"hinglish":"auto"}}
 function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMsg("Voice recognition is not available in this browser. Type the same command instead.");return}const r=new SR();r.lang="hi-IN";r.interimResults=false;r.continuous=false;setListening(true);r.onresult=(e:any)=>{setCommand((old:string)=>[old,e.results?.[0]?.[0]?.transcript||""].filter(Boolean).join(" "));setListening(false)};r.onerror=()=>{setListening(false);setMsg("Voice capture stopped. You can type the command.")};r.onend=()=>setListening(false);r.start()}
 async function queue(){if(!session||!authorized||!command.trim())return;setMsg("Creating Rohilla Growth command…");const payload={intent:structured(command),requested_channels:channels,portal:actorRole};const {error}=await db.from("automation_jobs").insert({created_by:session.user.id,actor_role:actorRole,job_type:"growth_command",command:command.trim(),channels,source_vehicle_id:vehicle||null,payload,status:"queued"});if(error){setMsg(error.message);return}setCommand("");setMsg("Command queued ✓ It can be processed automatically once the required AI/social/ad connections are authorised.");await load()}
 if(checking)return <main><section className="section"><h1>ROHILLA INTELLIGENCE</h1><p>Checking secure access…</p></section></main>;
 if(!authorized)return <main><section className="section"><h1>ROHILLA INTELLIGENCE</h1><p>{msg}</p><a className="call" href={homeHref}>Back</a></section></main>;
 return <main><header><div className="brand"><b>ROHILLA INTELLIGENCE</b><small>{title}</small></div><div className="row"><a className="call" href={homeHref}>Back</a></div></header><section className="section"><h1>Voice / Text Growth Command</h1><p>Describe the outcome, not the buttons. Example: “2022 Creta ki photos se 3 creatives banao, number plate hide rakho, Instagram Facebook aur YouTube ke drafts ready karo.”</p>{actorRole==="dealer"&&<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">No specific vehicle</option>{cars.map(c=><option key={c.id} value={c.id}>{c.year||""} {c.brand} {c.model} {c.variant||""}</option>)}</select>}<textarea style={{width:"100%",minHeight:130,marginTop:12}} placeholder="Speak or type a command…" value={command} onChange={e=>setCommand(e.target.value)}/><div className="row" style={{marginTop:10}}><button onClick={voice}>{listening?"🎙️ Listening…":"🎙️ Speak Command"}</button>{["instagram","facebook","youtube","google_ads","seo"].map(ch=><button key={ch} className={channels.includes(ch)?"filter active":"filter"} onClick={()=>toggle(ch)}>{ch.replace("_"," ")}</button>)}</div><button style={{marginTop:12}} onClick={queue} disabled={!command.trim()}>Queue Command</button>{msg&&<div className="notice">{msg}</div>}</section><section className="section"><h2>My Growth Queue</h2>{jobs.length===0?<p>No commands yet.</p>:<div className="grid">{jobs.map(j=><article className="application" key={j.id}><label>{j.status}</label><h3>{j.job_type.replace("_"," ")}</h3><p>{j.command}</p><small>{Array.isArray(j.channels)?j.channels.join(" • "):""} • {new Date(j.created_at).toLocaleString()}</small></article>)}</div>}</section><section className="section dark"><div className="about"><h2>What this layer is designed to become</h2><p>Multimodal vehicle understanding → creative generation → plate/privacy rules → SEO copy → social drafts → scheduled publishing → ad campaign drafts → performance feedback. The command bus is live; actual generation/publishing needs official AI and platform authorisation.</p></div></section></main>
}
