"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../supabaseClient";
import {LANGUAGE_STORAGE_KEY,ROHILLA_LANGUAGES,languageByCode} from "../lib/rohilla-languages";

declare global {interface Window{webkitSpeechRecognition?:any;SpeechRecognition?:any}}

const PIPELINE=[
 ["1","Brief","Objective, vehicle, offer and audience"],
 ["2","Privacy Review","Number plate, phone and private-data controls"],
 ["3","Content","Photos, listing copy, social posts and short-form video plan"],
 ["4","Localisation","Language and regional variants"],
 ["5","Quality Review","Brand, facts, pricing and permissions"],
 ["6","Distribution","Website and approved external channels"],
 ["7","Measurement","Views, enquiries and conversion signals"],
 ["8","Optimisation","Use results to improve the next campaign"]
] as const;

const clean=(v:any)=>String(v||"").replace(/\s+/g," ").trim();
const statusLabel=(s:any)=>clean(s).replace(/_/g," ").replace(/\b\w/g,x=>x.toUpperCase());
function hashtags(car:any){const bits=["RohillaDrive","RohillaMultibrandCars","UsedCars","CarForSale","BuyCar","SellCar",clean(car?.brand).replace(/[^a-z0-9]/gi,""),clean(car?.model).replace(/[^a-z0-9]/gi,""),clean(car?.city||"AmbalaCity").replace(/[^a-z0-9]/gi,"")].filter(Boolean);return [...new Set(bits)].map(x=>`#${x}`).join(" ")}

export default function GrowthConsole({actorRole,title,homeHref}:{actorRole:"admin"|"dealer"|"partner";title:string;homeHref:string}){
 const db=supabase();const [session,setSession]=useState<any>(null);const [authorised,setAuthorised]=useState(false);const [checking,setChecking]=useState(true);const [command,setCommand]=useState("");const [jobs,setJobs]=useState<any[]>([]);const [cars,setCars]=useState<any[]>([]);const [vehicle,setVehicle]=useState("");const [channels,setChannels]=useState<string[]>(["website","instagram","facebook","youtube","seo"]);const [contentLangs,setContentLangs]=useState<string[]>(["en-IN","hi-IN"]);const [operatorLang,setOperatorLang]=useState("hi-IN");const [msg,setMsg]=useState("");const [listening,setListening]=useState(false);const [organic,setOrganic]=useState<any>(null);const [leadRows,setLeadRows]=useState<any[]>([]);
 useEffect(()=>{setOperatorLang(localStorage.getItem(LANGUAGE_STORAGE_KEY)||"hi-IN");(async()=>{const {data:{session}}=await db.auth.getSession();setSession(session);if(!session){setMsg(`${actorRole==="partner"?"Partner":actorRole==="dealer"?"Dealer":"Administrator"} sign-in is required.`);setChecking(false);return}if(actorRole==="admin"){const [{data:aal},{data:isAdmin}]=await Promise.all([db.auth.mfa.getAuthenticatorAssuranceLevel(),db.rpc("is_admin")]);if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Administrator authentication is required.");setChecking(false);return}}else{const {data:p}=await db.from("profiles").select("role,active").eq("id",session.user.id).single();if(!p||p.role!==actorRole||!p.active){setMsg(`Approved ${actorRole==="partner"?"partner":"dealer"} access is required.`);setChecking(false);return}}setAuthorised(true);setChecking(false);await load(session.user.id)})()},[]);
 async function load(uid?:string){const userId=uid||session?.user?.id;if(!userId)return;let q=db.from("automation_jobs").select("*").order("created_at",{ascending:false}).limit(30);if(actorRole!=="admin")q=q.eq("created_by",userId);const {data,error}=await q;if(error){setMsg(error.message);return}setJobs(data||[]);if(actorRole==="dealer"){const {data:v}=await db.from("vehicles").select("id,brand,model,variant,year,km,fuel,asking_price,city,status,vehicle_photos(url,sort_order)").eq("partner_id",userId).order("created_at",{ascending:false});setCars(v||[])}else if(actorRole==="admin"){const [{data:v},{data:l}]=await Promise.all([db.from("vehicles").select("id,brand,model,variant,year,km,fuel,asking_price,city,status,vehicle_photos(url,sort_order)").order("created_at",{ascending:false}).limit(150),db.from("leads").select("source,status,enquiry_type,created_at").order("created_at",{ascending:false}).limit(1000)]);setCars(v||[]);setLeadRows(l||[])}}
 function toggle(ch:string){setChannels(x=>x.includes(ch)?x.filter(y=>y!==ch):[...x,ch])}
 function toggleLang(code:string){setContentLangs(x=>x.includes(code)?x.filter(y=>y!==code):[...x,code])}
 function structured(text:string){const t=text.toLowerCase();return {hide_plate:/hide.*(number|plate)|number.*hide|plate.*hide/.test(t),keep_plate:/show.*(number|plate)|number.*show/.test(t),multiple_creatives:/multiple|different photo|several|3 photo|4 photo|5 photo/.test(t),poster:/poster|creative|ad image/.test(t),reel:/reel|short|video/.test(t),publish:/post|publish|upload|social/.test(t),seo:/google|seo|search/.test(t),ads:/adword|google ad|ads campaign/.test(t),lead_followup:/follow.?up|lead|customer reply|whatsapp/.test(t),new_vehicle:/new vehicle|new car|oem|showroom|dealer quote/.test(t),language:/punjabi|kannada|tamil|telugu|malayalam|marathi|gujarati|bengali|hindi|english/.test(t)?"multilingual":"auto"}}
 function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMsg("Voice input is not available in this browser. Type the brief instead.");return}const r=new SR();r.lang=languageByCode(operatorLang).speechCode;r.interimResults=false;r.continuous=false;setListening(true);r.onresult=(e:any)=>{setCommand((old:string)=>[old,e.results?.[0]?.[0]?.transcript||""].filter(Boolean).join(" "));setListening(false)};r.onerror=()=>{setListening(false);setMsg("Voice input stopped. You can continue by typing the brief.")};r.onend=()=>setListening(false);r.start()}
 async function queue(){if(!session||!authorised||!command.trim())return;setMsg("Adding campaign plan to the queue…");const intent=structured(command);const payload={pipeline_version:2,intent,requested_channels:channels,target_languages:contentLangs,operator_language:operatorLang,portal:actorRole,pipeline:PIPELINE.map(([step,name])=>({step,name,status:"planned"})),guardrails:{external_publish:"requires official connection and permission",ad_spend:hasGenuineLead?"requires explicit owner approval before any paid spend":"locked at zero paid spend until the first genuine lead",private_data:"never expose private customer or vehicle fields",plate_rule:intent.hide_plate?"mask requested":intent.keep_plate?"show requested":"follow account/default policy",fact_check:"vehicle facts and prices must be verified before distribution"}};const {error}=await db.from("automation_jobs").insert({created_by:session.user.id,actor_role:actorRole,job_type:"rohilla_intelligence_v2",command:command.trim(),channels,source_vehicle_id:vehicle||null,payload,status:"queued"});if(error){setMsg(error.message);return}setCommand("");setMsg("Campaign plan added to the queue with language, privacy and review controls.");await load()}
 const selectedCar=useMemo(()=>cars.find(c=>c.id===vehicle)||null,[cars,vehicle]);
 const sourceStats=useMemo(()=>{const map=new Map<string,{source:string,total:number,buy:number,sell:number,newCount:number}>();for(const lead of leadRows){const source=clean(lead.source)||"unknown";const row=map.get(source)||{source,total:0,buy:0,sell:0,newCount:0};row.total++;if(lead.enquiry_type==="buy_vehicle")row.buy++;if(lead.enquiry_type==="sell_vehicle")row.sell++;if(lead.status==="new")row.newCount++;map.set(source,row)}return [...map.values()].sort((a,b)=>b.total-a.total)},[leadRows]);
 const hasGenuineLead=leadRows.length>0;
 function buildOrganic(){const c=selectedCar;if(!c&&!command.trim()){setMsg("Choose a vehicle or enter a promotion brief first.");return}const vehicleLine=c?`${c.year||""} ${c.brand||""} ${c.model||""} ${c.variant||""}`.replace(/\s+/g," ").trim():"ROHILLA DRIVE automotive update";const spec=c?[c.fuel,c.km?`${Number(c.km).toLocaleString("en-IN")} km`:"",c.city].filter(Boolean).join(" • "):"";const price=c?.asking_price?`₹${Number(c.asking_price).toLocaleString("en-IN")}`:"Price / details on request";const caption=[`🚘 ${vehicleLine}`,spec,`💰 ${price}`,command.trim()?`✨ ${command.trim()}`:"",`📍 ${c?.city||"Ambala City"}`,"📞 7015260003","ROHILLA DRIVE — One network. Every vehicle. Every language.",hashtags(c)].filter(Boolean).join("\n");const hook=c?`${c.year||""} ${c.brand} ${c.model} — available through ROHILLA DRIVE.`:"One network for the complete vehicle journey.";const reel=[`0–2 sec: ${hook}`,"2–6 sec: Front and side walk-around",c?`6–10 sec: Show ${spec||"key condition and features"}`:"6–10 sec: Show the main service or benefit","10–13 sec: Interior or strongest proof point",`13–15 sec: CTA — Call/WhatsApp 7015260003 • ROHILLA DRIVE`];setOrganic({caption,hook,reel,vehicleUrl:c?`${window.location.origin}/cars/${c.id}`:window.location.origin});setMsg("Promotion content pack prepared. Review it before publishing.")}
 async function copyOrganic(){if(!organic)return;await navigator.clipboard.writeText(organic.caption);setMsg("Caption and hashtags copied.")}
 async function shareOrganic(){if(!organic)return;try{if(navigator.share){await navigator.share({title:"ROHILLA DRIVE",text:organic.caption,url:organic.vehicleUrl});return}await navigator.clipboard.writeText(`${organic.caption}\n${organic.vehicleUrl}`);setMsg("Content pack copied. Open the required publishing app and review it before posting.")}catch{}}
 function whatsappOrganic(){if(!organic)return;window.open(`https://wa.me/?text=${encodeURIComponent(`${organic.caption}\n${organic.vehicleUrl}`)}`,"_blank")}
 function trackedLeadUrl(source:string,intent:"buy"|"sell"="buy"){const params=new URLSearchParams({utm_source:source,utm_medium:"organic",utm_campaign:intent==="sell"?"ambala_sell_car":"ambala_used_car_leads"});if(intent==="sell")params.set("intent","sell");return `https://www.rohilladrive.com/find-car-ambala?${params.toString()}`}
 async function copyTrackedLink(source:string,intent:"buy"|"sell"="buy"){const url=trackedLeadUrl(source,intent);await navigator.clipboard.writeText(url);setMsg(`${source.replace(/_/g," ")} ${intent} link copied. Leads from this URL will keep their source label.`)}
 const attributionLinks=[["Google Business Profile","google_business_profile"],["Justdial","justdial"],["Instagram","instagram"],["Facebook","facebook"],["YouTube","youtube"],["WhatsApp Status","whatsapp_status"]] as const;
 if(checking)return <main><section className="section"><h1>{title}</h1><p>Checking secure access…</p></section></main>;
 if(!authorised)return <main><section className="section"><h1>{title}</h1><p>{msg}</p><a className="call" href={homeHref}>Back to Dashboard</a></section></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE</b><small>{title}</small></div><div className="row"><a className="call" href={homeHref}>Back to Dashboard</a></div></header><section className="hero"><div className="heroText"><span>CONTENT PLANNING • PRIVACY • REVIEW • DISTRIBUTION</span><h1>Marketing & Content Workspace</h1><p>Prepare vehicle and business content, review privacy and factual accuracy, localise it for selected languages and organise approved distribution.</p></div></section>
 <section className="section"><h2>Promotion Content Pack</h2><p>Select a vehicle or enter a brief to prepare a caption, hashtags and a short-form video shot plan for manual review and publishing.</p>{actorRole!=="partner"&&<select value={vehicle} onChange={e=>{setVehicle(e.target.value);setOrganic(null)}}><option value="">Choose vehicle (optional for a general brief)</option>{cars.map(c=><option key={c.id} value={c.id}>{c.year||""} {c.brand} {c.model} {c.variant||""} • {statusLabel(c.status)}</option>)}</select>}<textarea style={{width:"100%",minHeight:90,marginTop:10}} placeholder="Optional content brief: key features, ownership, offer, fuel type, transmission or condition" value={command} onChange={e=>setCommand(e.target.value)}/><div className="row" style={{marginTop:10}}><button onClick={buildOrganic}>Generate Content Pack</button>{organic&&<><button className="secondary" onClick={copyOrganic}>Copy Caption</button><button className="secondary" onClick={shareOrganic}>Share</button><button className="secondary" onClick={whatsappOrganic}>Share on WhatsApp</button></>}</div>{organic&&<div className="card" style={{marginTop:14}}><div className="body"><h3>Caption & Hashtags</h3><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",fontSize:13}}>{organic.caption}</pre><h3>15-Second Video Shot Plan</h3>{organic.reel.map((x:string)=><p key={x} style={{margin:"5px 0"}}>• {x}</p>)}<small>Distribution results vary by platform, audience and content performance. Review all facts, prices and permissions before publishing.</small></div></div>}{msg&&<div className="notice">{msg}</div>}</section>
 {actorRole==="admin"&&<section className="section"><h2>Organic Lead Performance</h2><p>Source attribution is read from genuine enquiries only. No test or fake leads are included.</p><div className="notice" style={{marginBottom:14}}><b>Zero-spend rule:</b> paid advertising remains locked until at least one genuine lead exists, and any later paid spend still requires explicit owner approval.</div>{sourceStats.length===0?<div className="card"><div className="body"><h3>No genuine leads yet</h3><p>Keep the free organic links active across Google Business Profile, Justdial and social profiles. Once the first enquiry arrives, this section will show which source produced it.</p></div></div>:<div className="grid">{sourceStats.map(row=><article className="application" key={row.source}><label>{statusLabel(row.source)}</label><h3>{row.total} lead{row.total===1?"":"s"}</h3><p>{row.buy} buyer • {row.sell} seller • {row.newCount} new</p></article>)}</div>}</section>}
 {actorRole==="admin"&&<section className="section"><h2>Trackable Lead Links</h2><p>Use these exact links in external business profiles, social bios, posts and listings. Buyer and seller enquiries are saved with a source label so the Administration Console can show which channel produced the lead.</p><div className="grid">{attributionLinks.map(([label,source])=><article className="application" key={source}><label>{label}</label><h3>Ambala Buyer Link</h3><p style={{fontSize:12,wordBreak:"break-all"}}>{trackedLeadUrl(source,"buy")}</p><div className="row"><button onClick={()=>copyTrackedLink(source,"buy")}>Copy Buyer Link</button><a className="secondary" href={trackedLeadUrl(source,"buy")} target="_blank" rel="noreferrer">Open</a></div><h3 style={{marginTop:14}}>Ambala Seller Link</h3><p style={{fontSize:12,wordBreak:"break-all"}}>{trackedLeadUrl(source,"sell")}</p><div className="row"><button onClick={()=>copyTrackedLink(source,"sell")}>Copy Seller Link</button><a className="secondary" href={trackedLeadUrl(source,"sell")} target="_blank" rel="noreferrer">Open</a></div></article>)}</div><div className="notice" style={{marginTop:14}}><b>Recommended profile destination:</b> use the Buyer Link as the main website/action URL on discovery profiles. Use the Seller Link in posts or sections specifically promoting car selling. Do not create duplicate or misleading business profiles.</div></section>}
 <section className="section"><h2>Marketing Workflow</h2><div className="grid">{PIPELINE.map(([n,name,desc])=><article className="application" key={n}><label>Stage {n}</label><h3>{name}</h3><p>{desc}</p></article>)}</div></section><section className="section"><h1>Campaign Planning Queue</h1><p>Record a marketing brief for future execution across approved channels. External publishing and advertising remain subject to separate authorisation and budget controls.</p>{actorRole!=="partner"&&<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">No specific vehicle</option>{cars.map(c=><option key={c.id} value={c.id}>{c.year||""} {c.brand} {c.model} {c.variant||""}</option>)}</select>}<textarea style={{width:"100%",minHeight:130,marginTop:12}} placeholder="Describe the campaign objective, audience and content requirements…" value={command} onChange={e=>setCommand(e.target.value)}/><div className="row" style={{marginTop:10}}><button onClick={voice}>{listening?"Listening…":"Voice Input"}</button>{["website","instagram","facebook","youtube","whatsapp_draft","google_ads","seo"].map(ch=>{const locked=ch==="google_ads"&&!hasGenuineLead;return <button key={ch} disabled={locked} title={locked?"Locked until first genuine lead":undefined} className={channels.includes(ch)?"filter active":"filter"} onClick={()=>!locked&&toggle(ch)}>{locked?"Google Ads Locked — First Lead Needed":ch.replace(/_/g," ").replace(/\b\w/g,x=>x.toUpperCase())}</button>})}</div><h3>Content Languages</h3><div className="row">{ROHILLA_LANGUAGES.map(l=><button key={l.code} className={contentLangs.includes(l.code)?"filter active":"filter"} onClick={()=>toggleLang(l.code)}>{l.nativeName}</button>)}</div><button style={{marginTop:12}} onClick={queue} disabled={!command.trim()||contentLangs.length===0}>Add to Planning Queue</button></section><section className="section"><h2>Planning Queue</h2>{jobs.length===0?<p>No campaign plans have been queued.</p>:<div className="grid">{jobs.map(j=><article className="application" key={j.id}><label>{statusLabel(j.status)}</label><h3>Marketing Plan</h3><p>{j.command}</p><small>{Array.isArray(j.channels)?j.channels.join(" • "):""} • {new Date(j.created_at).toLocaleString("en-IN")}</small></article>)}</div>}</section><section className="section dark"><div className="about"><h2>Distribution Policy</h2><p>Content can be prepared and reviewed inside ROHILLA DRIVE. Publishing to Instagram, Facebook, YouTube, advertising platforms or other external services requires the relevant account authorisation and permissions; those controls are not bypassed by the workspace.</p></div></section></main>
}
