"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../supabaseClient";
import {LANGUAGE_STORAGE_KEY,ROHILLA_LANGUAGES,languageByCode} from "../lib/rohilla-languages";

declare global {interface Window{webkitSpeechRecognition?:any;SpeechRecognition?:any}}

const PIPELINE=[
 ["1","Understand","Intent, vehicle, offer and audience"],
 ["2","Privacy","Plate/phone/private data rules"],
 ["3","Create","Photos, posters, reels, copy"],
 ["4","Localize","Language + region variants"],
 ["5","Quality Gate","Brand, facts, pricing, permissions"],
 ["6","Distribute","Website/social/ad drafts or approved publish"],
 ["7","Measure","Views, leads, CPL, conversion"],
 ["8","Learn","Feed results into next recommendation"]
] as const;

const clean=(v:any)=>String(v||"").replace(/\s+/g," ").trim();
function hashtags(car:any){const bits=["RohillaDrive","RohillaMultibrandCars","UsedCars","CarForSale","BuyCar","SellCar",clean(car?.brand).replace(/[^a-z0-9]/gi,""),clean(car?.model).replace(/[^a-z0-9]/gi,""),clean(car?.city||"AmbalaCity").replace(/[^a-z0-9]/gi,"")].filter(Boolean);return [...new Set(bits)].map(x=>`#${x}`).join(" ")}

export default function GrowthConsole({actorRole,title,homeHref}:{actorRole:"admin"|"dealer"|"partner";title:string;homeHref:string}){
 const db=supabase();const [session,setSession]=useState<any>(null);const [authorized,setAuthorized]=useState(false);const [checking,setChecking]=useState(true);const [command,setCommand]=useState("");const [jobs,setJobs]=useState<any[]>([]);const [cars,setCars]=useState<any[]>([]);const [vehicle,setVehicle]=useState("");const [channels,setChannels]=useState<string[]>(["website","instagram","facebook","youtube","seo"]);const [contentLangs,setContentLangs]=useState<string[]>(["en-IN","hi-IN"]);const [operatorLang,setOperatorLang]=useState("hi-IN");const [msg,setMsg]=useState("");const [listening,setListening]=useState(false);const [organic,setOrganic]=useState<any>(null);
 useEffect(()=>{setOperatorLang(localStorage.getItem(LANGUAGE_STORAGE_KEY)||"hi-IN");(async()=>{const {data:{session}}=await db.auth.getSession();setSession(session);if(!session){setMsg(`${actorRole==="partner"?"Business Hub":actorRole} login required.`);setChecking(false);return}if(actorRole==="admin"){const [{data:aal},{data:isAdmin}]=await Promise.all([db.auth.mfa.getAuthenticatorAssuranceLevel(),db.rpc("is_admin")]);if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Admin + Authenticator verification required.");setChecking(false);return}}else{const {data:p}=await db.from("profiles").select("role,active").eq("id",session.user.id).single();if(!p||p.role!==actorRole||!p.active){setMsg(`Approved ${actorRole==="partner"?"Business Hub Partner":"Dealer"} access required.`);setChecking(false);return}}setAuthorized(true);setChecking(false);await load(session.user.id)})()},[]);
 async function load(uid?:string){const userId=uid||session?.user?.id;if(!userId)return;let q=db.from("automation_jobs").select("*").order("created_at",{ascending:false}).limit(30);if(actorRole!=="admin")q=q.eq("created_by",userId);const {data,error}=await q;if(error){setMsg(error.message);return}setJobs(data||[]);if(actorRole==="dealer"){const {data:v}=await db.from("vehicles").select("id,brand,model,variant,year,km,fuel,asking_price,city,status,vehicle_photos(url,sort_order)").eq("partner_id",userId).order("created_at",{ascending:false});setCars(v||[])}else if(actorRole==="admin"){const {data:v}=await db.from("vehicles").select("id,brand,model,variant,year,km,fuel,asking_price,city,status,vehicle_photos(url,sort_order)").order("created_at",{ascending:false}).limit(150);setCars(v||[])}}
 function toggle(ch:string){setChannels(x=>x.includes(ch)?x.filter(y=>y!==ch):[...x,ch])}
 function toggleLang(code:string){setContentLangs(x=>x.includes(code)?x.filter(y=>y!==code):[...x,code])}
 function structured(text:string){const t=text.toLowerCase();return {hide_plate:/hide.*(number|plate)|number.*hide|plate.*hide/.test(t),keep_plate:/show.*(number|plate)|number.*show/.test(t),multiple_creatives:/multiple|different photo|several|3 photo|4 photo|5 photo/.test(t),poster:/poster|creative|ad image/.test(t),reel:/reel|short|video/.test(t),publish:/post|publish|upload|social/.test(t),seo:/google|seo|search/.test(t),ads:/adword|google ad|ads campaign/.test(t),lead_followup:/follow.?up|lead|customer reply|whatsapp/.test(t),new_vehicle:/new vehicle|new car|oem|showroom|dealer quote/.test(t),language:/punjabi|kannada|tamil|telugu|malayalam|marathi|gujarati|bengali|hindi|english/.test(t)?"multilingual":"auto"}}
 function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMsg("Voice recognition is not available in this browser. Type the same command instead.");return}const r=new SR();r.lang=languageByCode(operatorLang).speechCode;r.interimResults=false;r.continuous=false;setListening(true);r.onresult=(e:any)=>{setCommand((old:string)=>[old,e.results?.[0]?.[0]?.transcript||""].filter(Boolean).join(" "));setListening(false)};r.onerror=()=>{setListening(false);setMsg("Voice capture stopped. You can type the command.")};r.onend=()=>setListening(false);r.start()}
 async function queue(){if(!session||!authorized||!command.trim())return;setMsg("Creating Rohilla Intelligence V2 command…");const intent=structured(command);const payload={pipeline_version:2,intent,requested_channels:channels,target_languages:contentLangs,operator_language:operatorLang,portal:actorRole,pipeline:PIPELINE.map(([step,name])=>({step,name,status:"planned"})),guardrails:{external_publish:"requires official connection and permission",ad_spend:"requires Admin budget rule",private_data:"never expose private customer/vehicle fields",plate_rule:intent.hide_plate?"mask requested":intent.keep_plate?"show requested":"follow account/default policy",fact_check:"vehicle facts and prices must be verified before distribution"}};const {error}=await db.from("automation_jobs").insert({created_by:session.user.id,actor_role:actorRole,job_type:"rohilla_intelligence_v2",command:command.trim(),channels,source_vehicle_id:vehicle||null,payload,status:"queued"});if(error){setMsg(error.message);return}setCommand("");setMsg("Rohilla Intelligence V2 command queued ✓ Multi-layer plan, language targets and safety gates are attached.");await load()}
 const selectedCar=useMemo(()=>cars.find(c=>c.id===vehicle)||null,[cars,vehicle]);
 function buildOrganic(){const c=selectedCar;if(!c&&!command.trim()){setMsg("Choose a vehicle or type a promotion brief first.");return}const vehicleLine=c?`${c.year||""} ${c.brand||""} ${c.model||""} ${c.variant||""}`.replace(/\s+/g," ").trim():"ROHILLA DRIVE automotive update";const spec=c?[c.fuel,c.km?`${Number(c.km).toLocaleString("en-IN")} km`:"",c.city].filter(Boolean).join(" • "):"";const price=c?.asking_price?`₹${Number(c.asking_price).toLocaleString("en-IN")}`:"Price / details on request";const caption=[`🚘 ${vehicleLine}`,spec,`💰 ${price}`,command.trim()?`✨ ${command.trim()}`:"",`📍 ${c?.city||"Ambala City"}`,"📞 7015260003","ROHILLA DRIVE — One network. Every vehicle. Every language.",hashtags(c)].filter(Boolean).join("\n");const hook=c?`${c.year||""} ${c.brand} ${c.model} — worth checking before it’s gone.`:"One network for the complete vehicle journey.";const reel=[`0–2 sec: ${hook}`,"2–6 sec: Front + side walk-around",c?`6–10 sec: Show ${spec||"key condition/features"}`:"6–10 sec: Show the main service / benefit","10–13 sec: Interior / strongest proof point",`13–15 sec: CTA — Call/WhatsApp 7015260003 • Rohilla Drive`];setOrganic({caption,hook,reel,vehicleUrl:c?`${window.location.origin}/cars/${c.id}`:window.location.origin});setMsg("Free Organic Promotion Pack ready ✓ No AI API or ad spend used.")}
 async function copyOrganic(){if(!organic)return;await navigator.clipboard.writeText(organic.caption);setMsg("Caption + hashtags copied ✓")}
 async function shareOrganic(){if(!organic)return;try{if(navigator.share){await navigator.share({title:"ROHILLA DRIVE",text:organic.caption,url:organic.vehicleUrl});return}await navigator.clipboard.writeText(`${organic.caption}\n${organic.vehicleUrl}`);setMsg("Promotion pack copied ✓ Open Instagram/Facebook/YouTube and paste it.")}catch{}}
 function whatsappOrganic(){if(!organic)return;window.open(`https://wa.me/?text=${encodeURIComponent(`${organic.caption}\n${organic.vehicleUrl}`)}`,"_blank")}
 if(checking)return <main><section className="section"><h1>ROHILLA INTELLIGENCE</h1><p>Checking secure access…</p></section></main>;
 if(!authorized)return <main><section className="section"><h1>ROHILLA INTELLIGENCE</h1><p>{msg}</p><a className="call" href={homeHref}>Back</a></section></main>;
 return <main><header><div className="brand"><b>ROHILLA INTELLIGENCE V2</b><small>{title}</small></div><div className="row"><a className="call" href={homeHref}>Back</a></div></header><section className="hero"><div className="heroText"><span>ROHILLA-OWNED WORKFLOWS • ZERO-COST ORGANIC MODE</span><h1>One command. A controlled growth pipeline.</h1><p>Prepare organic promotion packs now without paid AI or ads. Official auto-publishing stays optional for later.</p></div></section>
 <section className="section"><h2>Free Organic Promotion Pack</h2><p>This works now without Meta/YouTube API access: select a vehicle, generate verified caption + hashtags + reel shot plan, then use Android/iPhone Share or copy it into the native apps.</p>{actorRole!=="partner"&&<select value={vehicle} onChange={e=>{setVehicle(e.target.value);setOrganic(null)}}><option value="">Choose vehicle (optional if writing a general brief)</option>{cars.map(c=><option key={c.id} value={c.id}>{c.year||""} {c.brand} {c.model} {c.variant||""} • {c.status}</option>)}</select>}<textarea style={{width:"100%",minHeight:90,marginTop:10}} placeholder="Optional promotion brief: sunroof highlight, first owner, Rakhi offer, diesel automatic, etc." value={command} onChange={e=>setCommand(e.target.value)}/><div className="row" style={{marginTop:10}}><button onClick={buildOrganic}>Build Free Promotion Pack</button>{organic&&<><button className="secondary" onClick={copyOrganic}>Copy Caption</button><button className="secondary" onClick={shareOrganic}>📤 Share</button><button className="secondary" onClick={whatsappOrganic}>WhatsApp Share</button></>}</div>{organic&&<div className="card" style={{marginTop:14}}><div className="body"><h3>Caption + Hashtags</h3><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",fontSize:13}}>{organic.caption}</pre><h3>15-sec Reel Shot Plan</h3>{organic.reel.map((x:string)=><p key={x} style={{margin:"5px 0"}}>• {x}</p>)}<small>Organic reach cannot be guaranteed by code; hooks, real inventory, regular posting, shares, saves and audience response influence distribution on each platform.</small></div></div>}{msg&&<div className="notice">{msg}</div>}</section>
 <section className="section"><h2>8-layer execution model</h2><div className="grid">{PIPELINE.map(([n,name,desc])=><article className="application" key={n}><label>Layer {n}</label><h3>{name}</h3><p>{desc}</p></article>)}</div></section><section className="section"><h1>Advanced Voice / Text Growth Command</h1><p>Use this queue for future automation planning. Paid ads and external publishing remain disabled unless explicitly authorised later.</p>{actorRole!=="partner"&&<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">No specific vehicle</option>{cars.map(c=><option key={c.id} value={c.id}>{c.year||""} {c.brand} {c.model} {c.variant||""}</option>)}</select>}<textarea style={{width:"100%",minHeight:130,marginTop:12}} placeholder="Speak or type the outcome you want…" value={command} onChange={e=>setCommand(e.target.value)}/><div className="row" style={{marginTop:10}}><button onClick={voice}>{listening?"🎙️ Listening…":"🎙️ Speak Command"}</button>{["website","instagram","facebook","youtube","whatsapp_draft","google_ads","seo"].map(ch=><button key={ch} className={channels.includes(ch)?"filter active":"filter"} onClick={()=>toggle(ch)}>{ch.replace(/_/g," ")}</button>)}</div><h3>Content languages</h3><div className="row">{ROHILLA_LANGUAGES.map(l=><button key={l.code} className={contentLangs.includes(l.code)?"filter active":"filter"} onClick={()=>toggleLang(l.code)}>{l.nativeName}</button>)}</div><button style={{marginTop:12}} onClick={queue} disabled={!command.trim()||contentLangs.length===0}>Queue V2 Command</button></section><section className="section"><h2>My Growth Queue</h2>{jobs.length===0?<p>No commands yet.</p>:<div className="grid">{jobs.map(j=><article className="application" key={j.id}><label>{j.status}</label><h3>{j.job_type.replace(/_/g," ")}</h3><p>{j.command}</p><small>{Array.isArray(j.channels)?j.channels.join(" • "):""} • {new Date(j.created_at).toLocaleString()}</small></article>)}</div>}</section><section className="section dark"><div className="about"><h2>Distribution rule</h2><p>Rohilla can prepare links, captions, hashtags, reel plans, SEO and share packs itself. Automatic Instagram/Facebook/YouTube publishing still requires those platforms to authorise the Rohilla account; no code can legitimately bypass their login or publishing permissions.</p></div></section></main>
}
