"use client";
import {useState} from "react";
import {supabase} from "../supabaseClient";
import LegalConsent from "./LegalConsent";

const categories=["Workshop / Repairs","Car Inspection","Finance DSA","Insurance","RC / RTO Assistance","Car Detailing","Roadside Assistance","Self-Drive Car Rental","Taxi / Cab Service","Chauffeur Service","Fleet / Corporate Mobility","Vehicle Delivery / Logistics","EV Services","Tyres / Battery","Registered Vehicle Scrapping Facility (RVSF)","Local Vehicle Recycler / Scrap Buyer","Other Automobile Service"];
export default function PartnerJoinForm({defaultCategory=""}:{defaultCategory?:string}){
 const db=supabase();const [category,setCategory]=useState(categories.includes(defaultCategory)?defaultCategory:"");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 async function signup(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("Creating account…");const x=new FormData(e.currentTarget);const name=String(x.get("name")),mobile=String(x.get("mobile")),business=String(x.get("business_name")),city=String(x.get("city")),address=String(x.get("address")),email=String(x.get("email")),password=String(x.get("password"));const {data,error}=await db.auth.signUp({email,password,options:{data:{network_role:"partner",name,phone:mobile,business_name:business,address,city,service_categories:category}}});if(error){setBusy(false);setMsg(error.message);return}if(!data.user){setBusy(false);setMsg("Account could not be created.");return}const {error:appError}=await db.from("collaboration_requests").insert({applicant_user_id:data.user.id,request_type:"partner",business_name:business,contact:name+" • "+mobile,category,city,message:[`Address: ${address}`,String(x.get("message")||"")].filter(Boolean).join("\n")});setBusy(false);if(appError){setMsg(appError.message);return}setMsg("Application submitted. ROHILLA DRIVE will review your account. You can sign in to the Partner Workspace after approval.")}
 return <main><header><div className="brand"><b>ROHILLA DRIVE</b><small>Service / Business Partner Registration</small></div><div className="row"><a className="call" href="/partner">Partner Workspace Sign In</a><a className="call" href="/business-hub">Business Hub</a></div></header><section className="hero"><div className="heroText"><span>DIRECT BUSINESS HUB REGISTRATION</span><h1>Join ROHILLA DRIVE as a Service / Mobility Partner</h1><p>Automotive businesses can apply directly. Approval activates only the relevant ROHILLA DRIVE workflow and does not replace any licence, registration, government approval or professional authorisation required for your activity.</p></div></section><section className="section"><div className="notice"><b>Regulated activities:</b> Finance, insurance, RC/RTO work, passenger or commercial mobility, RVSF and other regulated categories must be performed only by appropriately authorised or licensed persons or businesses. A local recycler or scrap buyer must not describe itself as a registered RVSF unless it holds the required registration.</div><form className="adminForm" onSubmit={signup}><input name="name" placeholder="Contact Name" required/><input name="business_name" placeholder="Business Name" required/><input name="mobile" placeholder="Mobile Number" required/><input name="email" type="email" placeholder="Email Address" required/><input name="password" type="password" minLength={6} placeholder="Create Password" required/><select value={category} onChange={e=>setCategory(e.target.value)} required><option value="" disabled>Select Business Category</option>{categories.map(x=><option key={x} value={x}>{x}</option>)}</select><input name="city" placeholder="City / Service Area" required/><input name="address" placeholder="Business Address" required/><textarea name="message" placeholder="Services, experience, coverage and any licence, registration or authorisation details"/><LegalConsent regulated/><button disabled={busy}>{busy?"Submitting…":"Create Account & Submit for Approval"}</button></form>{msg&&<div className="notice">{msg}</div>}<div className="notice">Already registered? <a href="/partner"><b>Sign In to Partner Workspace →</b></a></div></section></main>
}
