"use client";
import {useEffect,useState} from "react";
import {supabase} from "../supabaseClient";

async function translate(text:string,target:string,source:string){try{const r=await fetch("/api/translate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,target,source})});const j=await r.json();return {text:j?.translations?.[0]||text,configured:Boolean(j?.configured)}}catch{return {text,configured:false}}}

export default function ParticipantDealRooms({actorRole,homeHref}:{actorRole:"dealer"|"partner";homeHref:string}){
 const db=supabase();const [session,setSession]=useState<any>(null);const [ready,setReady]=useState(false);const [rooms,setRooms]=useState<any[]>([]);const [active,setActive]=useState<any>(null);const [tasks,setTasks]=useState<any[]>([]);const [messages,setMessages]=useState<any[]>([]);const [reply,setReply]=useState("");const [msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Login required.");return}const {data:p}=await db.from("profiles").select("role,active").eq("id",session.user.id).single();if(!p||p.role!==actorRole||!p.active){setMsg(`Approved ${actorRole==="dealer"?"Dealer":"Partner"} access is required.`);return}setSession(session);setReady(true);await loadRooms()})()},[]);
 async function loadRooms(){const {data:parts,error}=await db.from("deal_room_participants").select("room_id,participant_role").eq("user_id",(await db.auth.getUser()).data.user?.id).eq("active",true);if(error){setMsg(error.message);return}const ids=(parts||[]).map((x:any)=>x.room_id);if(!ids.length){setRooms([]);return}const {data,error:rerr}=await db.from("deal_rooms").select("id,title,status,customer_language,operator_language,customer_city,vehicle_city,created_at").in("id",ids).order("created_at",{ascending:false});if(rerr){setMsg(rerr.message);return}setRooms(data||[])}
 async function openRoom(room:any){setActive(room);const [a,b]=await Promise.all([db.from("deal_room_tasks").select("id,title,status,position,note").eq("room_id",room.id).order("position"),db.from("deal_room_messages").select("id,sender_role,source_language,original_text,operator_text,customer_text,translation_status,created_at").eq("room_id",room.id).order("created_at")]);if(a.error){setMsg(a.error.message);return}if(b.error){setMsg(b.error.message);return}setTasks(a.data||[]);setMessages(b.data||[])}
 async function send(e:React.FormEvent){e.preventDefault();if(!reply.trim()||!session||!active)return;const source=active.operator_language||"hi-IN";const target=active.customer_language||"en-IN";const x=source===target?{text:reply,configured:true}:await translate(reply,target,source);const {error}=await db.from("deal_room_messages").insert({room_id:active.id,sender_role:actorRole,sender_user_id:session.user.id,source_language:source,original_text:reply.trim(),operator_text:reply.trim(),customer_text:x.text,translation_status:x.configured?"ready":"pending"});if(error){setMsg(error.message);return}setReply("");setMsg(x.configured?"Message added to the deal workspace.":"Message saved. Translation provider connection is pending.");await openRoom(active)}
 if(!ready)return <main><section className="section"><div className="portalSectionLabel">Deal Management</div><h1>Secure access check</h1><p>{msg||"Verifying account permissions…"}</p><a className="call" href={homeHref}>Return to portal</a></section></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE</b><small>{actorRole==="dealer"?"Dealer Deal Management":"Partner Deal Management"}</small></div><a className="call" href={homeHref}>Portal Home</a></header><section className="section"><div className="portalSectionLabel">Assigned Transactions</div><h1>Authorised Deal Workspaces</h1><p>Only transactions where Rohilla Drive has explicitly added your business are visible in this area.</p>{rooms.length===0?<div className="notice">No deal workspace is currently assigned to your account.</div>:<div className="grid">{rooms.map(r=><article className="application" key={r.id}><label>{r.status}</label><h3>{r.title}</h3><p>{r.customer_city||"Customer location"} → {r.vehicle_city||"Vehicle location"}</p><button onClick={()=>openRoom(r)}>Open Workspace</button></article>)}</div>}</section>{active&&<section className="section"><div className="portalSectionLabel">Transaction Workspace</div><h2>{active.title}</h2><p>Customer contact remains protected. Communication and workflow updates should be coordinated through this authorised workspace.</p><h3>Workflow Status</h3><div className="grid">{tasks.map(t=><article className="application" key={t.id}><label>{t.status}</label><h3>{t.title}</h3>{t.note&&<p>{t.note}</p>}</article>)}</div><h3>Communication Log</h3><div className="request-list">{messages.map(m=><article className="request-card" key={m.id}><div className="request-top"><b>{m.sender_role}</b><small>{new Date(m.created_at).toLocaleString()}</small></div><p>{m.operator_text||m.original_text}</p></article>)}</div><form className="adminForm" onSubmit={send}><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder={`Reply in ${active.operator_language||"your working language"}. Customer translation is prepared when the approved translation provider is connected.`}/><button disabled={!reply.trim()}>Add Message</button></form>{msg&&<div className="notice">{msg}</div>}</section>}</main>
}
