"use client";
import {useEffect,useState} from "react";
import {supabase} from "../supabaseClient";
import CustomerBackBar from "./CustomerBackBar";

export default function PublicDealRoom({token}:{token:string}){
 const db=supabase();const [room,setRoom]=useState<any>(null);const [loading,setLoading]=useState(true);const [text,setText]=useState("");const [msg,setMsg]=useState("");const [sending,setSending]=useState(false);
 useEffect(()=>{load()},[token]);
 async function load(){setLoading(true);const {data,error}=await db.rpc("get_public_deal_room",{p_token:token});setLoading(false);if(error){setMsg(error.message);return}setRoom(data)}
 async function send(e:React.FormEvent){e.preventDefault();if(!text.trim())return;setSending(true);const {error}=await db.rpc("post_public_deal_message",{p_token:token,p_text:text.trim(),p_language:"en-IN"});setSending(false);if(error){setMsg(error.message);return}setText("");setMsg("Message sent ✓ Rohilla Drive will see it in the Deal Room.");await load()}
 if(loading)return <main><CustomerBackBar/><section className="section"><h2>Opening Rohilla Deal Room…</h2></section></main>;
 if(!room)return <main><CustomerBackBar/><section className="section"><h1>Deal Room not available</h1><p>This link may be invalid, closed or no longer active.</p></section></main>;
 const tasks=room.tasks||[],messages=room.messages||[];const done=tasks.filter((x:any)=>x.status==="completed").length;
 return <main><CustomerBackBar/><header><div className="brand"><b>ROHILLA DRIVE</b><small>Private Deal Room</small></div><button className="call" onClick={load}>Refresh</button></header><section className="hero"><div className="heroText"><span>VERIFY • DOCUMENT • TRANSPORT • DELIVER</span><h1>{room.title}</h1><p>{room.customer_city||"Customer location"} → {room.vehicle_city||"Vehicle location"} • Status: <b>{String(room.status).replace(/_/g," ")}</b></p><p><b>{done}/{tasks.length}</b> journey steps completed.</p></div></section><section className="section"><h2>Deal Journey</h2><div className="grid">{tasks.map((t:any)=><article className="application" key={t.id}><label>{t.status.replace(/_/g," ")}</label><h3>{t.title}</h3>{t.note&&<p>{t.note}</p>}</article>)}</div></section><section className="section"><h2>Messages</h2><div className="request-list">{messages.length===0?<p>No messages yet.</p>:messages.map((m:any)=><article className="request-card" key={m.id}><div className="request-top"><b>{m.sender_role==="customer"?"You":"Rohilla Drive"}</b><small>{new Date(m.created_at).toLocaleString()}</small></div><p style={{whiteSpace:"pre-wrap"}}>{m.text}</p></article>)}</div><form className="adminForm" onSubmit={send}><textarea required value={text} onChange={e=>setText(e.target.value)} placeholder="Message Rohilla Drive…"/><button disabled={sending}>{sending?"Sending…":"Send Message"}</button></form>{msg&&<div className="notice">{msg}</div>}</section><section className="section dark"><div className="about"><h2>One deal, one timeline.</h2><p>Inspection, documents, commercial terms, transport and delivery stay visible in one Rohilla Drive journey. Customer contact and partner access remain controlled.</p></div></section></main>
}
