"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../supabaseClient";

const statusLabel=(s:any)=>String(s||"").replace(/_/g," ").replace(/\b\w/g,x=>x.toUpperCase());
export default function AdminVerification(){
 const db=supabase(); const [session,setSession]=useState<any>(null); const [rows,setRows]=useState<any[]>([]); const [msg,setMsg]=useState("Checking administrator access…");
 async function load(){const {data,error}=await db.from("vehicle_verification_orders").select("*").order("created_at",{ascending:false});if(error){setMsg(error.message);return}setRows(data||[]);setMsg("")}
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Administrator sign-in is required.");return}const [{data:aal},{data:isAdmin}]=await Promise.all([db.auth.mfa.getAuthenticatorAssuranceLevel(),db.rpc("is_admin")]);if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Administrator authentication is required.");return}setSession(session);await load()})()},[]);
 async function setStatus(id:string,status:string){const {error}=await db.from("vehicle_verification_orders").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)setMsg(error.message);else{setMsg(`Verification status updated to ${statusLabel(status)}.`);await load()}}
 if(!session)return <main><div className="auth"><h1>Verification Operations</h1><p>{msg}</p><a className="call" href="/admin">Back to Dashboard</a></div></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE</b><small>Verification Operations</small></div><a className="call" href="/admin">Back to Dashboard</a></header><section className="section"><h1>Vehicle Verification Requests</h1><p>Record results only from legitimate authorised sources and supported customer-assisted workflows. Government portals, CAPTCHA, OTP and other access controls must not be bypassed.</p>{msg&&<p>{msg}</p>}{rows.length===0?<div className="card"><div className="body"><h3>No Verification Requests</h3><p>Customer requests submitted through the verification workflow will appear here.</p></div></div>:<div className="grid">{rows.map(r=><article className="card" key={r.id}><div className="body"><label>{statusLabel(r.status)}</label><h3>{r.vehicle_number}</h3><p>{r.customer_name||"Customer"} • {r.customer_phone}</p><p>Requested: {new Date(r.created_at).toLocaleString("en-IN")}</p><p>Payment: <b>{statusLabel(r.payment_status)}</b> • Service Fee: ₹{Number(r.service_fee||0).toLocaleString("en-IN")}</p><p>Government Fee: ₹{Number(r.government_fee||0).toLocaleString("en-IN")}</p><p>Report: {r.report_url?<a href={r.report_url} target="_blank" rel="noreferrer">Open Report</a>:"Not Generated"}</p><div className="row"><button onClick={()=>setStatus(r.id,"processing")}>Mark as Processing</button><button onClick={()=>setStatus(r.id,"needs_documents")}>Request Documents</button><button onClick={()=>setStatus(r.id,"completed")}>Mark Complete</button></div></div></article>)}</div>}</section><section className="section dark"><div className="about"><h2>Official Resources</h2><p>Use authorised access only. ROHILLA DRIVE is not a government authority and does not issue government certificates or official transport records.</p><div className="row"><a className="call" href="https://echallan.parivahan.gov.in/" target="_blank" rel="noreferrer">eChallan</a><a className="call" href="https://parivahan.gov.in/" target="_blank" rel="noreferrer">Parivahan</a></div></div></section></main>
}
