"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../supabaseClient";

export default function AdminVerification(){
 const db=supabase(); const [ready,setReady]=useState(false); const [rows,setRows]=useState<any[]>([]); const [msg,setMsg]=useState("Checking Admin access…");
 async function load(){const {data,error}=await db.from("vehicle_verification_orders").select("*").order("created_at",{ascending:false});if(error){setMsg(error.message);return}setRows(data||[]);setMsg("")}
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Admin login required.");return}const [{data:aal},{data:isAdmin}]=await Promise.all([db.auth.mfa.getAuthenticatorAssuranceLevel(),db.rpc("is_admin")]);if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Admin Authenticator verification is required. Open Operations first.");return}setReady(true);await load()})()},[]);
 async function setStatus(id:string,status:string){const {error}=await db.from("vehicle_verification_orders").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)setMsg(error.message);else{setMsg(`Verification status updated to ${status}.`);load()}}
 if(!ready)return <main><div className="auth"><h1>Vehicle Verification</h1><p>{msg}</p><a className="call" href="/admin">Open Admin Operations</a></div></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE</b><small>Admin Vehicle Verification</small></div><a className="call" href="/admin">Operations</a></header><section className="section"><h1>Vehicle Verification Requests</h1><p>Record verification results only from lawful, authorised or customer-assisted sources. Official portal security, authentication and access controls must always be respected.</p>{msg&&<div className="notice">{msg}</div>}{rows.length===0?<div className="card"><div className="body"><h3>No verification requests</h3><p>Customer requests submitted through the vehicle verification page will appear here.</p></div></div>:<div className="grid">{rows.map(r=><article className="card" key={r.id}><div className="body"><label>{r.status}</label><h3>{r.vehicle_number}</h3><p>{r.customer_name||"Customer"} • {r.customer_phone}</p><p>Requested: {new Date(r.created_at).toLocaleString("en-IN")}</p><p>Payment: <b>{r.payment_status}</b> • Rohilla Drive service fee: ₹{Number(r.service_fee||0).toLocaleString("en-IN")}</p><p>Government / official fee: ₹{Number(r.government_fee||0).toLocaleString("en-IN")}</p><p>Report: {r.report_url?<a href={r.report_url} target="_blank">Open Report</a>:"Not available yet"}</p><div className="row"><button onClick={()=>setStatus(r.id,"processing")}>Mark Processing</button><button onClick={()=>setStatus(r.id,"needs_documents")}>Request Documents</button><button onClick={()=>setStatus(r.id,"completed")}>Mark Complete</button></div></div></article>)}</div>}</section><section className="section dark"><div className="about"><h2>Official Reference Portals</h2><p>Use official or authorised access only. Rohilla Drive is not a government authority and should not present an informational verification result as a government certificate.</p><div className="row"><a className="call" href="https://echallan.parivahan.gov.in/" target="_blank" rel="noreferrer">eChallan</a><a className="call" href="https://parivahan.gov.in/" target="_blank" rel="noreferrer">Parivahan</a></div></div></section></main>
}
