"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../supabaseClient";

export default function AdminVerification(){
 const db=supabase(); const [session,setSession]=useState<any>(null); const [rows,setRows]=useState<any[]>([]); const [msg,setMsg]=useState("");
 async function load(){const {data,error}=await db.from("vehicle_verification_orders").select("*").order("created_at",{ascending:false});if(error)setMsg(error.message);setRows(data||[])}
 useEffect(()=>{db.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load()})},[]);
 async function setStatus(id:string,status:string){const {error}=await db.from("vehicle_verification_orders").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)setMsg(error.message);else{setMsg(`Verification status updated to ${status}.`);load()}}
 if(!session)return <main><div className="auth"><h1>Vehicle Verification</h1><p>Administrator login is required to access verification records.</p><a className="call" href="/admin">Open Administration</a></div></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE ADMIN</b><small>Vehicle Verification</small></div><a className="call" href="/admin">Administration</a></header><section className="section"><h1>Vehicle Verification Requests</h1><p>Record results only from legitimate authorised sources and supported customer-assisted workflows. Government portals, CAPTCHA, OTP and other access controls must not be bypassed.</p><p>{msg}</p>{rows.length===0?<div className="card"><div className="body"><h3>No verification requests</h3><p>Customer requests submitted through the verification flow will appear here.</p></div></div>:<div className="grid">{rows.map(r=><article className="card" key={r.id}><div className="body"><label>{r.status}</label><h3>{r.vehicle_number}</h3><p>{r.customer_name||"Customer"} • {r.customer_phone}</p><p>Requested: {new Date(r.created_at).toLocaleString("en-IN")}</p><p>Payment: <b>{r.payment_status}</b> • Service fee: ₹{Number(r.service_fee||0).toLocaleString("en-IN")}</p><p>Government fee: ₹{Number(r.government_fee||0).toLocaleString("en-IN")}</p><p>Report: {r.report_url?<a href={r.report_url} target="_blank">Open Report</a>:"Not generated"}</p><div className="row"><button onClick={()=>setStatus(r.id,"processing")}>Mark Processing</button><button onClick={()=>setStatus(r.id,"needs_documents")}>Request Documents</button><button onClick={()=>setStatus(r.id,"completed")}>Mark Complete</button></div></div></article>)}</div>}</section><section className="section dark"><div className="about"><h2>Official resources</h2><p>Use authorised access only. ROHILLA DRIVE is not a government authority and does not issue government certificates or official transport records.</p><div className="row"><a className="call" href="https://echallan.parivahan.gov.in/" target="_blank" rel="noreferrer">eChallan</a><a className="call" href="https://parivahan.gov.in/" target="_blank" rel="noreferrer">Parivahan</a></div></div></section></main>
}
