"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../supabaseClient";

export default function AdminVerification(){
 const db=supabase(); const [ready,setReady]=useState(false); const [rows,setRows]=useState<any[]>([]); const [msg,setMsg]=useState("Checking secure administration access…");
 async function load(){const {data,error}=await db.from("vehicle_verification_orders").select("*").order("created_at",{ascending:false});if(error){setMsg(error.message);return}setRows(data||[]);setMsg("")}
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Administration sign-in required.");return}const [{data:aal},{data:isAdmin}]=await Promise.all([db.auth.mfa.getAuthenticatorAssuranceLevel(),db.rpc("is_admin")]);if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Administrator authentication and Authenticator verification are required.");return}setReady(true);await load()})()},[]);
 async function setStatus(id:string,status:string){const {error}=await db.from("vehicle_verification_orders").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)setMsg(error.message);else{setMsg(`Verification status updated to ${status.replace(/_/g," ")}.`);load()}}
 if(!ready)return <main><div className="auth"><h1>Verification Operations</h1><p>{msg}</p><a className="call" href="/admin">Administration Dashboard</a></div></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE • ADMINISTRATION</b><small>Verification Operations</small></div><a className="call" href="/admin">Administration Dashboard</a></header><section className="section"><h1>Vehicle Verification Requests</h1><p>Record information only from legitimate authorised sources and customer-assisted official workflows. CAPTCHA, OTP and access-control bypasses are not permitted.</p>{msg&&<p>{msg}</p>}{rows.length===0?<div className="card"><div className="body"><h3>No verification requests</h3><p>New customer requests submitted through the verification flow will appear here.</p></div></div>:<div className="grid">{rows.map(r=><article className="card" key={r.id}><div className="body"><label>{r.status}</label><h3>{r.vehicle_number}</h3><p>{r.customer_name||"Customer"} • {r.customer_phone}</p><p>Submitted: {new Date(r.created_at).toLocaleString("en-IN")}</p><p>Payment: <b>{r.payment_status}</b> • Service fee: ₹{Number(r.service_fee||0).toLocaleString("en-IN")}</p><p>Government fee: ₹{Number(r.government_fee||0).toLocaleString("en-IN")}</p><p>Report: {r.report_url?<a href={r.report_url} target="_blank">Open report</a>:"Pending"}</p><div className="row"><button onClick={()=>setStatus(r.id,"processing")}>Mark Processing</button><button onClick={()=>setStatus(r.id,"needs_documents")}>Request Documents</button><button onClick={()=>setStatus(r.id,"completed")}>Mark Completed</button></div></div></article>)}</div>}</section><section className="section dark"><div className="about"><h2>Authorised Reference Sources</h2><p>Use official access channels or customer-assisted workflows. ROHILLA DRIVE is an automotive platform and does not represent itself as an RTO, transport department or government authority.</p><div className="row"><a className="call" href="https://echallan.parivahan.gov.in/" target="_blank" rel="noreferrer">eChallan Portal</a><a className="call" href="https://parivahan.gov.in/" target="_blank" rel="noreferrer">Parivahan Portal</a></div></div></section></main>
}
