"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../supabaseClient";

const MODEL_BRAND:[string,string][]=[
 ["Innova Crysta","Toyota"],["Corolla Altis","Toyota"],["Grand i10","Hyundai"],["Range Rover Evoque","Land Rover"],["XUV700","Mahindra"],["XUV500","Mahindra"],["Scorpio","Mahindra"],["Thar","Mahindra"],["Bolero","Mahindra"],["Harrier","Tata"],["Safari","Tata"],["Nexon","Tata"],["Punch","Tata"],["Altroz","Tata"],["Tiago","Tata"],["Creta","Hyundai"],["Verna","Hyundai"],["Venue","Hyundai"],["Santro","Hyundai"],["Alcazar","Hyundai"],["i20","Hyundai"],["Seltos","Kia"],["Sonet","Kia"],["Carens","Kia"],["Swift","Maruti Suzuki"],["WagonR","Maruti Suzuki"],["Baleno","Maruti Suzuki"],["Brezza","Maruti Suzuki"],["Celerio","Maruti Suzuki"],["Ritz","Maruti Suzuki"],["Ertiga","Maruti Suzuki"],["Dzire","Maruti Suzuki"],["Fortuner","Toyota"],["Glanza","Toyota"],["Hyryder","Toyota"],["Amaze","Honda"],["City","Honda"],["Elevate","Honda"],["WR-V","Honda"],["WRV","Honda"],["EcoSport","Ford"],["Endeavour","Ford"],["Figo","Ford"],["Polo","Volkswagen"],["Virtus","Volkswagen"],["Taigun","Volkswagen"],["Superb","Skoda"],["Octavia","Skoda"],["Slavia","Skoda"],["Kushaq","Skoda"],["C200","Mercedes-Benz"]
];
const BRANDS=["Maruti Suzuki","Hyundai","Mahindra","Tata","Toyota","Honda","Kia","Ford","Volkswagen","Skoda","Renault","Nissan","MG","Jeep","Mercedes-Benz","Mercedes","BMW","Audi","Land Rover","Range Rover"];
const num=(s:string)=>Number(s.replace(/,/g,""));
function parsePoster(raw:string){
 const text=raw.replace(/\r/g," ").replace(/[|•]/g," ");const low=text.toLowerCase();const out:any={notes:""};
 const ym=text.match(/\b(20(?:0\d|1\d|2\d))\b/);if(ym)out.year=ym[1];
 const lakhKm=text.match(/(\d+(?:\.\d+)?)\s*(?:lakh|lac)\s*(?:km|kms|kilomet)/i);if(lakhKm)out.km=String(Math.round(Number(lakhKm[1])*100000));else{const km=text.match(/(\d{1,3}(?:[,.]\d{3})+|\d{4,6})\s*(?:km|kms|kilometers?|kilometres?)/i);if(km)out.km=String(num(km[1].replace(/\./g,"")))}
 if(/\bdiesel\b/i.test(text))out.fuel="Diesel";else if(/\bpetrol\b/i.test(text))out.fuel="Petrol";else if(/\bcng\b/i.test(text))out.fuel="CNG";else if(/\belectric|\bev\b/i.test(text))out.fuel="Electric";else if(/\bhybrid\b/i.test(text))out.fuel="Hybrid";
 if(/\bautomatic\b|\bauto\b|\bAT\b/.test(text))out.transmission="Automatic";else if(/\bmanual\b|\bMT\b/.test(text))out.transmission="Manual";
 const owner=text.match(/\b([1-9])\s*(?:st|nd|rd|th)?\s*owner\b/i);if(owner)out.owner_count=owner[1];else if(/first owner/i.test(text))out.owner_count="1";else if(/second owner/i.test(text))out.owner_count="2";
 const pr=text.match(/(?:price|only|₹|rs\.?)[\s:=-]*₹?\s*(\d+(?:\.\d+)?)(?:\s*(lakh|lac|cr|crore))?/i);if(pr){let v=Number(pr[1]);const unit=(pr[2]||"").toLowerCase();if(unit.startsWith("cr"))v*=10000000;else if(unit||v<100)v*=100000;out.price=String(Math.round(v))}
 for(const [model,brand] of MODEL_BRAND){if(low.includes(model.toLowerCase())){out.model=model;out.brand=brand;break}}
 if(!out.brand){const b=BRANDS.find(x=>low.includes(x.toLowerCase()));if(b)out.brand=b==="Mercedes"?"Mercedes-Benz":b}
 const cityMatch=text.match(/\b(Ambala(?: City)?|Delhi|Gurugram|Gurgaon|Chandigarh|Panchkula|Yamunanagar|Kurukshetra|Karnal|Panipat|Sonipat|Rohtak|Mohali)\b/i);if(cityMatch)out.city=/ambala/i.test(cityMatch[1])?"Ambala City":cityMatch[1];
 const lines=raw.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(out.model){const line=lines.find(x=>x.toLowerCase().includes(out.model.toLowerCase()));if(line){let rest=line.replace(new RegExp(out.brand||"","i"),"").replace(new RegExp(out.model,"i"),"").replace(/20\d{2}/g,"").replace(/[|•,-]+/g," ").trim();if(rest.length>1&&rest.length<40)out.variant=rest}}
 out.notes=lines.filter(x=>!/^\+?91?\s*\d{10}$/.test(x)).slice(0,8).join(" • ");return out;
}

export default function PosterScan(){
 const db=supabase();const [ready,setReady]=useState(false);const [poster,setPoster]=useState<File|null>(null);const [gallery,setGallery]=useState<File[]>([]);const [preview,setPreview]=useState("");const [ocrText,setOcrText]=useState("");const [progress,setProgress]=useState(0);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");const [f,setF]=useState<any>({status:"draft",city:"Ambala City"});
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Admin login required.");return}const {data:aal}=await db.auth.mfa.getAuthenticatorAssuranceLevel();const {data:isAdmin}=await db.rpc("is_admin");if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Open Admin and complete Authenticator verification first.");return}setReady(true)})()},[]);
 function choose(file:File|null){setPoster(file);if(preview)URL.revokeObjectURL(preview);setPreview(file?URL.createObjectURL(file):"");setMsg("")}
 async function scan(){if(!poster)return;setBusy(true);setProgress(1);setMsg("Reading poster…");try{const T=await import("tesseract.js");const result=await T.recognize(poster,"eng",{logger:(m:any)=>{if(m.status==="recognizing text")setProgress(Math.round((m.progress||0)*100))}});const text=result.data.text||"";setOcrText(text);setF((old:any)=>({...old,...parsePoster(text)}));setMsg("Poster read ✓ Please verify the fields before publishing.")}catch(e:any){setMsg(`Poster scan failed: ${e?.message||"Unknown error"}. You can paste the poster text below and tap Parse Text.`)}finally{setBusy(false)}}
 function parseTyped(){setF((old:any)=>({...old,...parsePoster(ocrText)}));setMsg("Text parsed ✓ Please verify all fields.")}
 async function upload(vehicleId:string,files:File[]){for(let i=0;i<files.length;i++){const file=files[i];const path=`${vehicleId}/${Date.now()}-${i}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"")}`;const up=await db.storage.from("vehicle-photos").upload(path,file,{upsert:false});if(up.error)throw up.error;const url=db.storage.from("vehicle-photos").getPublicUrl(path).data.publicUrl;const ins=await db.from("vehicle_photos").insert({vehicle_id:vehicleId,url,path,sort_order:i});if(ins.error)throw ins.error}}
 async function save(e:React.FormEvent){e.preventDefault();if(!poster&&gallery.length===0){setMsg("Select at least one image.");return}setBusy(true);setMsg("Saving vehicle…");const payload:any={brand:f.brand,model:f.model,variant:f.variant||null,year:f.year?Number(f.year):null,km:f.km?Number(f.km):null,fuel:f.fuel||null,transmission:f.transmission||null,owner_count:f.owner_count?Number(f.owner_count):null,asking_price:f.price?Number(f.price):null,city:f.city||"Ambala City",public_notes:f.notes||"",status:f.status||"draft"};const {data,error}=await db.from("vehicles").insert(payload).select().single();if(error){setMsg(error.message);setBusy(false);return}try{const files=[...(poster?[poster]:[]),...gallery.filter(x=>x!==poster)];await upload(data.id,files);await db.from("vehicle_events").insert({vehicle_id:data.id,event_type:"poster_scan_created",event_data:{ocr_used:Boolean(ocrText),status:payload.status}});if(payload.status==="published"){const media=(await db.from("vehicle_photos").select("url").eq("vehicle_id",data.id).order("sort_order")).data?.map((x:any)=>x.url)||[];await db.from("social_posts").insert(["instagram","facebook","youtube"].map(platform=>({vehicle_id:data.id,platform,caption:`${data.brand} ${data.model} ${data.variant||""} | ₹${data.asking_price||""}`,media_urls:media,status:"queued"})))}setMsg(payload.status==="published"?"Vehicle published live ✓":"Vehicle saved as draft ✓");setF({status:"draft",city:"Ambala City"});setPoster(null);setGallery([]);setOcrText("");setPreview("")}catch(err:any){await db.from("vehicles").update({status:"draft"}).eq("id",data.id);setMsg(err?.message||"Photo upload failed; vehicle kept as draft.")}finally{setBusy(false)}}
 if(!ready)return <main><section className="section"><h1>Smart Poster Scan</h1><p>{msg||"Checking Admin security…"}</p><a href="/admin">Back to Admin</a></section></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE</b><small>Smart Poster → Vehicle Details</small></div><div className="row"><a className="call" href="/admin">Control Room</a><a className="call" href="/admin/finance">Finance & RC</a></div></header><section className="section"><h1>Smart Poster Scan</h1><p>Upload a sale poster. The scanner reads visible English text and pre-fills the vehicle form. Always verify details before Publish Live.</p><div className="adminForm"><label className="upload">Sale poster / first image<input accept="image/*" type="file" onChange={e=>choose(e.target.files?.[0]||null)}/></label>{preview&&<img src={preview} alt="Poster preview" style={{maxWidth:320,width:"100%",borderRadius:14}}/>}<button disabled={!poster||busy} onClick={scan}>{busy?`Reading… ${progress}%`:"Scan Poster & Auto-Fill"}</button><textarea placeholder="OCR / listing text (you can also paste text here)" value={ocrText} onChange={e=>setOcrText(e.target.value)} style={{minHeight:120}}/><button disabled={!ocrText||busy} onClick={parseTyped}>Parse Text</button></div>{msg&&<p>{msg}</p>}</section><section className="section"><h2>Verify & Save</h2><form className="adminForm" onSubmit={save}><input required placeholder="Brand" value={f.brand||""} onChange={e=>setF({...f,brand:e.target.value})}/><input required placeholder="Model" value={f.model||""} onChange={e=>setF({...f,model:e.target.value})}/><input placeholder="Variant" value={f.variant||""} onChange={e=>setF({...f,variant:e.target.value})}/><input type="number" placeholder="Year" value={f.year||""} onChange={e=>setF({...f,year:e.target.value})}/><input type="number" placeholder="KM" value={f.km||""} onChange={e=>setF({...f,km:e.target.value})}/><input placeholder="Fuel" value={f.fuel||""} onChange={e=>setF({...f,fuel:e.target.value})}/><input placeholder="Transmission" value={f.transmission||""} onChange={e=>setF({...f,transmission:e.target.value})}/><input type="number" placeholder="Owners" value={f.owner_count||""} onChange={e=>setF({...f,owner_count:e.target.value})}/><input type="number" placeholder="Asking Price ₹" value={f.price||""} onChange={e=>setF({...f,price:e.target.value})}/><input placeholder="City" value={f.city||""} onChange={e=>setF({...f,city:e.target.value})}/><textarea placeholder="Description / features" value={f.notes||""} onChange={e=>setF({...f,notes:e.target.value})}/><label className="upload">Add more car photos<input multiple accept="image/*" type="file" onChange={e=>setGallery(Array.from(e.target.files||[]))}/></label><select value={f.status||"draft"} onChange={e=>setF({...f,status:e.target.value})}><option value="draft">Save Draft — check first</option><option value="published">Publish Live</option></select><button disabled={busy}>{busy?"Saving…":f.status==="published"?"Publish Vehicle Live":"Save Vehicle Draft"}</button></form></section></main>
}
