"use client";
import {useState} from "react";
import {supabase} from "../supabaseClient";

declare global {interface Window{webkitSpeechRecognition?:any;SpeechRecognition?:any}}

type Intent={type:string;label:string;vehicleType:string;service?:string};
function understand(raw:string):Intent{
 const t=raw.toLowerCase();
 const vehicleType=/bike|motorcycle|scooter|two.?wheeler/.test(t)?"two_wheeler":/truck|commercial|pickup|tempo|bus/.test(t)?"commercial":/tractor|agri|farm/.test(t)?"tractor_agri":/ev|electric/.test(t)?"ev":"car_suv";
 if(/dealer|dealership|work with|partner|business join|business hub|workshop.*join/.test(t))return {type:"business",label:"Join / Work with Rohilla Drive",vehicleType};
 if(/sell|sale|bech|बेच/.test(t))return {type:"sell",label:"Sell / List Vehicle",vehicleType};
 if(/new car|new vehicle|new bike|new scooter|new tractor|brand new|showroom/.test(t))return {type:"new",label:"New Vehicle Assistance",vehicleType};
 const services:[[RegExp,string],...Array<[RegExp,string]>]=[[/insurance|policy/,"insurance"],[/rc |rto|transfer/,"RC / ownership transfer"],[/service|repair|workshop|mechanic/,"workshop service"],[/inspect|verify|inspection/,"vehicle inspection"],[/scrap|recycle/,"registered RVSF vehicle scrapping"],[/detail|ceramic|paint/,"vehicle detailing"],[/roadside|rsa|towing|breakdown/,"RSA assistance"],[/finance|loan|emi/,"vehicle finance"]];
 for(const [re,s] of services)if(re.test(t))return {type:"service",label:s,vehicleType,service:s};
 return {type:"buy",label:"Buy / Find Vehicle",vehicleType};
}

export default function Assistant(){
 const db=supabase();const [text,setText]=useState("");const [intent,setIntent]=useState<Intent|null>(null);const [listening,setListening]=useState(false);const [f,setF]=useState<any>({city:"Ambala City"});const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 function analyse(v=text){const i=understand(v);setIntent(i);return i}
 function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMsg("Voice recognition is not available in this browser. Type your request below.");return}const r=new SR();r.lang="hi-IN";r.interimResults=false;setListening(true);r.onresult=(e:any)=>{const v=e.results?.[0]?.[0]?.transcript||"";setText(v);analyse(v);setListening(false)};r.onerror=()=>{setListening(false);setMsg("Voice capture stopped. Please type the request.")};r.onend=()=>setListening(false);r.start()}
 async function submit(e:React.FormEvent){e.preventDefault();const i=intent||analyse();if(i.type==="business"){location.href="/business-hub";return}setBusy(true);setMsg("Saving request…");if(i.type==="service"){const {error}=await db.from("service_requests").insert({customer_name:f.name,customer_phone:f.phone,category:i.service,customer_location:f.city||null,details:text,status:"new"});setBusy(false);if(error){setMsg(error.message);return}setMsg("Service request saved ✓");return}const {error}=await db.from("leads").insert({customer_name:f.name,customer_phone:f.phone,requirement:i.label,message:text,status:"new",source:"rohilla_voice_assist",enquiry_type:i.type==="new"?"new_vehicle":i.type==="sell"?"sell_vehicle":"buy_vehicle",new_or_used:i.type==="new"?"new":"used",vehicle_type:i.vehicleType,customer_city:f.city||null,budget:f.budget?Number(f.budget):null,preferred_brand:f.brand||null,preferred_model:f.model||null});setBusy(false);if(error){setMsg(error.message);return}setMsg("Request saved ✓ Rohilla Drive can now continue from this requirement.")}
 return <main><header><div className="brand"><b>ROHILLA INTELLIGENCE</b><small>Customer Voice Assist • Beta</small></div><div className="row"><a className="call" href="/">Customer Website</a><a className="call" href="/business-hub">Business Hub</a></div></header><section className="hero"><div className="heroText"><span>VOICE • HINDI / HINGLISH / ENGLISH</span><h1>Tell Rohilla Drive what you want to do.</h1><p>Buy, sell, new vehicle, service, insurance, RC, inspection, scrap or business partnership — speak naturally and the platform routes the requirement.</p></div></section><section className="section"><div className="adminForm"><button onClick={voice}>{listening?"🎙️ Listening…":"🎙️ Speak to Rohilla"}</button><textarea style={{minHeight:130}} placeholder="Example: Mujhe 12 lakh ke around automatic new SUV chahiye Ambala me, exchange bhi hai." value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>analyse()} disabled={!text.trim()}>Understand Request</button></div>{intent&&<div className="notice"><b>Detected:</b> {intent.label} • {intent.vehicleType.replace("_"," ")}{intent.type==="business"&&<> — <a href="/business-hub">Open Business Hub</a></>}</div>}</section>{intent&&intent.type!=="business"&&<section className="section"><h2>Continue</h2><form className="adminForm" onSubmit={submit}><input required placeholder="Your name" value={f.name||""} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="Mobile number" value={f.phone||""} onChange={e=>setF({...f,phone:e.target.value})}/><input placeholder="City" value={f.city||""} onChange={e=>setF({...f,city:e.target.value})}/>{intent.type!=="service"&&<><input placeholder="Preferred brand (optional)" value={f.brand||""} onChange={e=>setF({...f,brand:e.target.value})}/><input placeholder="Preferred model (optional)" value={f.model||""} onChange={e=>setF({...f,model:e.target.value})}/><input type="number" placeholder="Budget ₹ (optional)" value={f.budget||""} onChange={e=>setF({...f,budget:e.target.value})}/></>}<button disabled={busy}>{busy?"Saving…":"Submit to Rohilla Drive"}</button></form>{msg&&<div className="notice">{msg}</div>}</section>}<section className="section dark"><div className="about"><h2>This is the command layer, not the final AI ceiling.</h2><p>The live beta already accepts voice/text and routes customer intent. Multimodal photo/RC understanding, natural follow-up questions, live inventory reasoning and autonomous tool actions will activate when the secured AI provider is connected.</p></div></section></main>
}
