"use client";
import {useEffect,useState} from "react";
import {supabase} from "../supabaseClient";
import {LANGUAGE_STORAGE_KEY,languageByCode} from "../lib/rohilla-languages";
import CustomerBackBar from "../components/CustomerBackBar";

declare global {interface Window{webkitSpeechRecognition?:any;SpeechRecognition?:any}}

type Intent={type:string;label:string;vehicleType:string;service?:string};
type Match={id:string;brand:string;model:string;variant?:string|null;year?:number|null;fuel?:string|null;km?:number|null;asking_price?:number|null;city?:string|null;vehicle_type?:string|null;vehicle_photos?:{url:string;sort_order?:number}[]};
function understand(raw:string):Intent{
 const t=raw.toLowerCase();
 const vehicleType=/bike|motorcycle|scooter|two.?wheeler/.test(t)?"two_wheeler":/truck|commercial|pickup|tempo|bus/.test(t)?"commercial":/tractor|agri|farm/.test(t)?"tractor_agri":/ev|electric/.test(t)?"ev":"car_suv";
 if(/dealer|dealership|oem|work with|partner|business join|business hub|workshop.*join/.test(t))return {type:"business",label:"Join / Work with Rohilla Drive",vehicleType};
 if(/sell|sale|bech|बेच|बेचना/.test(t))return {type:"sell",label:"Sell / List Vehicle",vehicleType};
 if(/new car|new vehicle|new bike|new scooter|new tractor|brand new|showroom|नई गाड़ी|नयी गाड़ी/.test(t))return {type:"new",label:"New Vehicle Assistance",vehicleType};
 const services:[[RegExp,string],...Array<[RegExp,string]>]=[[/insurance|policy|बीमा/,"insurance"],[/rc |rto|transfer|आरसी/,"RC / ownership transfer"],[/service|repair|workshop|mechanic|सर्विस|रिपेयर/,"workshop service"],[/inspect|verify|inspection|जांच|वेरिफ/,"vehicle inspection"],[/scrap|recycle|स्क्रैप/,"registered RVSF vehicle scrapping"],[/detail|ceramic|paint|डिटेल/,"vehicle detailing"],[/roadside|rsa|towing|breakdown|टोइंग/,"RSA assistance"],[/finance|loan|emi|लोन|फाइनेंस/,"vehicle finance"]];
 for(const [re,s] of services)if(re.test(t))return {type:"service",label:s,vehicleType,service:s};
 return {type:"buy",label:"Buy / Find Vehicle",vehicleType};
}

async function translate(text:string,target:string,source="auto"){
 try{const r=await fetch("/api/translate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,target,source})});const j=await r.json();return {text:j?.translations?.[0]||text,configured:Boolean(j?.configured)}}catch{return {text,configured:false}}
}

function parseBudget(text:string){const t=text.toLowerCase().replace(/,/g,"");const m=t.match(/(\d+(?:\.\d+)?)\s*(lakh|lac|लाख|crore|cr|करोड़)?/g)||[];let best=0;for(const raw of m){const n=parseFloat(raw);if(!Number.isFinite(n))continue;const val=/crore|cr|करोड़/.test(raw)?n*10000000:/lakh|lac|लाख/.test(raw)?n*100000:n>=100000?n:0;if(val>best)best=val}return best||null}
function tokens(text:string){const stop=new Set(["want","need","looking","find","buy","car","vehicle","used","second","hand","me","for","a","an","the","in","under","below","around","please","chahiye","chaahiye","gadi","gaadi"]);return text.toLowerCase().replace(/[^a-z0-9\s-]/g," ").split(/\s+/).filter(x=>x.length>1&&!stop.has(x)&&!/^\d+$/.test(x))}

export default function Assistant(){
 const db=supabase();const [text,setText]=useState("");const [normalized,setNormalized]=useState("");const [intent,setIntent]=useState<Intent|null>(null);const [listening,setListening]=useState(false);const [f,setF]=useState<any>({city:"Ambala City"});const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const [lang,setLang]=useState("en-IN");const [matches,setMatches]=useState<Match[]>([]);
 useEffect(()=>{const read=()=>setLang(localStorage.getItem(LANGUAGE_STORAGE_KEY)||"en-IN");read();const fn=(e:any)=>setLang(e?.detail?.code||localStorage.getItem(LANGUAGE_STORAGE_KEY)||"en-IN");window.addEventListener("rohilla-language-change",fn);return()=>window.removeEventListener("rohilla-language-change",fn)},[]);
 async function findInventory(query:string,i:Intent){setMatches([]);const {data}=await db.from("vehicles").select("id,brand,model,variant,year,fuel,km,asking_price,city,vehicle_type,vehicle_photos(url,sort_order)").eq("status","published").order("created_at",{ascending:false}).limit(150);const list=(data||[]) as Match[];if(!list.length)return;const q=query.toLowerCase();const keys=tokens(query);const budget=parseBudget(query);const fuel=/diesel|डीजल/.test(q)?"diesel":/petrol|पेट्रोल/.test(q)?"petrol":/cng/.test(q)?"cng":/electric|\bev\b/.test(q)?"electric":null;const ranked=list.map(car=>{const hay=`${car.brand} ${car.model} ${car.variant||""} ${car.year||""} ${car.fuel||""} ${car.city||""} ${car.vehicle_type||""}`.toLowerCase();let score=0;for(const k of keys)if(hay.includes(k))score+=3;if(fuel&&String(car.fuel||"").toLowerCase().includes(fuel))score+=4;if(i.vehicleType&&i.vehicleType!=="car_suv"&&car.vehicle_type===i.vehicleType)score+=5;if(budget&&Number(car.asking_price||0)<=budget)score+=2;if(budget&&Number(car.asking_price||0)>budget*1.2)score-=3;return {car,score}}).filter(x=>x.score>0||keys.length===0).sort((a,b)=>b.score-a.score||Number(b.car.year||0)-Number(a.car.year||0)).slice(0,6).map(x=>x.car);setMatches(ranked)}
 async function analyse(v=text){setBusy(true);setMsg("Rohilla Intelligence is understanding your request…");const tr=lang==="en-IN"?{text:v,configured:true}:await translate(v,"en-IN",lang);const i=understand(tr.text);setNormalized(tr.text);setIntent(i);if(i.type==="buy")await findInventory(tr.text,i);else setMatches([]);setBusy(false);setMsg(lang!=="en-IN"&&!tr.configured?"Your original message is preserved. Paid translation is OFF, so Rohilla will continue from the original text and your submitted requirement.":i.type==="buy"?"Matched against Rohilla Drive's own live inventory — no paid AI used.":"");return i}
 function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMsg("Voice recognition is not available in this browser. Type your request below.");return}const r=new SR();r.lang=languageByCode(lang).speechCode;r.interimResults=false;r.continuous=false;setListening(true);r.onresult=async(e:any)=>{const v=e.results?.[0]?.[0]?.transcript||"";setText(v);setListening(false);await analyse(v)};r.onerror=()=>{setListening(false);setMsg("Voice capture stopped. Please type the request.")};r.onend=()=>setListening(false);r.start()}
 async function replyMessage(english:string){if(lang==="en-IN")return english;const tr=await translate(english,lang,"en-IN");return tr.text}
 async function submit(e:React.FormEvent){e.preventDefault();const i=intent||await analyse();if(i.type==="business"){location.href="/business-hub";return}setBusy(true);setMsg(await replyMessage("Saving your request…"));const stored=[`Customer language: ${lang}`,`Original: ${text}`,normalized&&normalized!==text?`English operator view: ${normalized}`:""] .filter(Boolean).join("\n");if(i.type==="service"){const {error}=await db.from("service_requests").insert({customer_name:f.name,customer_phone:f.phone,category:i.service,customer_location:f.city||null,details:stored,status:"new"});setBusy(false);if(error){setMsg(error.message);return}setMsg(await replyMessage("Service request saved. Rohilla Drive can continue with you in your selected language."));return}const {error}=await db.from("leads").insert({customer_name:f.name,customer_phone:f.phone,requirement:i.label,message:stored,status:"new",source:"rohilla_multilingual_voice_assist",enquiry_type:i.type==="new"?"new_vehicle":i.type==="sell"?"sell_vehicle":"buy_vehicle",new_or_used:i.type==="new"?"new":"used",vehicle_type:i.vehicleType,customer_city:f.city||null,budget:f.budget?Number(f.budget):null,preferred_brand:f.brand||null,preferred_model:f.model||null});setBusy(false);if(error){setMsg(error.message);return}setMsg(await replyMessage("Request saved. Rohilla Drive can now continue from this requirement."))}
 return <main><CustomerBackBar/><header><div className="brand"><b>ROHILLA INTELLIGENCE</b><small>Rohilla-owned routing + inventory engine • Beta</small></div><div className="row"><a className="call" href="/inventory">Inventory</a><a className="call" href="/business-hub">Business Hub</a></div></header><section className="hero"><div className="heroText"><span>VOICE • TEXT • ROHILLA DOMAIN INTELLIGENCE</span><h1>Tell Rohilla what you need.</h1><p>Buy, sell, new vehicle, service, insurance, RC, inspection, scrap or business partnership. Inventory matching and workflow routing run on Rohilla's own rules and database without a paid AI provider.</p></div></section><section className="section"><div className="notice"><b>Selected language:</b> {languageByCode(lang).nativeName} • Change it anytime from the 🌐 language button.</div><div className="adminForm"><button onClick={voice}>{listening?"🎙️ Listening…":"🎙️ Speak to Rohilla"}</button><textarea style={{minHeight:130}} placeholder="Example: I need a diesel Creta under 8 lakh in Ambala…" value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>analyse()} disabled={!text.trim()||busy}>{busy?"Working…":"Find / Understand"}</button></div>{intent&&<div className="notice"><b>Detected:</b> {intent.label} • {intent.vehicleType.replace("_"," ")}{intent.type==="business"&&<> — <a href="/business-hub">Open Business Hub</a></>}</div>}{msg&&<div className="notice">{msg}</div>}</section>
 {matches.length>0&&<section className="section" style={{paddingTop:10}}><div className="head"><div><h2>Rohilla Matches</h2><p>Live published inventory matched from your words.</p></div><a className="call" href={`/inventory?q=${encodeURIComponent(text)}`}>See Full Inventory</a></div><div className="grid">{matches.map(car=>{const photo=[...(car.vehicle_photos||[])].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0))[0]?.url;return <article className="card" key={car.id}><div className="photo real">{photo?<img src={photo} alt={`${car.brand} ${car.model}`}/>:<span>🚘</span>}</div><div className="body"><h3>{car.brand} {car.model}</h3>{car.variant&&<p>{car.variant}</p>}<small>{car.year||""} • {Number(car.km||0).toLocaleString("en-IN")} km • {car.fuel||""}{car.city?` • ${car.city}`:""}</small><strong>₹{Number(car.asking_price||0).toLocaleString("en-IN")}</strong><a className="call" href={`/cars/${car.id}`} style={{display:"block",textAlign:"center"}}>View Vehicle</a></div></article>})}</div></section>}
 {intent&&intent.type!=="business"&&<section className="section"><h2>Continue</h2>{intent.type==="sell"&&<p><a className="call" href="/sell">Open dedicated Sell / List form</a></p>}{intent.type==="new"&&<p><a className="call" href="/new-vehicles">Open New Vehicle Assistance</a></p>}<form className="adminForm" onSubmit={submit}><input required placeholder="Your name" value={f.name||""} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="Mobile number" value={f.phone||""} onChange={e=>setF({...f,phone:e.target.value})}/><input placeholder="City" value={f.city||""} onChange={e=>setF({...f,city:e.target.value})}/>{intent.type!=="service"&&<><input placeholder="Preferred brand (optional)" value={f.brand||""} onChange={e=>setF({...f,brand:e.target.value})}/><input placeholder="Preferred model (optional)" value={f.model||""} onChange={e=>setF({...f,model:e.target.value})}/><input type="number" placeholder="Budget ₹ (optional)" value={f.budget||""} onChange={e=>setF({...f,budget:e.target.value})}/></>}<button disabled={busy}>{busy?"Saving…":"Submit to Rohilla Drive"}</button></form></section>}<section className="section dark"><div className="about"><h2>Our AI strategy</h2><p>Rohilla Intelligence owns the automotive rules, matching, routing, workflows and business data. Paid foundation-model features stay optional and OFF until they create enough revenue to justify their cost.</p></div></section></main>
}
