"use client";
import {useEffect,useState} from "react";
import {supabase} from "../supabaseClient";
import {LANGUAGE_STORAGE_KEY,languageByCode} from "../lib/rohilla-languages";

declare global {interface Window{webkitSpeechRecognition?:any;SpeechRecognition?:any}}

type Intent={type:string;label:string;vehicleType:string;service?:string};
function understand(raw:string):Intent{
 const t=raw.toLowerCase();
 const vehicleType=/bike|motorcycle|scooter|two.?wheeler/.test(t)?"two_wheeler":/truck|commercial|pickup|tempo|bus/.test(t)?"commercial":/tractor|agri|farm/.test(t)?"tractor_agri":/ev|electric/.test(t)?"ev":"car_suv";
 if(/dealer|dealership|oem|work with|partner|business join|business hub|workshop.*join/.test(t))return {type:"business",label:"Join / Work with Rohilla Drive",vehicleType};
 if(/sell|sale|bech|बेच|बेचना/.test(t))return {type:"sell",label:"Sell / List Vehicle",vehicleType};
 if(/new car|new vehicle|new bike|new scooter|new tractor|brand new|showroom|नई गाड़ी|नयी गाड़ी/.test(t))return {type:"new",label:"New Vehicle Assistance",vehicleType};
 const services:[[RegExp,string],...Array<[RegExp,string]>]=[[/insurance|policy|बीमा/,"insurance"],[/rc |rto|transfer|आरसी/,"RC / ownership transfer"],[/service|repair|workshop|mechanic|सर्विस|रिपेयर/,"workshop service"],[/inspect|verify|inspection|जांच|वेरिफ/,"vehicle inspection"],[/scrap|recycle|स्क्रैप/,"registered RVSF vehicle scrapping"],[/detail|ceramic|paint|डिटेल/,"vehicle detailing"],[/roadside|rsa|towing|breakdown|टोइंग/,"RSA assistance"],[/finance|loan|emi|लोन|फाइनेंस/,"vehicle finance"]];
 for(const [re,s] of services)if(re.test(t))return {type:"service",label:s,vehicleType,service:s};
 return {type:"buy",label:"Buy / Find Vehicle",vehicleType};
}

async function translate(text:string,target:string,source="auto"){
 try{const r=await fetch("/api/translate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,target,source})});const j=await r.json();return {text:j?.translations?.[0]||text,configured:Boolean(j?.configured)}}catch{return {text,configured:false}}
}

export default function Assistant(){
 const db=supabase();const [text,setText]=useState("");const [normalized,setNormalized]=useState("");const [intent,setIntent]=useState<Intent|null>(null);const [listening,setListening]=useState(false);const [f,setF]=useState<any>({city:"Ambala City"});const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const [lang,setLang]=useState("en-IN");
 useEffect(()=>{const read=()=>setLang(localStorage.getItem(LANGUAGE_STORAGE_KEY)||"en-IN");read();const fn=(e:any)=>setLang(e?.detail?.code||localStorage.getItem(LANGUAGE_STORAGE_KEY)||"en-IN");window.addEventListener("rohilla-language-change",fn);return()=>window.removeEventListener("rohilla-language-change",fn)},[]);
 async function analyse(v=text){setBusy(true);setMsg("Understanding your request…");const tr=lang==="en-IN"?{text:v,configured:true}:await translate(v,"en-IN",lang);const i=understand(tr.text);setNormalized(tr.text);setIntent(i);setBusy(false);setMsg(lang!=="en-IN"&&!tr.configured?"Your language is saved and the original message will be preserved. Live translation provider is not connected yet.":"");return i}
 function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMsg("Voice recognition is not available in this browser. Type your request below.");return}const r=new SR();r.lang=languageByCode(lang).speechCode;r.interimResults=false;r.continuous=false;setListening(true);r.onresult=async(e:any)=>{const v=e.results?.[0]?.[0]?.transcript||"";setText(v);setListening(false);await analyse(v)};r.onerror=()=>{setListening(false);setMsg("Voice capture stopped. Please type the request.")};r.onend=()=>setListening(false);r.start()}
 async function replyMessage(english:string){if(lang==="en-IN")return english;const tr=await translate(english,lang,"en-IN");return tr.text}
 async function submit(e:React.FormEvent){e.preventDefault();const i=intent||await analyse();if(i.type==="business"){location.href="/business-hub";return}setBusy(true);setMsg(await replyMessage("Saving your request…"));const stored=[`Customer language: ${lang}`,`Original: ${text}`,normalized&&normalized!==text?`English operator view: ${normalized}`:""] .filter(Boolean).join("\n");if(i.type==="service"){const {error}=await db.from("service_requests").insert({customer_name:f.name,customer_phone:f.phone,category:i.service,customer_location:f.city||null,details:stored,status:"new"});setBusy(false);if(error){setMsg(error.message);return}setMsg(await replyMessage("Service request saved. Rohilla Drive can continue with you in your selected language."));return}const {error}=await db.from("leads").insert({customer_name:f.name,customer_phone:f.phone,requirement:i.label,message:stored,status:"new",source:"rohilla_multilingual_voice_assist",enquiry_type:i.type==="new"?"new_vehicle":i.type==="sell"?"sell_vehicle":"buy_vehicle",new_or_used:i.type==="new"?"new":"used",vehicle_type:i.vehicleType,customer_city:f.city||null,budget:f.budget?Number(f.budget):null,preferred_brand:f.brand||null,preferred_model:f.model||null});setBusy(false);if(error){setMsg(error.message);return}setMsg(await replyMessage("Request saved. Rohilla Drive can now continue from this requirement."))}
 return <main><header><div className="brand"><b>ROHILLA INTELLIGENCE</b><small>Multilingual Customer Voice Assist • Beta</small></div><div className="row"><a className="call" href="/">Customer Website</a><a className="call" href="/business-hub">Business Hub</a></div></header><section className="hero"><div className="heroText"><span>VOICE • TEXT • INDIAN LANGUAGES</span><h1>Speak in your language. Rohilla Drive handles the handoff.</h1><p>Buy, sell, new vehicle, service, insurance, RC, inspection, scrap or business partnership — the assistant preserves your original words and prepares an operator-friendly view.</p></div></section><section className="section"><div className="notice"><b>Selected language:</b> {languageByCode(lang).nativeName} • Change it anytime from the 🌐 language button.</div><div className="adminForm"><button onClick={voice}>{listening?"🎙️ Listening…":"🎙️ Speak to Rohilla"}</button><textarea style={{minHeight:130}} placeholder="Speak or type naturally in your selected language…" value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>analyse()} disabled={!text.trim()||busy}>{busy?"Working…":"Understand Request"}</button></div>{intent&&<div className="notice"><b>Detected:</b> {intent.label} • {intent.vehicleType.replace("_"," ")}{intent.type==="business"&&<> — <a href="/business-hub">Open Business Hub</a></>}</div>}{msg&&<div className="notice">{msg}</div>}</section>{intent&&intent.type!=="business"&&<section className="section"><h2>Continue</h2><form className="adminForm" onSubmit={submit}><input required placeholder="Your name" value={f.name||""} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="Mobile number" value={f.phone||""} onChange={e=>setF({...f,phone:e.target.value})}/><input placeholder="City" value={f.city||""} onChange={e=>setF({...f,city:e.target.value})}/>{intent.type!=="service"&&<><input placeholder="Preferred brand (optional)" value={f.brand||""} onChange={e=>setF({...f,brand:e.target.value})}/><input placeholder="Preferred model (optional)" value={f.model||""} onChange={e=>setF({...f,model:e.target.value})}/><input type="number" placeholder="Budget ₹ (optional)" value={f.budget||""} onChange={e=>setF({...f,budget:e.target.value})}/></>}<button disabled={busy}>{busy?"Saving…":"Submit to Rohilla Drive"}</button></form></section>}<section className="section dark"><div className="about"><h2>Rohilla Language Bridge</h2><p>Customer language → speech/text capture → translation → intent → Rohilla operator/dealer/partner workflow → reply translation back to the customer language. Live phone-call translation uses the same language layer but also requires an authorised telephony stream plus speech-to-text and text-to-speech connections.</p></div></section></main>
}
