export const metadata={title:"Privacy Notice",description:"How ROHILLA DRIVE handles customer, seller, dealer and business partner information.",alternates:{canonical:"/privacy"}};

const sectionStyle={background:"#fff",border:"1px solid #d9dee8",borderRadius:18,padding:22,marginBottom:14,lineHeight:1.65,color:"#334155"} as const;

export default function PrivacyPage(){return <main style={{maxWidth:960,margin:"0 auto",padding:"100px 18px 56px",fontFamily:"Arial,Helvetica,sans-serif"}}>
  <a href="/" style={{fontWeight:800}}>← ROHILLA DRIVE</a>
  <h1 style={{fontSize:"clamp(32px,6vw,54px)",marginBottom:6}}>Privacy Notice</h1>
  <p style={{color:"#64748b"}}>Effective: 9 September 2026</p>

  <section style={sectionStyle}><h2>1. Scope</h2><p>This notice explains how ROHILLA DRIVE, operating under the Rohilla Multibrand Cars business name, handles personal information when customers, sellers, dealers, partners and other users use rohilladrive.com, its portals, forms, enquiries or connected communication workflows.</p><p>We aim to handle personal information only for lawful and relevant purposes and to apply applicable Indian data-protection requirements as they become applicable to the relevant processing activity.</p></section>

  <section style={sectionStyle}><h2>2. Information we may collect</h2><p>Depending on the feature used, this may include name, phone number, email address, city, business name and address, vehicle details, service requirements, messages, account/profile information, listing photos, submitted documents where a workflow permits them, consent or preference records, and basic technical/security records needed to operate and protect the service.</p><p>Please do not send passwords or OTPs. Do not upload Aadhaar, PAN, bank details or other sensitive identification unless a specific verified workflow clearly requires that information and explains why it is needed.</p></section>

  <section style={sectionStyle}><h2>3. Why we use information</h2><p>We may use information to respond to enquiries, create and secure accounts, review dealer or partner applications, manage inventory and listings, coordinate vehicle or service requests, carry out verification assistance, route an accepted requirement to a relevant provider, maintain transaction or support records, prevent misuse, improve the platform and meet applicable legal or regulatory obligations.</p></section>

  <section style={sectionStyle}><h2>4. Direct transactions, referrals and sharing</h2><p>If Rohilla Multibrand Cars is directly buying or selling a vehicle, information may be used as reasonably necessary for that transaction and related records. For marketplace, referral or coordination workflows, information may be shared with a relevant dealer, service business or other provider when needed for the user-requested service, when the user has chosen or accepted the handoff, or when sharing is otherwise permitted or required by law.</p><p>We do not sell personal information as a standalone data product. For regulated services such as finance or insurance, information should be routed only to an appropriately authorised or licensed provider as applicable.</p></section>

  <section style={sectionStyle}><h2>5. Dealer and Partner access</h2><p>Private portal access is role-based. A dealer or Partner should receive only the information reasonably needed for the assigned workflow. Customer phone numbers, emails or private documents are not intended to be exposed broadly merely because an enquiry or service request exists on the platform. Rohilla Drive may coordinate the connection or disclose relevant details when the workflow, user choice or applicable permission allows it.</p></section>

  <section style={sectionStyle}><h2>6. Public listings</h2><p>Vehicle details and approved listing photos may be public when a vehicle is published. A seller's or customer's private phone number, email address, home address or private document should not be made public by default unless that person has specifically asked for or agreed to that publication or the information is lawfully required to be displayed.</p></section>

  <section style={sectionStyle}><h2>7. Service providers and external platforms</h2><p>Rohilla Drive uses technology, hosting, authentication, communications and other service providers to operate and secure the platform. If you choose to continue a workflow on WhatsApp or another external service, that service also processes information under its own terms and privacy practices. Government portals and third-party websites linked from Rohilla Drive are independently operated.</p></section>

  <section style={sectionStyle}><h2>8. Technical data and cookies</h2><p>The platform or its service providers may process ordinary technical information such as device/browser details, IP address, security logs, session information and similar records needed for authentication, fraud prevention, reliability, analytics or platform security. Where a consent choice is legally required for a particular cookie or tracking technology, the applicable choice should be provided before that technology is used for the relevant purpose.</p></section>

  <section style={sectionStyle}><h2>9. Retention</h2><p>Information should be retained only for as long as reasonably necessary for the purpose for which it was collected, for account or security needs, transaction and dispute records, fraud prevention, or applicable legal and regulatory requirements. When information is no longer reasonably required, it may be deleted, de-identified or anonymised where appropriate.</p></section>

  <section style={sectionStyle}><h2>10. Security</h2><p>We use reasonable technical and organisational measures such as authentication controls, role-based access, protected private data areas and access restrictions. No internet service can promise absolute security, so users should also protect passwords, OTPs and devices and should report suspected unauthorised access promptly.</p></section>

  <section style={sectionStyle}><h2>11. Your choices and requests</h2><p>Subject to applicable law and legitimate retention requirements, you may ask about personal information connected with your account or enquiry, request correction of inaccurate information, request deletion where appropriate, or withdraw a consent that is no longer required for an ongoing requested service. Withdrawal does not undo processing that was lawful before withdrawal and may prevent completion of the affected workflow.</p></section>

  <section style={sectionStyle}><h2>12. Children</h2><p>Rohilla Drive is intended for vehicle owners, buyers and business users and is not designed as a service for children. We do not knowingly seek children's personal data for ordinary platform use. Where applicable law requires parental or guardian consent, the relevant workflow must not proceed without it.</p></section>

  <section style={sectionStyle}><h2>13. Privacy and grievance contact</h2><p>For a privacy, correction, deletion, consent or account-data request, contact ROHILLA DRIVE / Rohilla Multibrand Cars, Ambala City, Haryana at <a href="tel:+917015260003">+91 70152 60003</a> (phone/WhatsApp). Please identify the relevant account, enquiry, vehicle or transaction reference, but never send your password or OTP.</p><p>Where applicable law prescribes a specific data-protection or grievance process or timeline, that requirement will apply.</p></section>

  <section style={sectionStyle}><h2>14. Updates</h2><p>We may update this notice as the product, business model, service providers or applicable legal requirements change. The effective date will be updated on this page.</p></section>
</main>}
