"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "./supabaseClient";

type Vehicle = { id:string; brand:string; model:string; variant?:string; year:number; km:number; fuel:string; owner_count?:number; asking_price:number; city?:string; public_notes?:string; vehicle_photos?:{url:string;sort_order?:number}[] };

export default function Home(){
 const db=supabase(); const [cars,setCars]=useState<Vehicle[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(""); const [fuel,setFuel]=useState("All"); const [leadOpen,setLeadOpen]=useState(false); const [leadMessage,setLeadMessage]=useState(""); const [leadType,setLeadType]=useState(""); const [leadName,setLeadName]=useState(""); const [leadPhone,setLeadPhone]=useState(""); const [leadLocation,setLeadLocation]=useState(""); const [leadTime,setLeadTime]=useState(""); const [leadBusy,setLeadBusy]=useState(false);
 useEffect(()=>{async function loadCars(){const {data}=await db.from("vehicles").select("*,vehicle_photos(url,sort_order)").eq("status","published").order("created_at",{ascending:false});setCars((data||[]) as Vehicle[]);setLoading(false)}loadCars()},[]);
 const filteredCars=useMemo(()=>{const q=search.trim().toLowerCase();return cars.filter(car=>{const text=`${car.brand} ${car.model} ${car.variant||""} ${car.year} ${car.city||""}`.toLowerCase();return(!q||text.includes(q))&&(fuel==="All"||car.fuel===fuel)})},[cars,search,fuel]);
 function whatsapp(text:string){window.open(`https://wa.me/917015260003?text=${encodeURIComponent(text)}`,"_blank")}
 function openLead(type:string){setLeadType(type);setLeadMessage(`Hello Rohilla Drive, I am interested in your ${type} service. Please contact me.`);setLeadOpen(true)}
 function openServiceLead(type:string){setLeadType(type);setLeadMessage(`I need ${type} assistance.`);setLeadOpen(true)}
 async function submitLead(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!leadName.trim()||!leadPhone.trim())return;setLeadBusy(true);const isService=!['vehicle purchase','vehicle sale','car purchase','car sale'].includes(leadType);if(isService){const {error}=await db.from('service_requests').insert({customer_name:leadName.trim(),customer_phone:leadPhone.trim(),category:leadType,customer_location:leadLocation.trim()||null,details:leadMessage.trim()||null,preferred_time:leadTime.trim()||null,status:'new'});if(error){setLeadBusy(false);alert(error.message);return}setLeadBusy(false);setLeadOpen(false);setLeadName('');setLeadPhone('');setLeadLocation('');setLeadTime('');alert('Request submitted ✓ ROHILLA DRIVE will coordinate a verified service provider.');return}whatsapp(`${leadMessage}\n\nName: ${leadName}\nPhone: ${leadPhone}\nLocation: ${leadLocation}\n\nROHILLA DRIVE\n7015260003`);setLeadBusy(false);setLeadOpen(false)}
 const verticals=[['🚗','Cars & SUVs','Buy, sell, verify and manage personal vehicles.','car / SUV'],['🏍️','Two-Wheelers','Bikes, scooters and electric two-wheelers.','two-wheeler'],['🚚','Commercial Vehicles','Pickups, LCVs, trucks and buses.','commercial vehicle'],['🚜','Tractor & Agriculture','Tractors and agriculture mobility support.','tractor / agriculture vehicle'],['🏢','Fleet & Transporters','Fleet operations, compliance and service coordination.','fleet / transporter'],['⚡','EV Network','Electric vehicles and future mobility support.','EV vehicle']];
 const socialLinks=<div className="socialIcons">
  <a href="https://www.instagram.com/rohillamultibrandcars/" target="_blank" rel="noreferrer" aria-label="Instagram" title="Instagram" className="instagram"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg></a>
  <a href="https://www.facebook.com/" target="_blank" rel="noreferrer" aria-label="Facebook" title="Facebook" className="facebook"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M14 8h3V4h-3c-3.3 0-5 2-5 5v2H6v4h3v5h4v-5h3.2l.8-4H13V9c0-.7.3-1 1-1Z"/></svg></a>
  <a href="https://youtube.com/shorts/hqYTgiIaEko?si=mSFnKGfy3PX3d6WP" target="_blank" rel="noreferrer" aria-label="YouTube" title="YouTube" className="youtube"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M21.6 7.2a2.8 2.8 0 0 0-2-2C17.8 4.7 12 4.7 12 4.7s-5.8 0-7.6.5a2.8 2.8 0 0 0-2 2C1.9 9 1.9 12 1.9 12s0 3 .5 4.8a2.8 2.8 0 0 0 2 2c1.8.5 7.6.5 7.6.5s5.8 0 7.6-.5a2.8 2.8 0 0 0 2-2c.5-1.8.5-4.8.5-4.8s0-3-.5-4.8ZM10 15.5v-7l6 3.5-6 3.5Z"/></svg></a>
 </div>;
 return <main>
 <header><div className="brand"><img className="rdLogo" src="/rohilla-drive-logo.svg" alt="Rohilla Drive"/><small>by Rohilla Multibrand Cars</small></div><nav><a href="#inventory">Inventory</a><a href="#network">Vehicle Network</a><a href="#services">Services</a><a href="#mobility">Mobility</a><a href="#about">About</a></nav><div className="topActions"><a className="call" href="/verify">🔎 Verify Vehicle</a>{socialLinks}<button className="waTop" onClick={()=>whatsapp("Hello Rohilla Drive, I want to know about available vehicles.")}>WhatsApp</button></div></header>
 <section className="hero"><div className="heroText"><span>ROHILLA DRIVE • COMPLETE VEHICLE & MOBILITY NETWORK</span><h1>You don't just own a vehicle.<br/><span className="lifeLine">You manage its entire life.</span></h1><p className="heroSub">Buy • Verify • Drive • Maintain • Protect • Sell</p><p>One trusted network for cars, two-wheelers, commercial vehicles, fleets and future mobility.</p><div className="positioning"><span>Vehicle Passport</span><span>Verification</span><span>Cars</span><span>Two-Wheelers</span><span>Commercial</span><span>Fleet & Transporters</span><span>EV</span><span>Dealer Network</span><span>Provider Network</span></div><div className="search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search current inventory by brand, model, year or city..."/><select value={fuel} onChange={e=>setFuel(e.target.value)}><option>All</option><option>Petrol</option><option>Diesel</option><option>CNG</option><option>Electric</option><option>Hybrid</option></select><button onClick={()=>document.getElementById("inventory")?.scrollIntoView({behavior:"smooth"})}>Search Inventory</button></div></div></section>
 <section className="section" id="network"><div className="head"><div><h2>Complete Automobile Network</h2><p>Rohilla Drive is built for the complete vehicle ecosystem — not only personal cars.</p></div></div><div className="vehicleVerticals">{verticals.map(v=><button key={v[1]} onClick={()=>openServiceLead(v[3])}><span>{v[0]}</span><b>{v[1]}</b><small>{v[2]}</small></button>)}</div></section>
 <section className="section"><div className="quickLead"><div><h2>🔎 Vehicle Verification</h2><p>Official-source vehicle information, challans and available compliance records for supported vehicle categories.</p></div><div className="quickLeadBtns"><a className="call" href="/verify">Verify a Vehicle</a></div></div></section>
 <section className="section" id="inventory"><div className="head"><div><h2>Live Vehicle Inventory</h2><p>{loading?"Loading available vehicles...":`${filteredCars.length} vehicles available`}</p></div></div>{loading?<p>Loading inventory...</p>:filteredCars.length===0?<div className="card"><div className="body"><h3>No matching vehicles found</h3><p>Try another brand, model, fuel type or city.</p></div></div>:<div className="grid">{filteredCars.map(car=>{const photos=[...(car.vehicle_photos||[])].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));return <article className="card" key={car.id}><div className="photo real swipeGallery">{photos.length?photos.map((photo,index)=><img key={photo.url||index} src={photo.url} alt={`${car.brand} ${car.model} photo ${index+1}`}/>):<span>🚘</span>}</div>{photos.length>1&&<div className="swipeHint">← Swipe →</div>}<div className="body"><label>ROHILLA DRIVE</label><h3>{car.brand} {car.model}</h3>{car.variant&&<p>{car.variant}</p>}<small>{car.year} • {Number(car.km).toLocaleString("en-IN")} km • {car.fuel}{car.owner_count?` • ${car.owner_count} Owner`:""}</small><strong>₹{Number(car.asking_price).toLocaleString("en-IN")}</strong><a className="call" href={`/cars/${car.id}`} style={{display:"block",textAlign:"center",marginBottom:"10px"}}>View Details</a><button onClick={()=>whatsapp(`ROHILLA DRIVE VEHICLE ENQUIRY\n\nVehicle: ${car.brand} ${car.model} ${car.variant||""}\nYear: ${car.year}\nKM: ${car.km}\nFuel: ${car.fuel}\nPrice: ₹${car.asking_price}\nCity: ${car.city||""}\nVehicle ID: ${car.id}\n\nI am interested in this vehicle.`)}>WhatsApp Enquiry</button></div></article>})}</div>}</section>
 <section className="section"><div className="quickLead"><div><h2>Looking for a specific vehicle?</h2><p>Car, bike, commercial vehicle or fleet requirement — tell us what you need.</p></div><div className="quickLeadBtns"><button onClick={()=>openLead("vehicle purchase")}>Find a Vehicle</button><button className="secondary" onClick={()=>openLead("vehicle sale")}>Sell Your Vehicle</button></div></div></section>
 <section className="section" id="services"><div className="head"><div><h2>Vehicle Life Services</h2><p>One network to manage the complete life of your vehicle.</p></div></div><div className="services"><button onClick={()=>openServiceLead("vehicle inspection")}>🔍 Inspection</button><button onClick={()=>openServiceLead("vehicle finance")}>💳 Finance</button><button onClick={()=>openServiceLead("insurance")}>🛡️ Insurance</button><button onClick={()=>openServiceLead("RC / ownership transfer")}>📄 RC Transfer</button><button onClick={()=>openServiceLead("vehicle detailing")}>✨ Detailing</button><button onClick={()=>openServiceLead("workshop service")}>🔧 Workshop</button><button onClick={()=>openServiceLead("RSA assistance")}>🚨 RSA</button><button onClick={()=>openServiceLead("vehicle exchange")}>🔄 Exchange</button><button onClick={()=>openServiceLead("commercial permit / fitness support")}>📋 Permit & Fitness</button><button onClick={()=>openServiceLead("fleet maintenance")}>🛠️ Fleet Maintenance</button><a className="call" href="/verify" style={{textAlign:"center"}}>🔎 Vehicle Verification</a></div></section>
 <section className="section" id="mobility"><div className="head"><div><h2>Mobility Network</h2><p>Personal mobility, shared mobility and commercial fleet support in one ecosystem.</p></div></div><div className="mobility"><button onClick={()=>openServiceLead("self-drive rental")}>🚘 Self-Drive Rental</button><button onClick={()=>openServiceLead("taxi / cab")}>🚕 Taxi / Cab</button><button onClick={()=>openServiceLead("chauffeur service")}>🧑‍✈️ Chauffeur</button><button onClick={()=>openServiceLead("fleet / corporate mobility")}>🏢 Fleet & Corporate Mobility</button><button onClick={()=>openServiceLead("transporter network")}>🚛 Transporter Network</button><button onClick={()=>openServiceLead("EV mobility")}>⚡ EV Mobility</button></div></section>
 <section className="section dark" id="about"><div className="about"><h2>ROHILLA DRIVE</h2><p className="brandPromise">Complete Vehicle & Mobility Network.</p><p>From a scooter or personal car to a commercial fleet, Rohilla Drive connects vehicle discovery, verification, ownership support, services, mobility, dealers and approved providers through one platform.</p><div className="aboutGrid"><div><h3>Own</h3><p>Discover, buy, sell and verify multiple vehicle categories.</p></div><div><h3>Manage</h3><p>Connect compliance, maintenance, protection and vehicle-life support.</p></div><div><h3>Operate</h3><p>Support dealers, service providers, transporters and fleets through one network.</p></div></div></div></section>
 <footer><img className="rdFooterLogo" src="/rohilla-drive-logo.svg" alt="Rohilla Drive"/><div className="footerCopy"><p>Complete Vehicle & Mobility Network<br/>by Rohilla Multibrand Cars • Ambala City</p><p><a href="tel:7015260003">7015260003</a></p><div className="footerSocial">{socialLinks}</div></div></footer>
 <button className="floatingWa" onClick={()=>whatsapp("Hello Rohilla Drive, I want to enquire about your vehicles and services.")}>WhatsApp</button>
 {leadOpen&&<div className="overlay"><div className="modal"><button className="x" onClick={()=>setLeadOpen(false)}>×</button><h2>{leadType==='vehicle purchase'?'Find a Vehicle':leadType==='vehicle sale'?'Sell Your Vehicle':`Request ${leadType}`}</h2><p>{leadType==='vehicle purchase'||leadType==='vehicle sale'?"Tell us your requirement and our team will contact you.":"Your details stay with ROHILLA DRIVE. We will match and coordinate a verified service provider; your phone number is not exposed to the provider."}</p><form onSubmit={submitLead}><input value={leadName} onChange={e=>setLeadName(e.target.value)} placeholder="Your name" required/><input value={leadPhone} onChange={e=>setLeadPhone(e.target.value)} placeholder="Mobile number" inputMode="tel" required/><input value={leadLocation} onChange={e=>setLeadLocation(e.target.value)} placeholder="City / Location" required/><input value={leadTime} onChange={e=>setLeadTime(e.target.value)} placeholder="Preferred time (optional)"/><textarea value={leadMessage} onChange={e=>setLeadMessage(e.target.value)} rows={5} required/><button type="submit" disabled={leadBusy}>{leadBusy?'Submitting…':leadType==='vehicle purchase'||leadType==='vehicle sale'?'Continue on WhatsApp':'Submit Request'}</button></form></div></div>}
 </main>
}
