"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../supabaseClient";

function toDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
export default function VehicleAI(){
 const db=supabase();const [ready,setReady]=useState(false);const [files,setFiles]=useState<File[]>([]);const [result,setResult]=useState<any>(null);const [prompt,setPrompt]=useState("Extract visible vehicle and listing details. Flag number-plate privacy and clearly separate unknown or uncertain fields.");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Administrator login required.");return}const [{data:aal},{data:isAdmin}]=await Promise.all([db.auth.mfa.getAuthenticatorAssuranceLevel(),db.rpc("is_admin")]);if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Administrator authentication is required.");return}setReady(true)})()},[]);
 async function analyse(){if(!files.length)return;setBusy(true);setMsg("Analysing selected images…");try{const {data:{session}}=await db.auth.getSession();if(!session)throw new Error("Administrator session expired");const images=await Promise.all(files.slice(0,6).map(toDataUrl));const r=await fetch("/api/ai/vehicle-understand",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({prompt,images})});const j=await r.json();if(!j.configured){setMsg(j.error||"Vehicle intelligence provider is not connected.");setResult(null);return}if(!r.ok)throw new Error(j.error||"Image analysis failed");setResult(j.result);setMsg(`Analysis completed using ${j.model||"the configured provider"}. Verify every field before use.`)}catch(err:any){setMsg(err?.message||"Image analysis failed") }finally{setBusy(false)}}
 async function copy(){await navigator.clipboard.writeText(JSON.stringify(result,null,2));setMsg("Structured result copied.")}
 if(!ready)return <main><section className="section"><h1>Vehicle Intelligence</h1><p>{msg||"Checking secure access…"}</p><a href="/admin">Back to Administration</a></section></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE ADMIN</b><small>Vehicle Intelligence</small></div><div className="row"><a className="call" href="/admin/poster-scan">Listing Assistant</a><a className="call" href="/admin">Administration</a></div></header><section className="hero"><div className="heroText"><span>IMAGE ANALYSIS • PRIVACY CHECK • HUMAN REVIEW</span><h1>Vehicle and listing image analysis</h1><p>Review vehicle photos, listing posters or document images to extract visible information, identify privacy concerns and separate uncertain fields from confirmed observations.</p></div></section><section className="section"><div className="adminForm"><label className="upload">Vehicle, poster or document images (maximum 6)<input type="file" accept="image/*" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,6))}/></label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} style={{minHeight:110}}/><button onClick={analyse} disabled={!files.length||busy}>{busy?"Analysing…":`Analyse ${files.length||0} Image${files.length===1?"":"s"}`}</button></div>{msg&&<div className="notice">{msg}</div>}</section>{result&&<section className="section"><div className="head"><div><h2>Structured Analysis</h2><p>Human verification is required before publishing information or making document, ownership or compliance claims.</p></div><button onClick={copy}>Copy Structured Data</button></div><div className="grid">{Object.entries(result).map(([k,v])=><article className="application" key={k}><label>{k.replace(/_/g," ")}</label><p style={{whiteSpace:"pre-wrap",wordBreak:"break-word"}}>{Array.isArray(v)?v.join(" • "):typeof v==="object"?JSON.stringify(v):String(v??"—")}</p></article>)}</div></section>}<section className="section dark"><div className="about"><h2>Verification standard</h2><p>Image analysis can identify visible information, but it must not infer hidden registration details or treat a document image as proof of legal ownership. RC validity, challans, finance and title status require the appropriate verification workflow.</p></div></section></main>
}
