"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../supabaseClient";

function toDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
export default function VehicleAI(){
 const db=supabase();const [ready,setReady]=useState(false);const [files,setFiles]=useState<File[]>([]);const [result,setResult]=useState<any>(null);const [prompt,setPrompt]=useState("Extract visible vehicle/listing details. Flag number-plate privacy and clearly separate unknown or uncertain fields.");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Admin login required.");return}const [{data:aal},{data:isAdmin}]=await Promise.all([db.auth.mfa.getAuthenticatorAssuranceLevel(),db.rpc("is_admin")]);if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Admin + Authenticator verification required.");return}setReady(true)})()},[]);
 async function analyse(){if(!files.length)return;setBusy(true);setMsg("Rohilla Intelligence is analysing the images…");try{const {data:{session}}=await db.auth.getSession();if(!session)throw new Error("Admin session expired");const images=await Promise.all(files.slice(0,6).map(toDataUrl));const r=await fetch("/api/ai/vehicle-understand",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({prompt,images})});const j=await r.json();if(!j.configured){setMsg(j.error||"Multimodal AI provider is not connected yet.");setResult(null);return}if(!r.ok)throw new Error(j.error||"AI analysis failed");setResult(j.result);setMsg(`Analysis ready ✓ ${j.model||"Rohilla AI"}. Verify every field before using it.`)}catch(err:any){setMsg(err?.message||"AI analysis failed") }finally{setBusy(false)}}
 async function copy(){await navigator.clipboard.writeText(JSON.stringify(result,null,2));setMsg("Structured result copied ✓")}
 if(!ready)return <main><section className="section"><h1>Rohilla Vehicle AI</h1><p>{msg||"Checking secure access…"}</p><a href="/admin">Back to Admin</a></section></main>;
 return <main><header><div className="brand"><b>ROHILLA INTELLIGENCE</b><small>Multimodal Vehicle / Poster / Document Understanding</small></div><div className="row"><a className="call" href="/admin/poster-scan">Poster Scan</a><a className="call" href="/admin">Control Room</a></div></header><section className="hero"><div className="heroText"><span>IMAGE → FACTS → PRIVACY → HUMAN VERIFY</span><h1>Understand the vehicle, not just the poster text.</h1><p>Upload vehicle photos, listing posters or document images. Rohilla Intelligence extracts only visible facts, flags plate/privacy issues and returns unknown fields as unknown instead of guessing.</p></div></section><section className="section"><div className="adminForm"><label className="upload">Vehicle / poster / document images (max 6)<input type="file" accept="image/*" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,6))}/></label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} style={{minHeight:110}}/><button onClick={analyse} disabled={!files.length||busy}>{busy?"Analysing…":`Analyse ${files.length||0} Image${files.length===1?"":"s"}`}</button></div>{msg&&<div className="notice">{msg}</div>}</section>{result&&<section className="section"><div className="head"><div><h2>Structured Vehicle Understanding</h2><p>Human verification is mandatory before publishing or making document/ownership claims.</p></div><button onClick={copy}>Copy JSON</button></div><div className="grid">{Object.entries(result).map(([k,v])=><article className="application" key={k}><label>{k.replace(/_/g," ")}</label><p style={{whiteSpace:"pre-wrap",wordBreak:"break-word"}}>{Array.isArray(v)?v.join(" • "):typeof v==="object"?JSON.stringify(v):String(v??"—")}</p></article>)}</div></section>}<section className="section dark"><div className="about"><h2>Privacy rule</h2><p>AI may flag a visible registration plate, but it must not invent hidden characters or treat a document image as proof of legal ownership. RC validity, challans, finance and title status should use official verification workflows.</p></div></section></main>
}
