export const metadata={title:"Terms & Conditions",description:"Terms for using ROHILLA DRIVE vehicle, dealer, partner and automotive coordination services.",alternates:{canonical:"/terms"}};

const sectionStyle={background:"#fff",border:"1px solid #d9dee8",borderRadius:18,padding:22,marginBottom:14,lineHeight:1.65,color:"#334155"} as const;

export default function TermsPage(){return <main style={{maxWidth:960,margin:"0 auto",padding:"100px 18px 56px",fontFamily:"Arial,Helvetica,sans-serif"}}>
  <a href="/" style={{fontWeight:800}}>← ROHILLA DRIVE</a>
  <h1 style={{fontSize:"clamp(32px,6vw,54px)",marginBottom:6}}>Terms & Conditions</h1>
  <p style={{color:"#64748b"}}>Effective: 9 September 2026</p>

  <section style={sectionStyle}><h2>1. About Rohilla Drive</h2><p>ROHILLA DRIVE is an automotive vehicle-and-services network operated under the Rohilla Multibrand Cars business name in Ambala City, Haryana. The platform helps customers, individual sellers, dealers and automotive businesses connect, submit requirements, manage workflows and coordinate vehicle-related services.</p><p>Unless a specific transaction clearly says otherwise, Rohilla Drive acts as a coordination, listing, referral or workflow platform and is not the manufacturer, government authority, RTO, lender, insurer or final service provider.</p></section>

  <section style={sectionStyle}><h2>2. Accuracy of information</h2><p>Users, sellers, dealers and partners must provide truthful, current and lawful information. Vehicle ownership, registration, condition, mileage, service history, authorisations, licences, prices and availability may originate from the person or business submitting them. Rohilla Drive may review information but platform approval does not by itself certify that information as legally or technically verified.</p></section>

  <section style={sectionStyle}><h2>3. Vehicle listings and transactions</h2><p>Published listings are informational unless a separate written commitment says otherwise. Buyers should independently inspect the vehicle, verify ownership and documents, confirm price and payment terms, and complete legally required transfer formalities before concluding a transaction. Sellers remain responsible for having the right to sell or list the vehicle. Rohilla Drive does not guarantee condition, title, mileage, market value or future performance merely because a vehicle appears on the platform.</p></section>

  <section style={sectionStyle}><h2>4. New vehicles</h2><p>New-vehicle assistance may route a requirement to relevant participating OEM or authorised dealership teams. Stock, final on-road price, discount, finance, exchange valuation, delivery date, warranty and accessories are controlled by the relevant authorised seller and are not guaranteed by Rohilla Drive.</p></section>

  <section style={sectionStyle}><h2>5. Verification and official records</h2><p>Vehicle verification is an informational assistance service based on records that can be lawfully accessed and, where applicable, checks coordinated with authorised sources or partners. Rohilla Drive is not a government authority and a verification report is not a government certificate, legal title opinion or absolute guarantee that no undisclosed issue exists. Unavailable or inaccessible records must not be treated as clear records.</p></section>

  <section style={sectionStyle}><h2>6. Finance, insurance and regulated services</h2><p>Where a customer asks for finance, insurance or another regulated service, Rohilla Drive may coordinate a handoff only to an appropriately authorised or licensed provider when such a provider is available. The provider is responsible for eligibility, advice, documentation, pricing, approval, policy or loan terms and regulatory compliance. Rohilla Drive does not guarantee finance or insurance approval and does not present itself as a lender or insurer.</p></section>

  <section style={sectionStyle}><h2>7. Dealers and business partners</h2><p>Dealer or Partner approval grants access to relevant Rohilla Drive workflows; it is not an OEM, government, professional or statutory certification. Businesses are responsible for maintaining every registration, permit, licence, tax requirement, OEM authorisation and insurance required for their activity. A business must not misrepresent its status or use customer information outside the assigned purpose.</p></section>

  <section style={sectionStyle}><h2>8. Fees and payments</h2><p>No fee should be treated as payable merely because a user submits an enquiry or creates an account. If Rohilla Drive charges for a specific service, the applicable amount and material conditions should be disclosed before payment. Government charges, dealer/provider charges and Rohilla Drive charges, where applicable, should be distinguished. Any statutory consumer cancellation, refund or remedy rights remain unaffected.</p></section>

  <section style={sectionStyle}><h2>9. Accounts and acceptable use</h2><p>Users are responsible for keeping account credentials secure and for activity under their account. Do not submit false documents, impersonate another person or business, scrape protected data, bypass access controls, misuse customer details, interfere with platform security or use Rohilla Drive for unlawful activity.</p></section>

  <section style={sectionStyle}><h2>10. Availability and third-party services</h2><p>Platform features, partner availability and external services may change or be temporarily unavailable. WhatsApp, government portals, payment services, social networks, OEM/dealer systems and other external services operate under their own terms and availability.</p></section>

  <section style={sectionStyle}><h2>11. Responsibility and consumer rights</h2><p>Rohilla Drive will use reasonable care in operating the platform, but information and third-party outcomes can change. Nothing in these terms excludes rights or remedies that cannot lawfully be excluded under applicable Indian law. To the extent permitted by law, Rohilla Drive is not responsible for losses caused solely by false third-party information, independent third-party acts, or a user proceeding contrary to clear warnings or verification requirements.</p></section>

  <section style={sectionStyle}><h2>12. Law, updates and contact</h2><p>These terms are governed by applicable laws of India. Any forum or jurisdiction clause is subject to mandatory consumer and statutory rights. We may update these terms when the platform or legal requirements change; the effective date will be updated on this page.</p><p><b>Contact:</b> ROHILLA DRIVE / Rohilla Multibrand Cars, Ambala City, Haryana • Phone/WhatsApp: <a href="tel:+917015260003">+91 70152 60003</a>.</p></section>
</main>}
