export const metadata={title:"Terms & Conditions",description:"Terms for using ROHILLA DRIVE vehicle, dealer, partner and automotive services.",alternates:{canonical:"/terms"}};

const sectionStyle={background:"#fff",border:"1px solid #d9dee8",borderRadius:18,padding:22,marginBottom:14,lineHeight:1.65,color:"#334155"} as const;

export default function TermsPage(){return <main style={{maxWidth:960,margin:"0 auto",padding:"100px 18px 56px",fontFamily:"Arial,Helvetica,sans-serif"}}>
  <a href="/" style={{fontWeight:800}}>← ROHILLA DRIVE</a>
  <h1 style={{fontSize:"clamp(32px,6vw,54px)",marginBottom:6}}>Terms & Conditions</h1>
  <p style={{color:"#64748b"}}>Effective: 9 September 2026</p>

  <section style={sectionStyle}><h2>1. About Rohilla Drive and our role</h2><p>ROHILLA DRIVE is an automotive vehicle-and-services network operated under the Rohilla Multibrand Cars business name in Ambala City, Haryana. It supports customers, individual sellers, dealers and automotive businesses with vehicle discovery, selling, enquiries, verification assistance, service coordination and business workflows.</p><p>Our role can differ by transaction. Rohilla Multibrand Cars may, where clearly stated, act as the direct buyer or seller of a vehicle. In other cases, Rohilla Drive may act as a listing, coordination, lead, referral or workflow platform connecting independent buyers, sellers, dealers or service providers. The applicable role should be clear from the relevant listing, quotation, invoice, receipt, deal communication or service confirmation.</p></section>

  <section style={sectionStyle}><h2>2. Information and user responsibilities</h2><p>Users, sellers, dealers and partners must provide truthful, current and lawful information. Vehicle ownership, registration, condition, mileage, service history, authorisations, licences, prices and availability may originate from the person or business submitting them. A platform review, account approval or listing publication does not by itself certify that every submitted fact is legally or technically verified.</p></section>

  <section style={sectionStyle}><h2>3. Pre-owned vehicle listings and transactions</h2><p>For third-party listings, buyers should independently inspect the vehicle, verify ownership and documents, confirm price and payment terms, and complete legally required transfer formalities before concluding a transaction. Sellers remain responsible for having the right to sell or list the vehicle.</p><p>Where Rohilla Multibrand Cars is the direct buyer or seller, the specific written commitments made for that transaction, together with applicable law, govern that direct deal. General platform disclaimers do not cancel a commitment that Rohilla Multibrand Cars expressly makes in a direct transaction.</p></section>

  <section style={sectionStyle}><h2>4. New-vehicle assistance</h2><p>Rohilla Drive may route a new-vehicle requirement to participating OEM or authorised dealership teams. Rohilla Drive portal access or approval does not itself mean that Rohilla Drive is an OEM-authorised dealer, and it does not certify another business as authorised unless that status has been appropriately established. Stock, final on-road price, discounts, finance, exchange valuation, delivery date, warranty and accessories remain subject to the relevant authorised seller's confirmation.</p></section>

  <section style={sectionStyle}><h2>5. Verification and official records</h2><p>Vehicle verification and risk-review features are informational assistance services based on information that can be lawfully accessed or reasonably checked, including information coordinated with authorised sources or partners where applicable. Rohilla Drive is not an RTO, transport department or other government authority. A Rohilla Drive report is not a government certificate, legal title opinion or absolute guarantee that no undisclosed issue exists. Missing, delayed or inaccessible records must not be treated as clear records.</p></section>

  <section style={sectionStyle}><h2>6. Finance, insurance and other regulated services</h2><p>Rohilla Drive may facilitate or refer a customer requirement to an appropriately authorised or licensed provider where such a provider is available. Unless a separate legally authorised arrangement is expressly disclosed, Rohilla Drive does not act as a lender or insurer and does not guarantee eligibility, approval, pricing, policy issuance or loan terms. The relevant provider is responsible for its regulated product, advice, documentation and compliance.</p></section>

  <section style={sectionStyle}><h2>7. Dealers and business partners</h2><p>Dealer or Partner approval grants access to relevant Rohilla Drive workflows; it is not an OEM, government, professional or statutory certification. Businesses remain responsible for every registration, permit, licence, tax obligation, OEM authorisation, insurance and safety requirement applicable to their activity. They must not misrepresent their status or use customer information outside the permitted purpose.</p></section>

  <section style={sectionStyle}><h2>8. Fees, paid features, commissions and refunds</h2><p>Some enquiries or account features may be offered without charge, while other services may carry a disclosed fee. Paid services may include, depending on what is offered at the time, verification, listing or promotion tools, dealer or partner access, service coordination, lead or referral fees, success or facilitation fees, subscriptions or other automotive services.</p><p>Before a payment is requested, the applicable Rohilla Drive charge and the material conditions for that paid service should be disclosed. Government charges and independent dealer/provider charges should be identified separately where relevant. Cancellation, refund and remedy rights depend on the specific service, the stage of performance and applicable law; nothing here removes statutory consumer rights.</p></section>

  <section style={sectionStyle}><h2>9. Accounts and acceptable use</h2><p>Users are responsible for keeping account credentials secure and for activity under their account. Do not submit false documents, impersonate another person or business, scrape protected data, bypass access controls, misuse customer details, interfere with platform security or use Rohilla Drive for unlawful, fraudulent or misleading activity.</p></section>

  <section style={sectionStyle}><h2>10. Communications and external services</h2><p>If a user chooses phone, WhatsApp, email or another available channel, Rohilla Drive and the relevant participating business may use that channel for the requested enquiry or workflow. WhatsApp, payment services, maps, social networks, government portals, OEM/dealer systems and other external services are independently operated under their own terms, privacy practices and availability.</p></section>

  <section style={sectionStyle}><h2>11. Platform availability</h2><p>Features, inventory, partner availability and third-party integrations may change, be suspended or be temporarily unavailable. Rohilla Drive may update, improve or discontinue a feature where reasonably necessary, subject to any obligations already accepted for a paid or direct transaction.</p></section>

  <section style={sectionStyle}><h2>12. Responsibility and consumer rights</h2><p>Rohilla Drive will use reasonable care in operating its own platform and in commitments it directly makes. Independent third parties remain responsible for their own listings, workmanship, advice, products and representations. To the extent permitted by law, Rohilla Drive is not responsible for loss caused solely by false third-party information, an independent third-party act, or a user proceeding contrary to clear warnings or verification requirements.</p><p>Nothing in these terms excludes or limits any consumer right, statutory warranty, remedy or liability that applicable Indian law does not permit to be excluded or limited.</p></section>

  <section style={sectionStyle}><h2>13. Complaints and support</h2><p>For a transaction, account, listing, privacy or service complaint, contact ROHILLA DRIVE / Rohilla Multibrand Cars at <a href="tel:+917015260003">+91 70152 60003</a> (phone/WhatsApp). Please provide the relevant account, enquiry, vehicle or transaction reference. Where a law prescribes a specific grievance process or timeline for the applicable service, that requirement will apply.</p></section>

  <section style={sectionStyle}><h2>14. Law and updates</h2><p>These terms are governed by applicable laws of India. Any forum or jurisdiction position is subject to mandatory consumer and statutory rights. We may update these terms as the platform, business model or applicable legal requirements change; the effective date will be updated on this page.</p></section>
</main>}
