import {notFound} from "next/navigation";
import LocaleContinue from "../components/LocaleContinue";
import CustomerBackBar from "../components/CustomerBackBar";

const site="https://www.rohilladrive.com";
const copy:Record<string,{name:string;title:string;body:string;continue:string;newVehicle:string;business:string;language:string}>={
 en:{name:"English",title:"One network for every vehicle journey.",body:"Buy, sell, verify, service, compare new vehicles and coordinate cross-state deals through Rohilla Drive.",continue:"Continue in English",newVehicle:"New Vehicle Assistance",business:"Business Hub",language:"Language Bridge"},
 hi:{name:"हिन्दी",title:"हर वाहन यात्रा के लिए एक भरोसेमंद नेटवर्क।",body:"Rohilla Drive पर वाहन खरीदें, बेचें, वेरिफाई कराएँ, सर्विस लें, नई गाड़ियों की तुलना करें और दूसरे राज्य की डील को भी एक जगह से मैनेज करें।",continue:"हिन्दी में जारी रखें",newVehicle:"नई गाड़ी सहायता",business:"बिज़नेस हब",language:"भाषा सहायता"},
 pa:{name:"ਪੰਜਾਬੀ",title:"ਹਰ ਵਾਹਨ ਯਾਤਰਾ ਲਈ ਇੱਕ ਭਰੋਸੇਯੋਗ ਨੈੱਟਵਰਕ।",body:"Rohilla Drive ਨਾਲ ਵਾਹਨ ਖਰੀਦੋ, ਵੇਚੋ, ਵੇਰੀਫਾਈ ਕਰੋ, ਸਰਵਿਸ ਲਵੋ, ਨਵੀਆਂ ਗੱਡੀਆਂ ਦੀ ਤੁਲਨਾ ਕਰੋ ਅਤੇ ਦੂਜੇ ਰਾਜ ਦੀ ਡੀਲ ਵੀ ਸੰਭਾਲੋ।",continue:"ਪੰਜਾਬੀ ਵਿੱਚ ਜਾਰੀ ਰੱਖੋ",newVehicle:"ਨਵੀਂ ਗੱਡੀ ਸਹਾਇਤਾ",business:"ਬਿਜ਼ਨਸ ਹੱਬ",language:"ਭਾਸ਼ਾ ਸਹਾਇਤਾ"},
 kn:{name:"ಕನ್ನಡ",title:"ಪ್ರತಿ ವಾಹನ ಪ್ರಯಾಣಕ್ಕೂ ಒಂದೇ ವಿಶ್ವಾಸಾರ್ಹ ನೆಟ್‌ವರ್ಕ್.",body:"Rohilla Drive ಮೂಲಕ ವಾಹನ ಖರೀದಿ, ಮಾರಾಟ, ಪರಿಶೀಲನೆ, ಸೇವೆ, ಹೊಸ ವಾಹನ ಹೋಲಿಕೆ ಮತ್ತು ರಾಜ್ಯಾಂತರ ಡೀಲ್ ಸಂಯೋಜನೆ ಮಾಡಿ.",continue:"ಕನ್ನಡದಲ್ಲಿ ಮುಂದುವರಿಸಿ",newVehicle:"ಹೊಸ ವಾಹನ ಸಹಾಯ",business:"ಬಿಸಿನೆಸ್ ಹಬ್",language:"ಭಾಷಾ ಸಹಾಯ"},
 ta:{name:"தமிழ்",title:"ஒவ்வொரு வாகன பயணத்திற்கும் ஒரே நம்பகமான வலைப்பின்னல்.",body:"Rohilla Drive மூலம் வாங்குதல், விற்பனை, சரிபார்ப்பு, சேவை, புதிய வாகன ஒப்பீடு மற்றும் மாநிலங்களுக்கு இடையேயான டீலை ஒரே இடத்தில் ஒருங்கிணைக்கலாம்.",continue:"தமிழில் தொடரவும்",newVehicle:"புதிய வாகன உதவி",business:"பிசினஸ் ஹப்",language:"மொழி உதவி"},
 te:{name:"తెలుగు",title:"ప్రతి వాహన ప్రయాణానికి ఒకే నమ్మకమైన నెట్‌వర్క్.",body:"Rohilla Drive ద్వారా కొనుగోలు, అమ్మకం, ధృవీకరణ, సర్వీస్, కొత్త వాహన పోలిక మరియు రాష్ట్రాల మధ్య డీల్‌ను సమన్వయం చేయండి.",continue:"తెలుగులో కొనసాగండి",newVehicle:"కొత్త వాహన సహాయం",business:"బిజినెస్ హబ్",language:"భాషా సహాయం"},
 ml:{name:"മലയാളം",title:"ഓരോ വാഹന യാത്രയ്ക്കും ഒരൊറ്റ വിശ്വസനീയ നെറ്റ്‌വർക്ക്.",body:"Rohilla Drive വഴി വാങ്ങൽ, വിൽപ്പന, പരിശോധന, സർവീസ്, പുതിയ വാഹന താരതമ്യം, സംസ്ഥാനാന്തര ഡീൽ ഏകോപനം എന്നിവ നടത്താം.",continue:"മലയാളത്തിൽ തുടരുക",newVehicle:"പുതിയ വാഹന സഹായം",business:"ബിസിനസ് ഹബ്",language:"ഭാഷാ സഹായം"},
 mr:{name:"मराठी",title:"प्रत्येक वाहन प्रवासासाठी एक विश्वासार्ह नेटवर्क.",body:"Rohilla Drive वर खरेदी, विक्री, पडताळणी, सर्व्हिस, नवीन वाहनांची तुलना आणि राज्याबाहेरील डीलचे समन्वयन करा.",continue:"मराठीत पुढे जा",newVehicle:"नवीन वाहन सहाय्य",business:"बिझनेस हब",language:"भाषा सहाय्य"},
 gu:{name:"ગુજરાતી",title:"દરેક વાહન યાત્રા માટે એક વિશ્વસનીય નેટવર્ક.",body:"Rohilla Drive દ્વારા ખરીદી, વેચાણ, ચકાસણી, સર્વિસ, નવી ગાડીની તુલના અને રાજ્ય બહારની ડીલનું સંકલન કરો.",continue:"ગુજરાતીમાં આગળ વધો",newVehicle:"નવી ગાડી સહાય",business:"બિઝનેસ હબ",language:"ભાષા સહાય"},
 bn:{name:"বাংলা",title:"প্রতিটি গাড়ির যাত্রার জন্য একটি বিশ্বস্ত নেটওয়ার্ক।",body:"Rohilla Drive-এর মাধ্যমে কেনা, বিক্রি, যাচাই, সার্ভিস, নতুন গাড়ির তুলনা এবং আন্তঃরাজ্য ডিল সমন্বয় করুন।",continue:"বাংলায় চালিয়ে যান",newVehicle:"নতুন গাড়ি সহায়তা",business:"বিজনেস হাব",language:"ভাষা সহায়তা"},
 or:{name:"ଓଡ଼ିଆ",title:"ପ୍ରତ୍ୟେକ ଯାନ ଯାତ୍ରା ପାଇଁ ଗୋଟିଏ ବିଶ୍ୱସନୀୟ ନେଟୱର୍କ।",body:"Rohilla Drive ମାଧ୍ୟମରେ କ୍ରୟ, ବିକ୍ରୟ, ଯାଞ୍ଚ, ସର୍ଭିସ, ନୂଆ ଯାନ ତୁଳନା ଏବଂ ଅନ୍ୟ ରାଜ୍ୟର ଡିଲ୍ ସମନ୍ୱୟ କରନ୍ତୁ।",continue:"ଓଡ଼ିଆରେ ଜାରି ରଖନ୍ତୁ",newVehicle:"ନୂଆ ଯାନ ସହାୟତା",business:"ବିଜନେସ ହବ",language:"ଭାଷା ସହାୟତା"},
 ur:{name:"اردو",title:"ہر گاڑی کے سفر کے لیے ایک قابلِ اعتماد نیٹ ورک۔",body:"Rohilla Drive کے ذریعے خرید، فروخت، تصدیق، سروس، نئی گاڑیوں کا موازنہ اور دوسری ریاست کی ڈیل کو ایک جگہ سے منظم کریں۔",continue:"اردو میں جاری رکھیں",newVehicle:"نئی گاڑی کی مدد",business:"بزنس ہب",language:"زبان کی مدد"}
};
const locales=Object.keys(copy);
export function generateStaticParams(){return locales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!copy[locale])return {};return {title:`ROHILLA DRIVE — ${copy[locale].name}`,description:copy[locale].body,alternates:{canonical:`/${locale}`,languages:Object.fromEntries(locales.map(l=>[l,`${site}/${l}`]))},openGraph:{url:`${site}/${locale}`,title:`ROHILLA DRIVE — ${copy[locale].name}`,description:copy[locale].body}}}
export default async function Page({params}:{params:Promise<{locale:string}>}){const {locale}=await params;const c=copy[locale];if(!c)notFound();return <main dir={locale==="ur"?"rtl":"ltr"}><CustomerBackBar/><header><div className="brand"><b>ROHILLA DRIVE</b><small>{c.name}</small></div></header><section className="hero"><div className="heroText"><span>ONE NETWORK • EVERY VEHICLE • EVERY LANGUAGE</span><h1>{c.title}</h1><p>{c.body}</p><div className="row"><LocaleContinue locale={locale} label={c.continue}/><a className="call" href="/language-assist">{c.language}</a></div></div></section><section className="section"><div className="grid"><article className="application"><h2>{c.newVehicle}</h2><p>OEM / authorised dealer comparison, quote, exchange, finance and delivery coordination.</p><a className="call" href="/new-vehicles">{c.newVehicle} →</a></article><article className="application"><h2>{c.business}</h2><p>OEM dealers, pre-owned dealers and automotive service businesses can register directly.</p><a className="call" href="/business-hub">{c.business} →</a></article><article className="application"><h2>Rohilla Cross-State Assist</h2><p>Inspection, documents, transport and delivery can stay in one multilingual Deal Room.</p><a className="call" href="/language-assist">{c.language} →</a></article></div></section></main>}
