"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../supabaseClient";

type Car={id:string;brand:string;model:string;variant?:string;year?:number;status:string;asking_price?:number;city?:string};
type Row={id:string;purchase_price?:number|null;purchase_date?:string|null;refurbishment_cost?:number|null;transport_cost?:number|null;other_cost?:number|null;sale_price?:number|null;sale_date?:string|null;buyer_private?:any;seller_private?:any;rc_status?:string|null;rc_transfer_date?:string|null;internal_notes?:string|null;total_cost?:number|null;margin?:number|null};
const money=(n:any)=>`₹${Number(n||0).toLocaleString("en-IN")}`;

export default function DealerFinance(){
 const db=supabase();const [ready,setReady]=useState(false);const [cars,setCars]=useState<Car[]>([]);const [rows,setRows]=useState<Record<string,Row>>({});const [edit,setEdit]=useState<any>(null);const [msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Dealer sign-in is required.");return}const {data:p}=await db.from("profiles").select("role,active").eq("id",session.user.id).single();if(!p||p.role!=="dealer"||!p.active){setMsg("Approved Dealer Workspace access is required.");return}setReady(true);await load(session.user.id)})()},[]);
 async function load(uid?:string){const userId=uid||(await db.auth.getSession()).data.session?.user.id;if(!userId)return;const [a,b]=await Promise.all([db.from("vehicles").select("id,brand,model,variant,year,status,asking_price,city").eq("partner_id",userId).order("created_at",{ascending:false}),db.from("vehicle_private").select("*")]);if(a.error){setMsg(a.error.message);return}if(b.error){setMsg(b.error.message);return}setCars((a.data||[]) as Car[]);const m:Record<string,Row>={};(b.data||[]).forEach((x:any)=>m[x.id]=x);setRows(m)}
 function open(c:Car){const r=rows[c.id];setEdit({id:c.id,purchase_price:r?.purchase_price??"",purchase_date:r?.purchase_date||"",refurbishment_cost:r?.refurbishment_cost??0,transport_cost:r?.transport_cost??0,other_cost:r?.other_cost??0,sale_price:r?.sale_price??"",sale_date:r?.sale_date||"",seller_name:r?.seller_private?.name||"",seller_phone:r?.seller_private?.phone||"",buyer_name:r?.buyer_private?.name||"",buyer_phone:r?.buyer_private?.phone||"",rc_status:r?.rc_status||"pending",rc_transfer_date:r?.rc_transfer_date||"",internal_notes:r?.internal_notes||""});setMsg("")}
 function calc(x:any){const total=Number(x.purchase_price||0)+Number(x.refurbishment_cost||0)+Number(x.transport_cost||0)+Number(x.other_cost||0);return {total,margin:Number(x.sale_price||0)-total}}
 async function save(e:React.FormEvent){e.preventDefault();if(!edit)return;setMsg("Saving vehicle ledger…");const payload={id:edit.id,purchase_price:edit.purchase_price===""?null:Number(edit.purchase_price),purchase_date:edit.purchase_date||null,refurbishment_cost:Number(edit.refurbishment_cost||0),transport_cost:Number(edit.transport_cost||0),other_cost:Number(edit.other_cost||0),sale_price:edit.sale_price===""?null:Number(edit.sale_price),sale_date:edit.sale_date||null,seller_private:{name:edit.seller_name||null,phone:edit.seller_phone||null},buyer_private:{name:edit.buyer_name||null,phone:edit.buyer_phone||null},rc_status:edit.rc_status||"pending",rc_transfer_date:edit.rc_transfer_date||null,internal_notes:edit.internal_notes||null,updated_at:new Date().toISOString()};const {error}=await db.from("vehicle_private").upsert(payload,{onConflict:"id"});if(error){setMsg(error.message);return}setMsg("Vehicle ledger updated.");setEdit(null);await load()}
 const totals=useMemo(()=>cars.reduce((a,c)=>{const r=rows[c.id];a.stock+=c.status!=="sold"?Number(r?.total_cost||0):0;a.sales+=Number(r?.sale_price||0);a.margin+=r?.sale_price?Number(r?.margin||0):0;if(!["transferred","completed"].includes(String(r?.rc_status||"pending").toLowerCase()))a.rc++;return a},{stock:0,sales:0,margin:0,rc:0}),[cars,rows]);
 if(!ready)return <main><div className="auth"><h1>Vehicle Ledger & RC</h1><p>{msg||"Verifying Dealer Workspace access…"}</p><a href="/dealer">Return to Dealer Dashboard</a></div></main>;
 return <main><header><div className="brand"><b>VEHICLE LEDGER & RC</b><small>Transactions, margin and transfer tracking</small></div><div className="row"><a className="call" href="/dealer">Dashboard</a><button onClick={()=>db.auth.signOut().then(()=>location.href="/dealer")}>Sign Out</button></div></header>
 <section className="section"><h1>Transactions & Margin</h1><p>Your private ledger includes only vehicles associated with your approved dealer account. Other businesses and Rohilla Drive internal records remain restricted.</p><div className="stats-grid"><article className="stat-card"><strong>{money(totals.stock)}</strong><span>Stock Cost</span></article><article className="stat-card"><strong>{money(totals.sales)}</strong><span>Recorded Sales</span></article><article className="stat-card"><strong>{money(totals.margin)}</strong><span>Gross Margin</span></article><article className="stat-card"><strong>{totals.rc}</strong><span>RC Pending</span></article></div>{msg&&<div className="notice">{msg}</div>}</section>
 <section className="section"><h2>Vehicle Records ({cars.length})</h2><div className="grid">{cars.map(c=>{const r=rows[c.id];return <article className="card" key={c.id}><div className="body"><h3>{c.brand} {c.model} {c.variant||""}</h3><p>{c.year||""} • {c.city||""} • {c.status}</p><p>Purchase: <b>{money(r?.purchase_price)}</b><br/>Total Cost: <b>{money(r?.total_cost)}</b><br/>Sale: <b>{money(r?.sale_price)}</b><br/>Gross Margin: <b>{money(r?.sale_price?r?.margin:0)}</b></p><small>RC Status: {r?.rc_status||"pending"}{r?.rc_transfer_date?` • ${r.rc_transfer_date}`:""}</small><div className="row"><button onClick={()=>open(c)}>{r?"Edit Ledger / RC":"Add Ledger / RC"}</button></div></div></article>})}</div></section>
 {edit&&<div className="overlay"><div className="modal"><button className="x" onClick={()=>setEdit(null)}>×</button><h2>Vehicle Ledger</h2><form className="adminForm" onSubmit={save}><input type="number" placeholder="Purchase price ₹" value={edit.purchase_price} onChange={e=>setEdit({...edit,purchase_price:e.target.value})}/><input type="date" value={edit.purchase_date} onChange={e=>setEdit({...edit,purchase_date:e.target.value})}/><input type="number" placeholder="Refurbishment cost ₹" value={edit.refurbishment_cost} onChange={e=>setEdit({...edit,refurbishment_cost:e.target.value})}/><input type="number" placeholder="Transport cost ₹" value={edit.transport_cost} onChange={e=>setEdit({...edit,transport_cost:e.target.value})}/><input type="number" placeholder="Other cost ₹" value={edit.other_cost} onChange={e=>setEdit({...edit,other_cost:e.target.value})}/><input placeholder="Seller name" value={edit.seller_name} onChange={e=>setEdit({...edit,seller_name:e.target.value})}/><input placeholder="Seller phone" value={edit.seller_phone} onChange={e=>setEdit({...edit,seller_phone:e.target.value})}/><input type="number" placeholder="Sale price ₹" value={edit.sale_price} onChange={e=>setEdit({...edit,sale_price:e.target.value})}/><input type="date" value={edit.sale_date} onChange={e=>setEdit({...edit,sale_date:e.target.value})}/><input placeholder="Buyer name" value={edit.buyer_name} onChange={e=>setEdit({...edit,buyer_name:e.target.value})}/><input placeholder="Buyer phone" value={edit.buyer_phone} onChange={e=>setEdit({...edit,buyer_phone:e.target.value})}/><select value={edit.rc_status} onChange={e=>setEdit({...edit,rc_status:e.target.value})}><option value="pending">RC Pending</option><option value="documents_pending">Documents Pending</option><option value="submitted">Submitted</option><option value="in_process">In Process</option><option value="transferred">Transferred</option><option value="completed">Completed</option></select><input type="date" value={edit.rc_transfer_date} onChange={e=>setEdit({...edit,rc_transfer_date:e.target.value})}/><textarea placeholder="Private transaction notes" value={edit.internal_notes} onChange={e=>setEdit({...edit,internal_notes:e.target.value})}/><div className="application"><b>Current Calculation</b><p>Total Cost: {money(calc(edit).total)}<br/>Gross Margin: {money(calc(edit).margin)}</p></div><button>Save Vehicle Ledger</button></form></div></div>}
 </main>;
}
