import type {Metadata} from "next";
import {supabase} from "../../supabaseClient";
const site="https://www.rohilladrive.com";
export const revalidate=300;
export const metadata:Metadata={title:"Rohilla Multibrand Cars | Used Car Dealer in Ambala",description:"Rohilla Multibrand Cars in Baldev Nagar, Ambala — browse live used-car inventory, prices and vehicle details on Rohilla Drive.",alternates:{canonical:"/dealers/rohilla-multibrand-cars"}};
export default async function RohillaDealer(){
 const db=supabase();
 const {data}=await db.from("vehicles").select("id,brand,model,variant,year,asking_price,city").eq("status","published").eq("inventory_owner_type","rohilla_inventory").order("created_at",{ascending:false});
 const cars=(data||[]) as any[];
 const schema={"@context":"https://schema.org","@type":["AutoDealer","AutomotiveBusiness"],"@id":site+"/dealers/rohilla-multibrand-cars#dealer",name:"Rohilla Multibrand Cars",url:site+"/dealers/rohilla-multibrand-cars",telephone:"+91-7015260003",address:{"@type":"PostalAddress",streetAddress:"Near TR Sawhney Maruti Showroom, Jaggi Garden, Tagore Garden, Baldev Nagar",addressLocality:"Ambala",addressRegion:"Haryana",postalCode:"134007",addressCountry:"IN"},parentOrganization:{"@id":site+"/#organization"},hasOfferCatalog:{"@type":"OfferCatalog",name:"Published used cars",numberOfItems:cars.length,itemListElement:cars.map((c:any)=>({"@type":"Offer",itemOffered:{"@type":"Vehicle",name:[c.year,c.brand,c.model,c.variant].filter(Boolean).join(" "),url:site+"/cars/"+c.id},price:c.asking_price||undefined,priceCurrency:c.asking_price?"INR":undefined}))},sameAs:["https://www.instagram.com/rohillamultibrandcars/","https://www.google.com/search?kgmid=/g/11v13gyn6y&q=Rohilla+Multibrand+Cars"]};
 return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <section className="hero"><div className="heroText"><span>ROHILLA DRIVE DEALER</span><h1>Rohilla Multibrand Cars — Used Cars in Ambala</h1><p>Baldev Nagar, Ambala City. Browse our currently published pre-owned cars with direct vehicle details and enquiry options.</p><div className="row"><a className="call" href="/inventory">Browse All Cars</a><a className="secondary" href="https://wa.me/917015260003?text=Hi%2C%20I%20found%20Rohilla%20Multibrand%20Cars%20on%20Rohilla%20Drive.%20I%20want%20details%20about%20a%20used%20car.">WhatsApp 7015260003</a></div></div></section>
 <section className="section"><div className="head"><div><h2>Available Cars from Rohilla Multibrand Cars</h2><p>{cars.length} currently published vehicle{cars.length===1?"":"s"}.</p></div></div>{cars.length?<div className="grid">{cars.map(c=><article className="card" key={c.id}><div className="body"><h3>{[c.year,c.brand,c.model,c.variant].filter(Boolean).join(" ")}</h3><p>{c.city||"Ambala"}</p>{c.asking_price&&<strong>₹{Number(c.asking_price).toLocaleString("en-IN")}</strong>}<p><a className="textLink" href={"/cars/"+c.id}>View Vehicle →</a></p></div></article>)}</div>:<div className="notice">No vehicle is currently published. Send your requirement and we will help find a suitable car.</div>}</section>
 <section className="section dark"><div className="about"><h2>Rohilla Multibrand Cars, Ambala</h2><p>Rohilla Multibrand Cars is the Ambala used-car dealership connected with the Rohilla Drive automotive platform. Physical business location: Baldev Nagar, Ambala.</p><div className="row"><a className="call" href="/used-cars-ambala">Used Cars in Ambala</a><a className="secondary" href="/sell-car-ambala">Sell Your Car</a></div></div></section></main>
}