"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../supabaseClient";
const money=(n:any)=>n?`₹${Number(n).toLocaleString("en-IN")}`:"—";
export default function AdminNewVehicles(){
 const db=supabase();const [ready,setReady]=useState(false);const [leads,setLeads]=useState<any[]>([]);const [offers,setOffers]=useState<any[]>([]);const [msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:{session}}=await db.auth.getSession();if(!session){setMsg("Admin login required.");return}const {data:aal}=await db.auth.mfa.getAuthenticatorAssuranceLevel();const {data:isAdmin}=await db.rpc("is_admin");if(aal?.currentLevel!=="aal2"||!isAdmin){setMsg("Open Admin Control Room and complete Authenticator verification first.");return}setReady(true);await load()})()},[]);
 async function load(){const [a,b]=await Promise.all([db.from("leads").select("id,customer_name,customer_phone,requirement,message,status,source,vehicle_type,customer_city,budget,preferred_brand,preferred_model,created_at").eq("new_or_used","new").order("created_at",{ascending:false}),db.from("new_vehicle_offers").select("*,dealer:profiles!new_vehicle_offers_dealer_id_fkey(name,business_name,phone)").order("created_at",{ascending:false})]);if(a.error){setMsg(a.error.message);return}if(b.error){setMsg(b.error.message);return}setLeads(a.data||[]);setOffers(b.data||[])}
 async function mark(id:string,status:string){const {error}=await db.from("leads").update({status}).eq("id",id);if(error){setMsg(error.message);return}setMsg(`Requirement marked ${status} ✓`);await load()}
 if(!ready)return <main><section className="section"><h1>New Vehicle Network</h1><p>{msg||"Checking Admin access…"}</p><a href="/admin">Back to Admin</a></section></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE ADMIN</b><small>New Vehicle Quote Network</small></div><div className="row"><a className="call" href="/admin">Control Room</a><a className="call" href="/new-vehicles">Customer Flow</a></div></header><section className="section"><h1>Multi-Brand New Vehicle Demand</h1><p>Customer requirements on one side, competitive dealer offers on the other. Customer contact stays under Rohilla Drive control until you decide the handoff.</p>{msg&&<div className="notice">{msg}</div>}<button onClick={load}>Refresh</button></section><section className="section"><div className="grid">{leads.map(l=>{const os=offers.filter(o=>o.lead_id===l.id);return <article className="application" key={l.id}><label>{l.status} • {l.vehicle_type?.replace(/_/g," ")||"new vehicle"}</label><h2>{l.preferred_brand||"Any Brand"} {l.preferred_model||""}</h2><p><b>Customer:</b> {l.customer_name||"—"}<br/><b>Phone:</b> {l.customer_phone||"—"}<br/><b>City:</b> {l.customer_city||"—"}<br/><b>Budget:</b> {money(l.budget)}</p><p>{l.message||l.requirement}</p><h3>Dealer offers ({os.length})</h3>{os.length===0?<small>No dealer offer yet.</small>:os.map(o=><div className="notice" key={o.id}><b>{o.dealer?.business_name||o.dealer?.name||"Dealer"}</b><br/>On-road: <b>{money(o.on_road_price)}</b> • Discount {money(o.dealer_discount)} • Delivery {o.delivery_days?`${o.delivery_days} days`:"—"}<br/><small>{o.color_availability||""} {o.notes||""}</small></div>)}<div className="row"><button onClick={()=>mark(l.id,"qualified")}>Qualified</button><button onClick={()=>mark(l.id,"closed")}>Close</button><a className="call" href={`https://wa.me/91${String(l.customer_phone||"").replace(/\D/g,"")}?text=${encodeURIComponent(`ROHILLA DRIVE NEW VEHICLE ASSISTANCE\n\nWe have reviewed your ${l.preferred_brand||"new vehicle"} requirement. We are ready to discuss dealer options with you.`)}`} target="_blank">WhatsApp Customer</a></div></article>})}</div></section></main>
}
