"use client";
import {useEffect,useState} from "react";
import {supabase} from "../supabaseClient";

export default function Dealer(){
 const db=supabase();
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<any>(null),[mode,setMode]=useState<"login"|"signup"|"forgot">("login"),[m,setM]=useState(""),[cars,setCars]=useState<any[]>([]),[files,setFiles]=useState<File[]>([]),[f,setF]=useState<any>({});
 useEffect(()=>{db.auth.getSession().then(({data})=>{if(data.session){setSession(data.session);check(data.session)}})},[]);
 async function check(sess:any){const {data,error}=await db.from("profiles").select("*").eq("id",sess.user.id).single();if(error||!data){setM("Account profile is pending setup.");return}setProfile(data);if(data.role!=="dealer"){await db.auth.signOut();setSession(null);setM("This account is not a dealer account.")}else if(!data.active){setM("Your Dealer application is pending Admin approval.")}else load(sess.user.id)}
 async function load(userId=session?.user?.id){if(!userId)return;const {data}=await db.from("vehicles").select("*,vehicle_photos(url)").eq("partner_id",userId).order("created_at",{ascending:false});setCars(data||[])}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setM("Signing in…");const x=new FormData(e.currentTarget);const {data,error}=await db.auth.signInWithPassword({email:String(x.get("email")),password:String(x.get("password"))});if(error){setM(error.message);return}setSession(data.session);await check(data.session)}
 async function signup(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setM("Creating account…");const x=new FormData(e.currentTarget);const email=String(x.get("email")),password=String(x.get("password")),name=String(x.get("name")),mobile=String(x.get("mobile")),business=String(x.get("business_name")),city=String(x.get("city"));const {data,error}=await db.auth.signUp({email,password,options:{data:{network_role:"dealer",name,phone:mobile,business_name:business,address:String(x.get("address")),city,service_categories:"Vehicle Dealer"}}});if(error){setM(error.message);return}if(!data.user){setM("Account could not be created.");return}const {error:appError}=await db.from("dealer_applications").insert({applicant_user_id:data.user.id,business_name:business,contact_name:name,mobile,city,address:String(x.get("address")),inventory_count:Number(x.get("inventory_count")||0),services:String(x.get("services")||"Vehicle sales"),message:String(x.get("message")||""),status:"new"});if(appError){setM(appError.message);return}const wa=`ROHILLA DRIVE DEALER APPLICATION\n\nBusiness: ${business}\nContact: ${name}\nMobile: ${mobile}\nCity: ${city}\n\nMy Dealer application is submitted and waiting for Admin approval.`;window.location.href=`https://wa.me/917015260003?text=${encodeURIComponent(wa)}`}
 async function forgot(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setM("Sending reset link…");const email=String(new FormData(e.currentTarget).get("email"));const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});setM(error?error.message:"Password reset link sent to your email.")}
 async function add(e:React.FormEvent){e.preventDefault();if(files.length<1){setM("Add at least one photo");return}const {data,error}=await db.from("vehicles").insert({partner_id:session.user.id,brand:f.brand,model:f.model,variant:f.variant,year:Number(f.year),km:Number(f.km),fuel:f.fuel,owner_count:Number(f.owner_count),asking_price:Number(f.price),city:f.city,public_notes:f.notes||"",status:"draft"}).select().single();if(error){setM(error.message);return}for(let n=0;n<files.length;n++){const file=files[n],path=`${data.id}/${Date.now()}-${n}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"")}`,up=await db.storage.from("vehicle-photos").upload(path,file);if(up.error){setM(up.error.message);return}const pub=db.storage.from("vehicle-photos").getPublicUrl(path).data.publicUrl;await db.from("vehicle_photos").insert({vehicle_id:data.id,url:pub,sort_order:n,path})}setF({});setFiles([]);setM("Submitted to ROHILLA DRIVE for approval ✓");load()}
 if(!session||!profile||profile.role!=="dealer"||!profile.active)return <main><div className="auth"><h1>ROHILLA DRIVE Dealer Portal</h1><p>Approved dealers can login. New dealers can create an account and apply.</p>{mode==="login"&&<><form onSubmit={login}><input name="email" type="email" placeholder="Dealer email" required/><input name="password" type="password" placeholder="Password" required/><button>Dealer Login</button></form><button className="secondary" onClick={()=>{setMode("signup");setM("")}}>Create New Account</button><button className="secondary" onClick={()=>{setMode("forgot");setM("")}}>Forgot Password?</button></>}{mode==="signup"&&<form onSubmit={signup}><input name="name" placeholder="Contact name" required/><input name="business_name" placeholder="Business / Dealership name" required/><input name="mobile" placeholder="Mobile" required/><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" minLength={6} placeholder="Create password" required/><input name="city" placeholder="City" required/><input name="address" placeholder="Business address" required/><input name="inventory_count" type="number" min="0" placeholder="Approx inventory count"/><input name="services" placeholder="Services offered"/><textarea name="message" placeholder="About your dealership"/><button>Create Dealer Account & Continue on WhatsApp</button><button type="button" className="secondary" onClick={()=>setMode("login")}>Back to Login</button></form>}{mode==="forgot"&&<form onSubmit={forgot}><input name="email" type="email" placeholder="Registered email" required/><button>Send Reset Link</button><button type="button" className="secondary" onClick={()=>setMode("login")}>Back to Login</button></form>}<p>{m}</p>{profile&&!profile.active&&<button onClick={()=>db.auth.signOut().then(()=>location.reload())}>Close</button>}<a href="/">← Customer Website</a></div></main>;
 return <main><header><div className="brand"><b>ROHILLA DRIVE DEALER</b><small>Private Portal</small></div><button onClick={()=>db.auth.signOut().then(()=>location.reload())}>Logout</button></header><section className="section"><h1>Submit Dealer Vehicle</h1><p>Dealer submissions stay draft until ROHILLA DRIVE approval.</p><form className="adminForm" onSubmit={add}><input required placeholder="Brand" value={f.brand||""} onChange={e=>setF({...f,brand:e.target.value})}/><input required placeholder="Model" value={f.model||""} onChange={e=>setF({...f,model:e.target.value})}/><input placeholder="Variant" value={f.variant||""} onChange={e=>setF({...f,variant:e.target.value})}/><input required type="number" placeholder="Year" value={f.year||""} onChange={e=>setF({...f,year:e.target.value})}/><input required type="number" placeholder="KM" value={f.km||""} onChange={e=>setF({...f,km:e.target.value})}/><input required placeholder="Fuel" value={f.fuel||""} onChange={e=>setF({...f,fuel:e.target.value})}/><input required type="number" placeholder="Owners" value={f.owner_count||""} onChange={e=>setF({...f,owner_count:e.target.value})}/><input required type="number" placeholder="Asking Price ₹" value={f.price||""} onChange={e=>setF({...f,price:e.target.value})}/><input required placeholder="City" value={f.city||""} onChange={e=>setF({...f,city:e.target.value})}/><textarea placeholder="Description / features" value={f.notes||""} onChange={e=>setF({...f,notes:e.target.value})}/><label className="upload">Vehicle photos<input required multiple accept="image/*" type="file" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label><button>Submit for Admin Approval</button></form><p>{m}</p></section><section className="section"><h2>My Submitted Vehicles ({cars.length})</h2><div className="grid">{cars.map(c=><article className="card" key={c.id}><div className="photo real">{c.vehicle_photos?.[0]?.url&&<img src={c.vehicle_photos[0].url}/>}</div><div className="body"><h3>{c.brand} {c.model} {c.variant}</h3><small>{c.status}</small></div></article>)}</div></section></main>}
