"use client";
import {useEffect,useState} from "react";
import {supabase} from "../supabaseClient";
import {LANGUAGE_STORAGE_KEY,ROHILLA_LANGUAGES,languageByCode} from "../lib/rohilla-languages";

declare global {interface Window{webkitSpeechRecognition?:any;SpeechRecognition?:any}}

async function translate(text:string,target:string,source:string){try{const r=await fetch("/api/translate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,target,source})});const j=await r.json();return {text:j?.translations?.[0]||text,configured:Boolean(j?.configured)}}catch{return {text,configured:false}}}

export default function LanguageAssist(){
 const db=supabase();const [lang,setLang]=useState("pa-IN");const [text,setText]=useState("");const [english,setEnglish]=useState("");const [f,setF]=useState<any>({city:"Ambala City"});const [busy,setBusy]=useState(false);const [note,setNote]=useState("");const [listening,setListening]=useState(false);
 useEffect(()=>setLang(localStorage.getItem(LANGUAGE_STORAGE_KEY)||"pa-IN"),[]);
 function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setNote("Voice recognition is not available in this browser. Type your message instead.");return}const r=new SR();r.lang=languageByCode(lang).speechCode;r.interimResults=false;r.continuous=false;setListening(true);r.onresult=(e:any)=>{setText(e.results?.[0]?.[0]?.transcript||"");setListening(false)};r.onerror=()=>{setListening(false);setNote("Voice capture stopped. Please type your message.")};r.onend=()=>setListening(false);r.start()}
 async function preview(){if(!text.trim())return;setBusy(true);setNote("Preparing Rohilla operator view…");const x=lang==="en-IN"?{text,configured:true}:await translate(text,"en-IN",lang);setEnglish(x.text);setBusy(false);setNote(x.configured?"Translation ready ✓ Rohilla operator can read the English view while your original words are preserved.":"Your original message is preserved. Live translation provider still needs to be connected.")}
 async function submit(e:React.FormEvent){e.preventDefault();if(!text.trim())return;setBusy(true);const x=english?{text:english,configured:true}:lang==="en-IN"?{text,configured:true}:await translate(text,"en-IN",lang);const stored=[`Customer language: ${lang}`,`Original message: ${text}`,x.text!==text?`English operator view: ${x.text}`:""].filter(Boolean).join("\n");const {error}=await db.from("leads").insert({customer_name:f.name,customer_phone:f.phone,requirement:"Multilingual vehicle / mobility request",message:stored,status:"new",source:"rohilla_language_bridge",enquiry_type:"multilingual_request",customer_city:f.city||null});setBusy(false);if(error){setNote(error.message);return}setNote("Request saved ✓ Rohilla Drive has your original message and operator view.")}
 return <main><header><div className="brand"><b>ROHILLA LANGUAGE BRIDGE</b><small>Customer Multilingual Assistance</small></div><div className="row"><a className="call" href="/assistant">Rohilla AI</a><a className="call" href="/">Customer Website</a></div></header><section className="hero"><div className="heroText"><span>ANY REGION • ONE VEHICLE NETWORK</span><h1>Found a vehicle in another state? Language should not stop the deal.</h1><p>Speak or type in your own language. Rohilla Drive preserves the original message and prepares an operator-friendly translation for coordination.</p></div></section><section className="section"><form className="adminForm" onSubmit={submit}><label>Your language</label><select value={lang} onChange={e=>{setLang(e.target.value);localStorage.setItem(LANGUAGE_STORAGE_KEY,e.target.value);setEnglish("")}}>{ROHILLA_LANGUAGES.map(l=><option key={l.code} value={l.code}>{l.nativeName} — {l.name}</option>)}</select><button type="button" onClick={voice}>{listening?"🎙️ Listening…":"🎙️ Speak in your language"}</button><textarea required style={{minHeight:140}} value={text} onChange={e=>{setText(e.target.value);setEnglish("")}} placeholder="Tell us which vehicle you liked, where you are, and what help you need."/><button type="button" onClick={preview} disabled={busy||!text.trim()}>Preview Rohilla operator view</button>{english&&<div className="notice"><b>Operator view:</b><br/>{english}</div>}<input required placeholder="Your name" value={f.name||""} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="Mobile / WhatsApp number" value={f.phone||""} onChange={e=>setF({...f,phone:e.target.value})}/><input placeholder="Your city / state" value={f.city||""} onChange={e=>setF({...f,city:e.target.value})}/><button disabled={busy}>{busy?"Saving…":"Send to Rohilla Drive"}</button></form>{note&&<div className="notice">{note}</div>}</section><section className="section dark"><div className="about"><h2>Rohilla Cross-State Assist</h2><p>Vehicle discovery in one state, customer in another: language bridge, remote verification, inspection coordination, video walk-around, documentation/RC workflow, transporter handoff and Trusted Assist can stay inside one Rohilla Drive journey.</p></div></section></main>
}
